- signature/signature.go
- version/version.go
fine grained version variables (like in OCI projects) might not need this _now_
> version: adjust variables

- docker/docker_image_src.go
- docker/docker_image_src_test.go
- image/image.go
- manifest/fixtures/v2s1-unsigned.manifest.json
- manifest/fixtures_info_test.go
- manifest/manifest.go
- manifest/manifest_test.go
We now pay attention to the `Content-Type` header, but the returned value `application/vnd.docker.distribution.manifest.v1+prettyjws` was not recognized.
> Fix handling of Docker Hub images

- directory/directory_dest.go
- docker/docker_image.go
- docker/docker_image_dest.go
- image/image.go
- openshift/openshift.go
- signature/policy_eval_signedby_test.go
- types/types.go
This is an attempt to fix https://github.com/projectatomic/skopeo/pull/102#issuecomment-228747350 so we can move on with https://github.com/containers/image/pull/23 w/o breaking `skopeo copy` when working with the Atomic Registry.
@mtrmac PTAL
> *: add SupportedImageDestinationMIMEType to types.ImageDestination

- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/image.go
- manifest/fixtures/ociv1.manifest.json
- manifest/fixtures/ociv1list.manifest.json
- manifest/manifest.go
- manifest/manifest_test.go
- oci/oci_dest.go
/cc @mtrmac @sgotti
There are still a couple of stuff to be taken care of here but pls review and comment if you can
Most notably we need to take care of https://github.com/projectatomic/skopeo/pull/102#issuecomment-228747350 /cc @mtrmac
> OCI ImageDestination

- .travis.yml
- Makefile
Note that this is branched against commit 1a7569b24e0da9fdd777a112ae663cdfcb3d24f7 , not latest `master`; latest `master` currently breaks `skopeo` (pending projectatomic/skopeo#133 ).
Fixes #13 .
> Add (make test-skopeo) and run it in Travis CI

- directory/directory_dest.go
- directory/directory_src.go
- directory/directory_test.go
- doc.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_utils.go
- oci/oci_dest.go
- openshift/openshift.go
- signature/policy_eval_signedby_test.go
Fairly simple PR extracted from https://github.com/containers/image/pull/30
@mtrmac you already ack'ed there also. I'll fix skopeo as soon as we merge this.
> Cleanup API

- directory/directory_dest.go
- directory/directory_src.go
- directory/directory_test.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_utils.go
- image/image.go
- oci/oci_dest.go
- openshift/openshift.go
- signature/policy_eval.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- types/types.go
This cleans up Docker reference handling, primarily to rely more on `docker/reference.Named` than on strings. Conceptually a part of #33 , but usable and better to review stand-alone.
See the individual commits for detailed comments; the last one is the most important/disruptive.
`test-skopeo` will fail, but succeeds with `SKOPEO_REPO=mtrmac/skopeo SKOPEO_BRANCH=docker-references`; see also https://github.com/projectatomic/skopeo/pull/143 .
> Clean up Docker reference handling

- directory/directory_dest.go
- directory/directory_src.go
- directory/directory_test.go
- directory/directory_transport.go
- directory/directory_transport_test.go
- doc.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_transport.go
- docker/docker_transport_test.go
- docker/docker_utils.go
- image/image.go
- oci/oci_dest.go
- oci/oci_transport.go
- oci/oci_transport_test.go
- openshift/openshift.go
- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
- signature/policy_eval.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- transports/transports.go
- transports/transports_test.go
- types/types.go
This is split from #33 to make the review process a bit less overwhelming.
Introduces `types.ImageTransport` and `types.ImageReference`, and reorganizes the code to work with `ImageReference` for image identity.
Does not change anything about the behavior, except for the last commit which takes advantage of the ability to get an `ImageReference` from a `types.Image` to improve some error messages.
See individual commits for detailed description and rationale.
> Reference abstraction

- docker/docker_client.go
- openshift/openshift.go
And avoid creating 3 clients in `docker_client.go`
@mtrmac PTAL
> docker,openshift: create http.Client with Timeout

- directory/directory_transport.go
- directory/directory_transport_test.go
- directory/explicitfilepath/path.go
- directory/explicitfilepath/path_test.go
- docker/docker_transport.go
- docker/docker_transport_test.go
- docker/policyconfiguration/naming.go
- docker/policyconfiguration/naming_test.go
- oci/oci_transport.go
- oci/oci_transport_test.go
- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
- signature/fixtures/policy.json
- signature/json.go
- signature/policy_config.go
- signature/policy_config_test.go
- signature/policy_eval.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match_test.go
- signature/policy_types.go
- types/types.go
@runcom PTAL . This is by no means finished, but shows the direction I’m planning to use, early feedback on the API would help me avoid a dead end.  Start with `types.go` I think, I will comment more on the code.
> Transport-abstracted signature policy

- openshift/openshift.go
This adds support for storing signatures in Atomic Registry, assuming server-side support per (merged) openshift/origin#8371 and (currently unmerged) openshift/origin#9181 .
(Marked as WIP because the server side is missing, and because this currently requires a cluster-wide “update signatures” privilege, which seems impractical, so future changes of the API cannot be ruled out. Also, this is currently done as 2 commits to preserve the 2 possible ways to upload signatures, after the decisions are final they should be squashed.)
> OpenShift native signatures

- directory/directory_transport.go
- directory/directory_transport_test.go
- oci/oci_transport.go
- oci/oci_transport_test.go
Use `filepath.Clean()` to verify that the paths are in a canonical format, to catch simple and easy to detect mistakes like double slashes etc.
> Validate directory paths in policy configuration scopes

- directory/directory_dest.go
- directory/directory_test.go
- docker/docker_image_dest.go
- oci/oci_dest.go
- oci/oci_dest_test.go
- openshift/openshift.go
- types/types.go
This is necessary to prevent using layers which have been tampered with.
To implement this, `dir:` and `oci:` now store data into temporary files, and `Rename()` when all data is successfully copied and validated.
We do not do anything extra for `docker:`, hoping that the mandatory `digest=` parameter in the API call is sufficient.
> Require ImageDestination.PutBlob to fail and delete data on error in source stream

- signature/policy_config.go
- signature/policy_config_test.go
- types/types.go
This is the API most applications should use to get the policy for the current host.
Also adds a `types.SystemContext` per discussions in https://github.com/containers/image/pull/41 and elsewhere, to make the functions testable and usable in special situations like chroots.
(Though, `signature.DefaultPolicy()` with an override is not that different from `signature.NewPolicyFromFile()`.)
> Add signature.DefaultPolicy()

- docker/docker_image_src.go
`%v` on a `[]byte` is an unreadable list of integer values; convert the body into a string.
> Improve error reporting when deleting images

- directory/directory_src.go
- directory/directory_test.go
- directory/directory_transport.go
- directory/directory_transport_test.go
- doc.go
- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_transport.go
- docker/docker_transport_test.go
- image/image.go
- manifest/manifest.go
- oci/oci_dest_test.go
- oci/oci_transport.go
- oci/oci_transport_test.go
- openshift/openshift.go
- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
- signature/policy_config.go
- signature/policy_config_test.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match_test.go
- types/types.go
… immediately needed for #52 , but also #56 was done expecting these API changes to occur.
Primarily extends usage of `types.SystemContext` to creation of transport objects.  See individual commits for detailed comments.  Should not change behavior.
> API changes

- copy/copy.go
- copy/copy_test.go
As we’ve discussed several times, this moves the core of `skopeo copy` into the library.
Depends on way too much pending work, I will rebase as necessary.
> Move copy implementation into containers/image

- copy/copy.go
- copy/copy_test.go
Per conversation in https://github.com/containers/image/pull/56#discussion_r77046967 .
> Clean up `digestingReader` failure reporting

- manifest/manifest.go
- manifest/manifest_test.go
- oci/oci_dest.go
Also use github.com/opencontainers/image-spec instead of copy/pasting
structs and consts around.
> oci: use opencontainers/image-spec

- copy/copy.go
- directory/directory_dest.go
- directory/directory_test.go
- docker/docker_image_dest.go
- oci/oci_dest.go
- oci/oci_dest_test.go
- openshift/openshift.go
- types/types.go
This patch is a WIP to discuss about changing the signature of `PutBlob`. I'll fix the other types if we get consensus on this.
Basically, while working on `docker save --format oci` (https://github.com/runcom/docker/commits/oci-save-load), I noticed the `PutBlob` interface is really awful since it requires callers to provide their own _digest_. This isn't ensuring that the digest file name is the same as the one from the stream and the OCI image specification requires this (also).
Here I'm basically changing `PutBlob` to return the computed digest from the given stream (and also the size of the blob being saved).
I've noticed in `copy/copy.go` there's something (I've already forgotten) about _digest verification_ also but I feel this change is needed to have a consisted usage of the …
> ImageDestination.PutBlob returns digest and size

- copy/copy.go
- directory/directory_dest.go
- directory/directory_test.go
- docker/docker_image_dest.go
- oci/oci_dest.go
- openshift/openshift.go
- types/types.go
This allows `copy.go` to bail early, without transferring any large blobs.
(This is an attribute of an `ImageDestination` and not an `ImageTransport` because supporting signatures may depend on the individual destination, e.g. depending on server version or whether a sigstore lookaside has been configured for that destination.)
Also reorders the `ImageDestination` methods in some cases, to separate basic management / capability query / upload groups.
> Add ImageDestination.SupportsSignatures

- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
- oci/oci.go
- transports/transports.go
Fix https://github.com/containers/image/issues/75
@mtrmac slightly different path than discussed but ... I believe same net result.
I had to ofc change the transport name - I expect to still use `oci` in skopeo though. (unless I'm missing something)
> oci: mv to oci-layout

- image/image.go
carry https://github.com/containers/image/pull/58 after rebase
Signed-off-by: Tim Waugh <twaugh@redhat.com>
> Use special case for text/plain media type

- docker/docker_client.go
- types/types.go
Then document `SystemContext.DockerInsecureSkipTLSVerify` more precisely.
Also simplify `dockerClient.ping()` a bit.
Fixes #45 .
> Do not use HTTP for docker registries if ~SystemContext.DockerInsecureSkipTLSVerify

- docker/fixtures/registries.d/internal-example.com.yaml
- docker/fixtures/registries.d/internet-user.yaml
- docker/lookaside.go
- docker/lookaside_test.go
- docs/registries.d.md
This makes it much clearer how that URL is supposed to be used.
(And it could also clear the way to, in the future, have a write server. Perhaps.)
> Rename sigstore-write to sigstore-staging

- openshift/openshift-copies.go
Otherwise all map values were references to a single object with the same value.
Fixes #91
> Use a fresh instance of map values when unmarshaling Named* map forms

- copy/copy.go
- image/docker_schema1.go
- image/docker_schema2.go
- image/image.go
- manifest/manifest.go
- manifest/manifest_test.go
- signature/policy_reference_match_test.go
- types/types.go
@runcom PTAL
This is a subset of #93, preparing to be able to modify manifests. Does nothing so far, but will be shared by #93, pushing to Docker tags, and schema conversions.
See individual commits for a bit more description.
> Add manifest update infrastructure

- copy/copy.go
- directory/directory_dest.go
- directory/directory_test.go
- docker/docker_image_dest.go
- image/docker_schema1.go
- image/docker_schema2.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- types/types.go
@runcom PTAL
This integrates #90 , and builds on it to compress layers in `copy.go` if they are uncompressed and the destination prefers compressed ones.
If any layer is modified, we need corresponding updates to the manifest; hence `types.Image.UpdatedManifest`. I don’t particularly _like_ that interface, but it works for now, and it seems possible to extend it to the other anticipated uses (1) updating a tag when pushing schema1, 2) conversion to a different MIME type).  Any better ideas would be welcome. (Of course, an ugly interface is not a show-stopper; we can clean this up later after the uses are better knkown.)
This seems to work fine, though the schema1 manifest updates will need a closer look. And tests, I suppose?
> Layer compression

- docker/docker_image_dest.go
- openshift/openshift.go
Not pushing to a tag makes the image impossible to pull with a tag.
This is not really correct because we keep the Name and Tag in schema1 manifests unmodified, and older registry versions (in particular OpenShift 1.1) do inspect those fields.  But, it is better than nothing,
and for OpenShift manifest uploads via the Docker API ( #95 ) a tag is required.
_Recent_ versions of registry, both docker/distribution and OpenShift, AFAICS completely ignore the tag in schema1 manifests; so that should work fine.
> Use tags when pushing to dockerImageDestination

- openshift/openshift.go
Instead of manipulating an `ImageStreamMapping` and having to do exactly what OpenShift does, just use the Docker Registry API and let the server side deal with that.
This fixes “unexpected end of JSON input” when uploading schema2 manifests (because we didn’t also include the config object), and should resolve https://github.com/projectatomic/skopeo/issues/208 (by using the existing code on the server side)
> Use dockerImageDestination.PutManifest in openshiftDestination.PutManifest

- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
There is no reason not to, and it will allow `skopeo inspect atomic:` to work.
> Implement openshiftReference.NewImage

- docker/docker_client.go
- openshift/openshift.go
This timeout is a no sense I've added few months ago IIRC - for pushes that take more than 1 minute is idiotic to just cancel the request, imagine a big layer...
@mtrmac PTAL - this sort of stuff should be better handled through channels and context.Context, not just by adding a client's timeout.
> docker: remove client's timeout

- docker/docker_image_dest.go
This will make it easier for the user to figure out how to proceed.
As pointed out in https://github.com/projectatomic/atomic/issues/644#issuecomment-248969687 (though note that _that_ error message comes from `atomic`, not `containers/image`).
> When failing to write to http/https sigstore, suggest sigstore-staging:

- copy/copy.go
Silly me, we always want the new line - even on error if some of the progress has already been read 
> copy: progress fix

- docker/docker_client.go
This does not manifest with skopeo because skopeo usually uses `contextFromGlobalOptions()` which is never `nil`, but it still is a violation of the documented API (and breaks the copy-lookalike I use for quick debugging).
> Fix dockerClient use with nil SystemContext

- copy/copy.go
A few places were using `options.ReportWriter` instead of `reportWriter` which has the `ioutil.Discard` fallback.
Also handle `options == nil` to be consistent with the other uses of `options`.
> Fix the options.ReportWriter == nil case

- oci/layout/oci_dest.go
will need a skopeo re-vendor of opencontainers/image-spec
This is fixing CI:
```
$ make deps
go get -t ./...
oci/layout/oci_dest.go:156: undefined: specs.Descriptor
make: *** [deps] Error 2
The command "make deps" failed and exited with 2 during .
```
> oci/layout: fix deps

- docker/docker_image_src.go
This PR exports errFetchManifest. It's quite useful to have error types exported so that libraries
can avoid substring matchers. 
Thanks,
@albertoleal and @callisto13
> Make `errFetchManifest` public

- docker/docker_client.go
- docker/docker_client_test.go
Docker can store auth entries with schema prefix or even path suffix.
See an example:
{
"auths": {
"10.3.10.88:5000": {
...
},
"http://10.3.10.88:5000/v2/": {
...
},
"https://10.3.10.88:5000": {
...
},
"https://index.docker.io/v1/": {
...
}
}
}
The entries were created using command `docker login` of upstream Docker
1.12. Let's normalize the auth keys before trying to match against
hostname.
Signed-off-by: Michal Minář <miminar@redhat.com>
> Be benevolent to .docker/config.json file

- copy/copy.go
- directory/directory_src.go
- docker/docker_image_src.go
- image/docker_list.go
- image/image.go
- manifest/manifest.go
- openshift/openshift.go
- signature/policy_eval_simple_test.go
- signature/policy_reference_match_test.go
- types/types.go
Related to https://github.com/containers/image/issues/114
Needed for projectatomic/docker#200 - w/o this pulling an image with a manifest list is broken into docker.
Rigth now, by not supporting the manifest list media type we always got the _single_ manifest for the amd64 arch instead of the whole manifest list and this broke docker because computing the digest for that single manifest isn't the same as the digest from the manifest list.
Also note that if you pull-by-digest a manifest list in docker you get back exactly the same manifest list digest (and not the one from the target manifest) which is confusing to me but still, it's how docker works.
@mtrmac PTAL - this is blocking
> manifest: enable DockerV2List

- docker/docker_client.go
- docker/docker_client_test.go
- types/types.go
The automatic credentials retrieval built into containers/image doesn't play at all with external credentials store. Furthermore, we need a way to pass credentials to containers/image from docker/docker (projectatomic/docker#200). This also fixes a bunch of docker's integration tests in projectatomic/docker#200.
This patch just gives precedence to any `ctx.DockerAuthConfig` field before diving deep into the system to lookup credentials into `~/.docker/config.json`. So no real behavior change in skopeo so far. We'll need to tackle #111, at which point we'll made the automatic retrieval optional as per https://github.com/containers/image/pull/41#issuecomment-233338484.
Close #41 
Close projectatomic/skopeo#106
This is also needed by kubernetes-incubator/cri-o#8 since there it's k8s itself …
> types,docker: add DockerAuthConfig

- copy/copy.go
- directory/directory_transport.go
- directory/directory_transport_test.go
- docker/docker_image.go
- docker/docker_transport.go
- image/docker_schema1.go
- image/docker_schema2.go
- image/image.go
- image/manifest.go
- image/memory.go
- image/sourced.go
- image/unparsed.go
- oci/layout/oci_transport.go
- openshift/openshift_transport.go
- signature/policy_eval.go
- signature/policy_eval_baselayer.go
- signature/policy_eval_signedby.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- types/types.go
@runcom PTAL.
This is a pretty big refactoring of `image/`, see individual commits for details.  The overall ideas:
- Signature verification happens on `UnparsedImage`, which structurally prevents interpreting too much before we know the image is admissible.
- `genericImage` becomes `sourcedImage`, a very thin layer over `UnparsedImage` and `genericManifest`
- Instead of `UpdatedManifest`, we now have `UpdatedImage`. This does not change much now, but will be a way to return also `config.json` and other objects.
I haven’t actually updated the schema conversion work to take advantage of `UpdatedImage` yet, but I expect it to help with the API shape noticeably.
Tests pass in https://github.com/mtrmac/skopeo/tree/image-refactor-test , although note that that includes …
> Refactor c/i/image

- directory/directory_transport.go
- docker/docker_transport.go
- docker/docker_transport_test.go
- docker/policyconfiguration/naming.go
- docker/policyconfiguration/naming_test.go
- docker/reference/doc.go
- docker/reference/reference.go
- docker/reference/reference_test.go
- oci/layout/oci_transport.go
- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
- signature/policy_config.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- types/types.go
As discussed into https://github.com/containers/image/issues/99
@mtrmac PTAL, making a PR for skopeo check if everything's ok over there. I'll check with projectatomic/docker#200 as well.
> docker: fork docker/docker/reference pkg

- docker/docker_client.go
- types/types.go
Package users may want to identify themselves with the registry for tracking purpose (as Docker engine is doing). This patch adds a new field to `types.SystemContext` called `DockerRegistryUserAgent` which if not empty is added as an `User-Agent` header to each request to the registry.
@mtrmac PTAL, this is needed for projectatomic/docker#200 and it's blocking it since docker's integration tests are failing w/o this. 
> types: add DockerRegistryUserAgent to SystemContext

- docker/docker_image_src.go
Instead of that big json, reuse docker/distribution registry errors since we are already used by that in Docker. This change isn't a big deal but at least I got tests working in projectatomic/docker#200 and errors are much much nicer with skopeo:
```
$ ./skopeo inspect docker://runcom/doesnotexist
FATA[0001] manifest unknown: manifest unknown
$ ./skopeo inspect docker://asdasd
FATA[0002] unauthorized: authentication required
```
Note those errors above are the same docker print out.
This is a blocker for projectatomic/docker#200 because w/o this we don't have any way/mapping to tell docker to fallback to v1 and we end up breaking docker.
@mtrmac PTAL
@baude @aweiteka sort of related to https://github.com/projectatomic/atomic/issues/636
> docker: reuse docker/distribution registry errros

- copy/copy.go
It is a bit surprising to see “Uploading” during (atomic pull).
> Say “Copying” instead of “Uploading” in progress and error messages

- image/docker_list.go
- image/unparsed.go
- types/types.go
In particular, when copying from a digested reference, and when choosing a manifest from a manifest list (previously this was a way to bypass signatures!)
> Verify manifests against digests when known.

- docs/registries.d.md
Provide basic formatting markup so md2man renders properly.
@mtrmac please review
> Support man page formatting

- directory/directory_src.go
- docker/daemon/daemon_src.go
- docker/docker_image_src.go
- image/manifest.go
- image/sourced.go
- openshift/openshift.go
- types/types.go
https://github.com/containers/image/pull/139 has changed the semantics to always expect a value from an `ImageSource`; that’s not really great when the source has no idea, but we don’t have optionals in Golang to distinguish between a nonsensical `""` and unavailable, so this is at least making the documentation consistent.
Hopefully `ImageSources` which call `manifest.GuessMIMEType` in `GetManifest` will not proliferate…
> Update GetManifest documentation for empty MIME type

- README.md
Close https://github.com/containers/image/issues/146
> Add more description to the containers/image library

- image/manifest.go
- oci/layout/oci_src.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
fix #141 .
Test with skopeo:
```sh
Copying blob sha256:c04b14da8d1441880ed3fe6106fb2cc6fa1c9661846ac0266b8a5ec8edf37b7c
0 B / 974 B [-----------------------------------------------------------------]
Copying config sha256:c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc
0 B / 1.44 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
Copying blob sha256:c04b14da8d1441880ed3fe6106fb2cc6fa1c9661846ac0266b8a5ec8edf37b7c
0 B / 974 B [-----------------------------------------------------------------]
Copying config sha256:c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc
0 B / 1.44 KB [---------------------------------------------------------------]
Writing …
```
> Implement OCI image source

- docs/policy.json.md
- signature/fixtures/policy.json
- signature/policy_config.go
- signature/policy_config_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- signature/policy_types.go
This adds `signedIdentity` `type:` `matchRepoDigestOrExact`, and makes it the default.
With `matchRepoDigestOrExact`, Tag references require a signature with a matching repo:tag (`Exact`), digest references require a signature with a matching repo (and any tag [or digest]; `RepoDigest`), with the digest itself still being validated in `image.UnparsedImage`, independently of signature processing.
Rationale from  https://github.com/mtrmac/image/commit/6e18d3010b10708245f42db5612dd303dfb4769a#commitcomment-19557682 for not doing a digest check in the identity matching component:
> I have implemented the digest check in here—and thrown it away, it really does not make sense to me here. If a single `PolicyReferenceMatch` implementation does a more strict digest check than the one in …
> Add support for digest references to signature enforcement

- docker/docker_client.go
@mtrmac PTAL asap for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1393816
> docker: set proxy from env for custom transport

- oci/layout/oci_src.go
OCI source: return error if open blob failed. This is needed by [here](https://github.com/containers/image/blob/master/image/docker_schema2.go#L85)
Signed-off-by: Ye Yin <eyniy@qq.com>
> OCI source: return error if open blob failed

- directory/directory_src.go
- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/docker_schema1.go
golint nowadays rejects it with
`error strings should not be capitalized or end with punctuation or a newline`
(… but it accepts leading capitalization anyway, so this does not change any of the many instances of that.)
>  Remove trailing punctuation from error messages

- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/daemon/daemon_transport.go
- docker/daemon/daemon_transport_test.go
- docker/daemon/daemon_types.go
- transports/transports_test.go
This fixes #143 , by deciding on a reference format and implementing it.
Allow either a `!NameOnly` named reference, or a `sha256:`hex digest.  Both forms can be used for an `ImageSource`; `ImageDestination` accepts only a name`:`tag value.
Because the `sha256:`hex reference values make it impossible to create a reasonable policy hierarchy, only support a trivial namespace with a single per-transport policy.
This does not yet deal with the way projectatomic/docker/reference breaks the normalization (#72).
> Finish docker-daemon:

- docker/docker_client.go
Just cleaning up old comments/todos. This is no longer necessary as docker's registries auth is already being setup with `types.DockerAuthConfig`.
> docker: cleanup old comment

- copy/copy.go
- directory/directory_dest.go
- directory/directory_src.go
- directory/directory_test.go
- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/docker_schema2.go
- image/docker_schema2_test.go
- manifest/manifest.go
- oci/layout/oci_dest.go
- oci/layout/oci_src.go
- openshift/openshift.go
- types/types.go
@mtrmac PTAL
More information available at https://github.com/docker/docker/pull/27961
> [WIP] *: support layers federation

- docker/docker_client.go
Fully fix https://github.com/projectatomic/docker/issues/214 - checked directly with `docker`.
I'm not even sure why we had that check on `ping` - `errors` from `PingResult` isn't used anywhere also. Should be pretty safe to dump this code to me.
@mtrmac PTAL
> docker: remove silly error checks

- oci/layout/oci_dest.go
Fixes #178
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> oci: flip ShouldCompressLayers to always true

- docker/docker_client.go
- types/types.go
This is needed for the `projectatomic/docker` integration - otherwise if `dockerd` runs with `--disable-legacy-registry=true` and we ping V1, we're breaking that flag usage. Docker will set `DockerDisableV1Ping` to `true` if the daemon flag is set to true.
@mtrmac PTAL
> docker: add an option to disable V1 ping

- docker/docker_client.go
- types/types.go
This works as docker does upstream (by reading CAs as well from `/etc/docker/certs.d/`, here we just read from the input context).
This is also needed by the `projectatomic/docker` integration of `containers/image`.
For `skopeo copy` we'll likely do something like `--[src|dest]-cert` as we did for credentials - other skopeo commands would be unaffected except for the naming conventions around certs names and suffixes.
@mtrmac PTAL
> docker: use registry and system CAs

- .travis.yml
- Makefile
- copy/copy.go
- directory/directory_dest.go
- docker/daemon/daemon_dest.go
- docker/docker_client.go
- docker/docker_client_test.go
- docker/docker_image_dest.go
- image/docker_schema2_test.go
- image/memory.go
- image/sourced.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
- transports/transports.go
- types/types.go
This patch adds containers/storage as a backend type called 'oci-storage', using a storage.Mall initialized with the library's default settings, or using an externally-initialized storage.Mall.
An image's blobs are stored either as oci-storage layers (if they look like filesystem layers) or (alongside the manifest and signatures) as named big data items associated with the image.
Record-keeping (so that we can remember which blobs were layers and which weren't) are encoded as a JSON object which is stored as the oci-storage image's metadata.
The type of compression which we detected around a layer blob when it was imported is encoded as a field in a JSON object which is stored as the oci-storage layer object's metadata, and is reapplied if we need to export the layer later.
If we find …
> Add support for containers/storage

- Makefile
- docker/reference/reference.go
- docker/reference/reference_test.go
There has been a change in upstream (docker/distribution), where they
now require users of the digest library to load algorithms into the
binary (in other words they do .Available checks on crypto algorithms).
This fixes the unit test failures with "unsupported digest algorithm".
Since skopeo now also has containers/storage we have to pass it our
BUILDTAGS otherwise you'll get build failures in the CI.
Fixes #189 
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> *: fix the CI

- signature/mechanism.go
This reverts commit 7f87ae0ac78aa57de3b554540ac014920fa5634b.
With https://github.com/mtrmac/gpgme/pull/1 this is no longer necessary.
(A future rerunning of `hack/vendor.sh` in skopeo will pick up both the updated `mtrmac/gpgme` and `containers/image`; there is no rush.)
> Revert "provide better error when key not found"

- docker/docker_client.go
`./skopeo inspect gcr.io/google_containers/pause-amd64:3.0` currently fails while pulling from a `gcr.io` repository which requires auth is ok. This was my bad before the shutdown. This patch fixes both unauthenticated and authenticated pulls.
> docker: fix unauthenticated pulls from gcr.io

- image/memory.go
Instead of returning a probably-wrong guess from memoryImage.Size() (per https://github.com/containers/image/pull/63#pullrequestreview-14982893), return -1, to indicate that we don't know the right answer.
> Don't fake a bad answer from memoryImage.Size()

- openshift/openshift-copies.go
This is the problem with the CI. However, the build system has some dep mgmt issues too, so I'm not sure this will pass either; but this is at least part of the fix. I'm going to try putting together a build system today for testing with dependencies, I have everything working with godep minus some mishaps. I'll report more later.
> openshift: use new k8s.io/apimachinery GOPATHs for kube API

- docker/reference/reference.go
`docker/distribution/reference.ParseNamed` now (as of 6170ac53daed40ebbebc9fe5f482495d01f09f12) refuses input in a non-fully-explicit form; the new `ParseNormalizedNamed` accepts it and normalizes it into the fully explicit form.  (One would expect it to be the other way around…)
So, use `ParseNormalizedNamed` now.  This is a minimal fix for the failing tests.
Because `docker/distribution/reference` now does all the normalization, we can use it and drop our `docker/docker/reference` fork (which will go away upstream), at least in the short term.  (Longer-term we may need to reintroduce it again if `projectatomic/docker` decided to modify _that_.) But that’s more than just fixing the tests, so that will be a separate PR.
> Use docker/distribution/reference.ParseNormalizedNamed

- signature/json.go
- signature/signature.go
See individual commits for more details.
> Trivial fixes

- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/docker_schema2.go
- image/docker_schema2_test.go
- image/fixtures/oci1.json
- image/fixtures/schema2-to-oci1.json
- image/oci.go
- image/oci_test.go
- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
- openshift/openshift-copies.go
- storage/storage_test.go
https://github.com/opencontainers/image-spec/pull/411 removed the `MediaType` field in `Manifest[List]` causing builds error here. Fix that by teaching docker v2s2 to convert to OCI and remove that ugly manifest conversion in OCI image destination.
@mtrmac @cyphar PTAL
> Fix for image spec

- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
> docker: mimic docker upstream registry authentication

- docker/daemon/daemon_dest.go
This was inadvertently removed during the `HasBlob` addition, but the code below still relies on having a valid value.
(Well, it _could_ be recomputed, we already have the copy code for the `inputInfo.Size` case; this is just the very minimal fix.)
> Restore a check for unknown digest in daemonImageDestination.PutBlob

- docker/docker_client.go
@mtrmac PTAL, just WIP for now as I have to handle tokens refreshing and stuff like that.
> docker: cache bearer tokens

- storage/storage_image.go
When reapplying a blob to an image that's being written to the storage transport, don't enforce that the digest of the reapplied blob matches the blobinfo's digest, if there is one, because compression makes the reapply method (where we reextract the layer, and if it was originally compressed, recompress it) produce data with the same actual content, but with a different compressed digest.
This should fix https://github.com/kubernetes-incubator/cri-o/issues/351.
> Don't enforce digest match in storage.ReapplyBlob

- doc.go
This won't pass just yet.
I gofmt'd the source too, but the `//` syntax requirement that exists now was
throwing off the original example which would just panic.
> Fix top-level source example in godoc

- oci/layout/oci_src.go
OCI JSON blobs no longer contain a mediaType (since 1.0.0-rc4), which
breaks the auto-detection code for MIME types. However, it doesn't make
sense for us to be "auto-detecting" the MIME type of a manifest when the
OCI transport *already knows the mediaType* from the reference. So
instead just return the already-computed mediaType from the descriptor.
Unfortunately, this doesn't work for GetTargetManifest, in which case we
just default to the only valid value at the moment. In future we should
extend this logic to read `/index.json` and figure out what descriptor
referenced the manifest (though any such logic would be questionable
without running a full index on all blobs in the source image).
This is part of fixing projectatomic/skopeo#305.
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> oci: remove MIME type autodetection

- copy/copy.go
- copy/progress_reader.go
- types/types.go
Again, including the other commits for ease of getting things to compile; there
is an example at the end. Only the last commit is relevant in this PR.
This provides a hook and an interval timer for progressed copy operations, such
as image packaging. It only covers the docker endpoints for now and is
untested, again, as a proof of concept for approval.
Users can specify a function which is called at each interval as long as the
copy is progressing. This function is passed the current byte offset of the
copy operation. They can use this to calculate sizes, or percentages, or the
phase of the moon at the time the current byte is downloading. Resolution of
the timer is completely independent.
Here's some code that works with this: it reports byte offsets every 100ms
during both download and …
> Provide large file progress reporting hooks to copy operations

- copy/copy.go
- directory/directory_dest.go
- directory/directory_src.go
- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/docker_schema2_test.go
- image/memory.go
- image/unparsed.go
- oci/layout/oci_dest.go
- oci/layout/oci_src.go
- openshift/openshift.go
- signature/policy_reference_match_test.go
- storage/storage_image.go
- types/types.go
This patch augments the interfaces' close methods with an error return which is
only actually useful in one or two spots for now. However, it can be utilized
later as things fill in.
Fixes #82
> Close with error

- Makefile
Read this bit that got lostwith commit 01381869c6307e5801ce5413c3400d86f75d0b07
> Makefile: fix 'make test'

- Makefile
it applies on top of: https://github.com/containers/image/pull/242
> Use trash instead of vndr

- directory/directory_transport.go
- docker/daemon/daemon_transport.go
- docker/docker_transport.go
- manifest/manifest.go
- oci/layout/oci_transport.go
- openshift/openshift_transport.go
- signature/policy_config.go
- signature/policy_config_test.go
- signature/policy_eval_test.go
- storage/storage_transport.go
- transports/alltransports/alltransports.go
- transports/alltransports/alltransports_test.go
- transports/transports.go
Close #125 
As discussed in #125, this patch creates a new subpkg to import transports independently. projectatomic/docker would greatly benefit from this as it needs just the docker transport (right now).
Those will be the stats in projectatomic/docker + this PR:
```
Showing  76 changed files  with 1,715 additions and 6,770 deletions.
```
@mtrmac PTAL (far from being ready, just a start...)
> *: pluggable transports

- manifest/manifest.go
This reverts commit 0a5f50db799793f161cfc4d8d4fb00c9aa37585e. ,
which broke tests.
Eventually we may need that commit (when updating `image-spec`?), but right now it seems unnecessary and this is the most obvious way to get tests working without having to think :)
> Revert "manifest: remove not needed mediatype"

- docker/docker_image_dest.go
Call `HasBlob` in `dockerImageDestination.PutBlob` so that we only have one copy of the code.
Note that the first commit of this modifies `HasBlob` to fail on unexpected HTTP response statuses, instead of returning “blob not present”; this was modified in #63 but there hasn’t been an explicit explianation why, and right now, with the code duplicated, `PutBlob` is using its own implementation which aborts on such statuses, so AFAICT the change was either unintentional or ineffective. @nalind ?
> Avoid duplication in dockerImageDestionation.{Has,Put}Blob

- copy/copy.go
The following change caused a panic https://github.com/containers/image/commit/cdb838d9ac5776d3b3cc5d7593d2d4d849fa4fbf#diff-5f78baafa6d34438aba66ed64f4b16d5R156
@mtrmac @erikh PTAL
> copy: fix panic on error

- signature/json.go
- signature/json_test.go
- signature/policy_config.go
- signature/policy_config_test.go
- signature/signature.go
- signature/signature_test.go
Instead of relying on `json.Unmarshal` into a `map[string]interface{}`, and dealing with field presence and correct types manually, build a helper based on `paranoidUnmarshalJSONObjects` which verifies field presence automatically, relies on `json.Unmarshal` for enforcing types of unstructured values, and newly rejects JSON objects with duplicate members.
Besides the primary benefit, rejecting ambiguous signatures, this allows us to get rid of the infrastructure for safely manually parsing `map[string]interface{}`. The new `paranoidUnmarshalJSONObjectExactFields` can also be used to simplify `policy.json` parsing a bit.
Also includes one unrelated test bug fix.
See the individual commits for more details.
> Reject duplicate JSON members when parsing signatures

- docker/docker_image_dest.go
This avoids dereferencing a nil result when an error is
encountered on PATCH request.
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
> docker/image_dest: do not deref possibly-nil results

- docker/docker_image_dest.go
After PR #202, PutBlob() now goes through an initial HasBlob()
which may require authentication in order to perform the check;
in such case a push-only scoped token will fail with:
```
service="registry.docker.io",scope="repository:<name>:pull",error="insufficient_scope"
```
This fixes the above case by changing the scope of the token
requested for uploads, allowing pull+push.
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
> docker/image_dest: ask for pull action in token scope

- .travis.yml
- Makefile
- README.md
- copy/copy.go
- signature/docker_test.go
- signature/mechanism.go
- signature/mechanism_gpgme.go
- signature/mechanism_gpgme_test.go
- signature/mechanism_openpgp.go
- signature/mechanism_openpgp_test.go
- signature/mechanism_test.go
- signature/policy_eval_signedby.go
- signature/signature.go
- signature/signature_test.go
This demonstrates an alternative to #198 , which percolates the mechanism choice through the API and does not permit file-format-dependent mechanism selection.
In here, the default mechanism is gpgme; a `containers_image_openpgp` build tag can be used to use openpgp instead.
openpgp does not currently support signing, and is based on mfojtik's implementation (adding GPG home directory support, parsing of unarmored keys, and fixing `ImportKeysFromBytes` semantics).
NOTE: The openpgp backend is not really fleshed out yet. Some of the `mechanism_test.go` tests may be better mechanism-specific, and openpgp definitely needs more tests e.g. for `optionalDir`.
> Allow choosing between a gpgme and openpgp signature backend using a build tag

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
This is provided by the OpenShift-integrated registry. This is equivalent to the atomic: transport (in the “openshift”) subpackage, but    it requires less code and notably does not require an OpenShift login     context to be configured.
See https://github.com/openshift/origin/pull/12504 and     https://github.com/openshift/openshift-docs/pull/3556 for more     information on this API extension.
To preserve compatibility, we always check for a configured lookaside     sigstore first; if that is set up, we use the lookaside and ignore the     registry-native signature storage.  Usually the user would not bother to    set up the lookaside, and use the native mechanism.
See the individual commits for more details.
NOTE: This includes tests using the recording mechanism proposed in #254. …
> Add support for the X-Registry-Supports-Signatures API extension

- docker/lookaside.go
- docker/lookaside_test.go
This
* Changes the file name to use `=` instead of `:`, to avoid a Windows reserved character. Fixes #187 .
* Removes the host name from the path, per the conversation around #120 .
> Change sigstore layout

- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/lookaside.go
- docs/signature-protocols.md
This is primarily the only documentation of the sigstore layout; in addition it comments on the OpenShift API master REST API and the OpenShift docker/distribution API extension.
This is a superset of the documentation in #120 , and incorporates the layout changes in #247 .
> Add documentation for signature access protocols

- copy/copy.go
- directory/directory_dest.go
- docker/daemon/daemon_dest.go
- docker/docker_image_dest.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- storage/storage_image.go
- types/types.go
(WIP because this includes #202 and #203 just because I am lazy to do this several times.)
@runcom PTAL: I know in #63 you have explicitly asked for `ErrBlobNotFound` to be added, but it seems to me that just makes the uses of `HaveBlob` more complex. I can live with the current code if it is indeed is more idiomatic, or perhaps I am missing a cleaner way to use it.
The current interface can return `(haveBlob, _, err)`:
- `(true, nil)`: blob exists
- `(false, ErrBlobNotFound)`: blob does not exist or unknown
- `(false, `other non-nil`)`: unexpected error
i.e. `haveBlob` is equivalent to `err == nil`, which is both redundant and makes the interface unnecessarily difficult to use for the typical case where the caller wants to abort on an unexpected error, and then decide based on haveBlob: …
> RFC WIP: Define the three return states of HaveBlob as true/false/error

- image/docker_schema1.go
- image/docker_schema1_test.go
- image/docker_schema2.go
- image/fixtures/schema1-to-oci-config.json
- image/manifest.go
- image/oci.go
- types/types.go
We can't rely on people hacking around with blobs like https://github.com/kubernetes-incubator/cri-o/blob/master/pkg/storage/runtime.go#L213-L225
Instead, return OCI configuration and fix implementations :)
@mtrmac PTAL
> image: expose OCI configuration struct for all images

- ostree/ostree_dest.go
- ostree/ostree_transport.go
- ostree/ostree_transport_test.go
- transports/alltransports/alltransports.go
- types/types.go
skopeo copy docker://busybox ostree:foo:latest@/ostree/repo
> ostree: new transport

- ostree/ostree_dest.go
I've noticed this while working on the integration with atomic...
UntarPath would just fail when used from a non root user.
The temporary workaround is using GNU Tar.  This part should be fixed in
storage/pkg/archive.
The fix ensures every directory and file is readable/writeable by the
user.
> ostree: fix usermode pull

- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_transport.go
- storage/storage_transport_test.go
This PR changes the way we parse references in the "storage" transport to correctly accept references that include an ID that has a "sha256:" prefix.  It defaults to adding the fully-expanded version of a reference's string value as the image's name, and adds a check to ensure that when attempting to read an image using a reference that included both a name and an ID, that the image we located using the ID actually has the specified name.
> storage: improve handling of references with digests

- ostree/ostree_dest.go
The issue was just fixed in atomic with the current implementation that
doesn't use Skopeo yet.
Apparently there are some images that contain special files and OSTree
doesn't allow to commit these special files.
Closes: https://github.com/projectatomic/atomic/issues/943
> ostree: do not commit special files

- copy/copy.go
- copy/manifest.go
- copy/manifest_test.go
- copy/sign.go
- copy/sign_test.go
- directory/directory_dest.go
- docker/docker_image_dest.go
- docker/tarfile/dest.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- ostree/ostree_dest.go
- storage/storage_image.go
- types/types.go
This modifies `copy.Image` to try a sequence of possibly supported manifest MIME types instead of only a single preferred one; notably this allows using the `docker:` transport with schema1-only registries, although the mechanism is ultimately fully general (i.e. it can deal with OCI-only registries just as well if `SupportsManifestMIMEType` includes OCI).
See the individual commit messages for detailed description;
**NOTE** The final commits, starting with “Define a ManifestTypeRejectedError for ImageDestination.PutManifest”, implement the behavior of only trying a sequence of MIME types if the initial manifest is rejected with a recognized "this is an invalid manifest” error (as opposed to anything else, e.g. insufficient permissions or out of space). This is IMHO more sensible, but it …
> Support run-time manifest type support (e.g. schema1/schema2) autodetection

- openshift/openshift.go
With #264 we can dynamically try pushing using schema2, and fall back to schema1, without relying on a static `SupportedManifestMIMETypes` list. Therefore, modify the `atomic:` transport to use the same set of of statically declared MIME types candidates as the `docker:` transport.
In practical terms, OpenShift registries configured with `acceptschema2: true` will now get schema2 images if the input is schema2 (schema1 images would be copied unmodified as schema1), while `accpetschema2:false` registries will continue to always get schema1.
One notable difference is that `SupportedManifestMIMETypes` affects what we configure the _source_ to accept: e.g. when streaming from `docker:` to s1-only `atomic:`, previously the conversion was done by the `docker:` registry server, but now the …
> Allow using schema2 when pushing to OpenShift

- copy/copy.go
- copy/manifest_test.go
- image/docker_schema1.go
- image/docker_schema2.go
- image/docker_schema2_test.go
- image/manifest.go
- image/oci.go
- image/oci_test.go
- types/types.go
FIXME: Actually handle the manifest-embedded tags in schema 1. Without that, this is a fairly broken implementation (though might be better than nothing I suppose).
**EDIT** When pushing a schema1 image, update the name/tag embedded in the manifest. Recent registry versions ignore the fields, but older ones require them to match the registry/tag used to upload the image.
> Update name/tag embedded into schema1 manifests

- docs/atomic-signature.md
- signature/signature.go
This documents the signature format, in more detail than #59.
> Add documentation for the atomic signature format

- docs/atomic-signature-embedded-json.json
- signature/signature.go
- signature/signature_test.go
- vendor.conf
This schema is a supplement to `docs/atomic-signature.md`, added by #251 ; this PR therefore depends on and includes #251.
Also adds some tests for the schema. See individual commit messages for details.
Quoting `description` inside the schema:
> Consumers of the JSON MUST use the processing rules documented in `atomic-signature.md`, especially the requirements for the `critical` subjobject.
>
> Whenever this schema and `atomic-signature.md`, or the `github.com/containers/image/signature` implementation, differ, it is the `atomic-signature.md` document, or the `github.com/containers/image/signature` implementation, which governs.
>
> Users are STRONGLY RECOMMENDED to use the `github.com/containeres/image/signature` implementation instead of writing their own, ESPECIALLY when consuming …
> Add JSON schema for the JSON embedded inside signatures

- vendor.conf
The version we use expects Linux-specific `struct stat`; per https://github.com/containers/image/issues/268#issuecomment-301072144 the update fixes this.
> Rebase containers/storage to fix build on macOS

- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
- vendor.conf
This involves some API Changes.
Mainly containers/storage/storage files moved to containers/storage
store.Get* functions dropped the Get to get in compliance with Golang standards.
> Vendor in latest changes for containers/storage

- oci/layout/oci_dest.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
- vendor.conf
According to rc6 spec, the annotation was wrong https://github.com/opencontainers/image-spec/blob/v1.0.0-rc6/annotations.md
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> org.opencontainers.ref.name -> org.opencontainers.image.ref.name

- copy/sign_test.go
- docker/docker_client.go
- docker/docker_client_test.go
- docker/docker_transport_test.go
- types/types.go
This adds `types.SystemContext.DockerPerHostCertDirPath`, defaulting to `/etc/docker/certs.d`, and making it work by default.
Note that this also applies the general TLS defaults to cases when they were previously ignored, notably even when TLS verification is disabled we now restrict the TLS version. That may not be the right thing to do, but if so, we should make an explicit decision about that.
> Support /etc/docker/certs.d

- storage/storage_image.go
`storage` should support manifest list like `docker-daemon` - this is needed in CRI-O
> storage: add support for manifest list

- copy/copy.go
- directory/directory_dest.go
- docker/daemon/daemon_dest.go
- docker/docker_image_dest.go
- docker/tarfile/dest.go
- image/docker_schema2_test.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- ostree/ostree_dest.go
- storage/storage_image.go
- types/types.go
We don't want to pull all layers for an image before realizing it's incompatible with the host OS. An example would be when you try to copy a windows image with skopeo:
```
$ ./skopeo copy docker://microsoft/windowsservercore docker-daemon:testwin:latest
```
The above will pull all layers (more than 3GB) before realizing it's incompatible.
We want to fail early as docker itself does today, so this patch modifies the flow to check for OS compatibility asap (relying on the OCI config):
```
$ sudo ./skopeo copy docker://microsoft/windowsservercore docker-daemon:testwin:latest
FATA[0003] image operating system "windows" cannot be used on "linux"
```
@mtrmac PTAL
needed for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1418173
> copy: fail early when image os doesn't match host os

- README.md
- Add a “command-line usage” heading and section
- Enhance the dependencies subsection
- Move the “when developing this library” sentence into a “Contributing” section
- Add another skopeo pointer to the “building” subsection
- Fix the actual building instructions
- Document the gpgme dependency and how to install it
This should help with #268, and fixes #270.
(Re: #270, this completely removes any mention of `go build ./...` without replacement; as #268 shows, `./...` is undesirable because it includes all depdendencies, and `go build $(PACKAGES)` in `Makefile` is unnecessary because `go test $(PACKAGES)` builds all of the named subpackages, even those which don’t have any tests.)
@hferentschik is this sufficient? (The containers/storage …
> Fix build and usage instructions in README.md

- .travis.Dockerfile
- ostree/ostree_dest.go
- vendor.conf
the main advantage, beside not requiring external processes, is that we
can commit all the layers as an unique transaction.
> ostree: use golang bindings

- transports/transports.go
This interface can be used by callers in their Usage statements, to
guide users to all potential transports.
> Interface to return list of transport names

- README.md
- transports/alltransports/alltransports.go
- transports/alltransports/alltransports_test.go
- transports/alltransports/ostree.go
- transports/alltransports/ostree_stub.go
- transports/stub.go
- transports/stub_test.go
This adds a `containers_image_ostree_stub` build tag to allow making the libostree dependency optional. See the individual commit messages for more details.
@williamh , could you please try applying this PR to the vendored copy of containers/image in skopeo, and then building skopeo with `make binary-local BUILDTAGS=containers_image_ostree_stub` ?
@giuseppe FYI
> Make the libostree dependency optional

- storage/storage_image.go
- vendor.conf
Update the vendored version of github.com/containers/storage to 105f7c77aef0c797429e41552743bf5b03b63263, and pass nil as the new options parameter to the storage/Store.Diff() method.
> Bump github.com/containers/storage

- image/docker_list.go
- image/docker_schema2.go
- image/oci.go
- image/oci_test.go
Add the "Annotations" field to our definition for the OCI manifest type, and give OCI its own descriptor type, so that UpdatedImage() doesn't lose annotations unless it's converting between formats.  Handle
conversions between OCI descriptors and traditional ones.
> Add "Annotations" to OCI manifest and descriptors

- image/docker_schema2.go
- image/oci.go
UpdatedImage() has been dropping the MediaType from layer descriptors when updating OCI v1 and Docker schema 2 images.  When updating them now, give the updated layer descriptors the media types of the original layers.
> Preserve layer media types when updating images

- storage/storage_image.go
- storage/storage_test.go
The storage library, and parts of our storage-related logic, can return errors wrapped by `github.com/pkg/errors.Wrap()` and friends, so when checking for equality to specific errors, use `errors.Cause()` to dig into them.
Tests for duplicate ID detection were broken starting in d41025d60560cf463a215fc951a6ed949523a4bf, which made it acceptable to reuse an image ID if the new image and the old image had the same top layer, so adjust the tests for that error to use different layer contents when creating the second image with the same ID as one that it had just created.
> Fix checks for storage.Errors and tests for them

- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
Expand the syntax of the store's location to allow it to also contain the runRoot location (optional, after the root, separated by '+') and a list of driver options (optional, after the runRoot, separated by ":",
and itself broken up using ",").
> Expand store locations to include runRoot and opts

- docker/docker_client.go
As already done docker-side at
https://github.com/moby/moby/blob/master/vendor/github.com/docker/distribution/registry/client/auth/session.go#L98
@mtrmac PTAL this fixes https://github.com/projectatomic/skopeo/issues/375
> docker: loop auth handlers instead of using just one

- docker/tarfile/src.go
Need it in kpod pull and kpod load. These commands need all the manifests, so took out the length checking block from loadTarManifest.
> Add LoadTarManifest to get the manifest from docker-archive

- docker/tarfile/dest.go
- docker/tarfile/src.go
- docker/tarfile/types.go
Otherwise lint fails on Fedora 24:
> …/docker/tarfile/src.go:192:37: exported method LoadTarManifest returns unexported type []tarfile.manifestItem, which can be annoying to use
(Yes, #309 did pass tests. I don’t know what makes the difference. Anyway, I need the warning to go away to keep my workflow clean.)
This should not affect users of #309 because they were not able to name the type before anyway.
> Make docker/tarfile.manifestItem public

- docker/archive/dest.go
Need this fix for kpod load so that stdout can write to a file when redirected. Checks if the file exists and is empty first as the file is created then written to.
> Add fixes to newImageDestination to allow kpod save to write to a file when stdout is redirected

- vendor.conf
This updates the version of `containers/storage` that we recommend to the current master revision.
> Bump the recommended containers/storage version

- docker/docker_image_src.go
If we are supplied a digested reference, use it instead of possibly fetching the manifest.  This allows using signatures which are not protected even if the manifest is, in some situations.
To ensure consistent behavior, only do this if the reference uses the `digest.Canonical` algorithm, which has been used so far.  This could be perhaps relaxed in the future.
Note that this does not promise that GetSignatures will never need authentication—e.g. for `X-Registry-Supports-Signatures` this already depends on the server, and for the sigstore lookaside authentication
support may be added in the future.
Cc: @mfojtik
> Don’t load the manifest in GetSignatures if the digest is known

- transports/transports.go
This will indicate if the interface should be used any longer.  The
patch removes the transport for the list of transports.
>  Deprecate atomic transport 

- copy/copy.go
- copy/manifest_test.go
- directory/directory_src.go
- directory/directory_test.go
- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/tarfile/src.go
- image/docker_schema2_test.go
- image/memory.go
- image/unparsed.go
- oci/layout/oci_src.go
- openshift/openshift.go
- signature/policy_eval.go
- signature/policy_eval_signedby.go
- signature/policy_reference_match_test.go
- storage/storage_image.go
- storage/storage_test.go
- types/types.go
@mtrmac @runcom since we plan to use the containers/image for downloading signatures from external location, we want to wrap every HTTP request to any location with `context.Context` that allows to set timeouts and deadlines for the request (so we won't open a request to a black hole, etc.)
i don't want to sweep all containers/image code and address all cases for now (but somebody should ;-) just plumb the code we currently need for https://github.com/openshift/origin/pull/15494
@smarterclayton FYI
> allow to use context for getting signatures

- copy/copy.go
- copy/manifest.go
- docker/archive/src.go
- docker/daemon/daemon_dest.go
- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/lookaside.go
- docker/tarfile/dest.go
- image/docker_schema2.go
- openshift/openshift.go
- pkg/compression/compression.go
- signature/policy_eval.go
- signature/policy_eval_baselayer.go
- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_test.go
- storage/storage_transport.go
- vendor.conf
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
> Update and rename the import for logrus v1.0.0

- vendor.conf
Although containers/image uses lowercase sirupsen as a dependency, some
of the referenced vendor shas still use uppercase Sirupsen which causes
build problems on OSX
Signed-off-by: Tiago Scolari <tscolari@pivotal.io>
> Bump dependencies that reference Sirupsen

- docker/docker_client.go
Ignore (but log) all permission errors when trying to get the list of
additionally trusted Docker certificates and keys. This should not
result in any security issues, because additional trusted certificates
are additive (and thus the only issue that can occur is that a transport
is not trusted by skopeo when it should be).
Not ignoring permission errors would cause issues when trying to perform
a copy of a Docker image on a machine that has Docker installed (by
default Docker makes /etc/docker/certs.d not accessible). This would
manifest itself like so:
% ./skopeo copy docker://busybox oci:busybox
FATA[0000] Error initializing source docker://busybox:latest: open /etc/docker/certs.d/docker.io: permission denied
Fixes #297
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> docker: ignore EPERM when scanning for certificates

- Makefile
- docs/registries.conf.5.md
- pkg/sysregistries/system_registries.go
- pkg/sysregistries/system_registries_test.go
- registries.conf
registries.conf is a system-wide configuration file initially
developed in https://github.com/projectatomic/registries.  We
eventually want to ship the configuration file with this project;
hence the addition.  However, we also needed a library like
approach that gave this and other projects the ability to
parse the file in the same manner.
Signed-off-by: baude <bbaude@redhat.com>
> Add registries.conf file and build library to parse it

- oci/layout/oci_dest.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
- transports/alltransports/alltransports_test.go
Fix oci to save the full image name `image:tag` instead of just `tag` in index.json.
Add function to retrieve the image name from index.json when loading or pulling image from oci directory.
> Fix oci to save the full image name in index.json

- oci/archive/oci_dest.go
- oci/archive/oci_src.go
- oci/archive/oci_transport.go
- oci/archive/oci_transport_test.go
- oci/layout/oci_dest.go
- transports/alltransports/alltransports.go
- transports/alltransports/alltransports_test.go
The oci-archive transport uses oci to create a directory of the image, which is then tarred up into a file. oci-archive will be used in kpod save and kpod load for oci images.
> Add oci-archive transport that creates a tar archive of an image

- .travis.Dockerfile
- pkg/sysregistries/system_registries.go
The version of golint in Travis is quietly failing because it doesn't
support multiple packages as variadic args. This removes the version of
golint being fetched from apt in favour of that built by the tools make
target. It also resolves the linting error surfaced from fixing the makefile.
Signed-off-by: Gareth Clay <gclay@pivotal.io>
This is a replacement for the PR #335 which resolved this issue in a different way.
> Resolve linting errors and use recent golint

- docker/docker_client.go
- vendor.conf
Does this look reasonable? It adds a new dependency on docker/container-registry-helpers. I'm happy to rewrite this without that dependency if it seems preferable.
Also happy to add some tests for this if the approach looks correct.
Ref #334
> Add support for credential helpers.

- copy/copy.go
- directory/directory_test.go
- directory/directory_transport.go
- directory/directory_transport_test.go
- docker/archive/transport.go
- docker/archive/transport_test.go
- docker/daemon/daemon_transport.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_transport.go
- docker/docker_transport_test.go
- image/docker_schema2_test.go
- oci/archive/oci_src.go
- oci/archive/oci_transport.go
- oci/archive/oci_transport_test.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
- openshift/openshift.go
- openshift/openshift_transport.go
- ostree/ostree_transport.go
- ostree/ostree_transport_test.go
- signature/policy_eval_signedby_test.go
- signature/policy_eval_simple_test.go
- signature/policy_eval_test.go
- signature/policy_reference_match_test.go
- storage/storage_reference.go
- storage/storage_test.go
- types/types.go
This pull request has a tiny one-line patch to add imgspecv1.MediaTypeImageManifest to the list of MIME types that a docker registry might support (as always, the exact list depends on the version of the registry we are talking to), and a bigger, though still trivial patch that prevents some breakage from the change - as discussed in #331.
(With the obvious compilation fix to skopeo, the skopeo tests all pass with these changes.)
The breakage that is avoided is that for copying from docker to oci, we don't want to pass only the imgspecv1.MediaTypeImageManifest in the Accept header - a) the particular docker registry might not in fact support imgspecv1.MediaTypeImageManifest b) and if it did, the particular manifest being requested might not be a imgspecv1.MediaTypeImageManifest, instead …
> Support pulling/pushing OCI manifests from a docker registry

- pkg/sysregistries/system_registries.go
- pkg/sysregistries/system_registries_test.go
- types/types.go
pkg/sysregistries/system_registries.go: Override system registries path
For the purposes of testing, it is handy to override the default configuration
file location of the system registries configuration file.  This is particularilyi
true in the case of crio-o which consumes this library.
Signed-off-by: baude <bbaude@redhat.com>
> pkg/sysregistries/system_registries.go: Override system registries path

- ostree/ostree_dest.go
- ostree/ostree_transport.go
- ostree/ostree_transport_test.go
a couple of issues I've observed while using `atomic pull` (which now uses Skopeo copy for ostree as well)
> ostree: fix a couple of issues

- manifest/manifest.go
This allows `copy.Image` to work with Docker Hub registries, which now use manifest lists for many images; the downside is breaking non-`copy` uses for any non-default architecture.
> Hotfix: Do not fetch manifest lists from Docker registries

- image/fixtures/oci1-to-schema2.json
- image/fixtures/oci1.json
- image/oci.go
- image/oci_test.go
- oci/archive/oci_dest.go
- signature/signature.go
According to the image spec [1], descriptors should be able to contain
URLs. Support them on the returned BlobInfo for layers.
[1] https://github.com/opencontainers/image-spec/blob/master/descriptor.md
Signed-off-by: Danail Branekov <danail.branekov@sap.com>
> Support URLs on oci layers

- copy/copy.go
Were seeing progress that looks like this:
Copying blob sha256:e190868d63f8f8b85b026e53b5724c3c2a4548e1d642953442559cfa5f79b2c9
62.72 MiB / 62.72 MiB [=======================================================]
Copying blob sha256:909cd34c6fd77d398af1d93e9d4f7f76104903f237be3d4db7b345a19631f291
0 B / 69.81 KiB [-------------------------------------------------------------]
Copying blob sha256:0b9bfabab7c119abe303f22a146ff78be4ab0abdc798b0a0e97e94e80238a7e8
0 B / 682 B [-----------------------------------------------------------------]
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
0 B / 32 B [------------------------------------------------------------------]
Copying blob sha256:00bf65475aba8f1077fa9629f088a5f531d645faeccb6acd7a8626c7d896a4c4
35.96 MiB / …
> Print Skipping comment on new line in progress

- .travis.Dockerfile
We noticed that the travis output can be a bit misleading because it
says that it's running the tests against go 1.9 but the actual version
inside the docker image is 1.7.
Signed-off-by: Danail Branekov <danail.branekov@sap.com>
> Update test image to always use go version 1.8

- docker/docker_image_src.go
This has two impacts:
1. In the case where a request succeeds, break out of the loop so as not to
continue fetching unnecessary blobs.
2. Previously it was possible for a request to fail after succeeding in a
previous iteration, which would error the function, despite a successful
fetch.
Signed-off-by: Tiago Scolari <tscolari@pivotal.io>
> Fix bug in getting external docker blob

- docker/docker_client.go
- docker/docker_client_test.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- oci/archive/oci_dest.go
- pkg/docker/config/config.go
- types/types.go
This package is used in authenticating a user for kpod login
and can be used for authentication in kpod push, pull etc.
> Add authentication package to containers/image/pkg

- image/oci.go
- image/oci_test.go
- types/types.go
According to the image spec [1], descriptors should contain
media types. Support them on the returned BlobInfo for layers.
[1] https://github.com/opencontainers/image-spec/blob/master/descriptor.md
> Support MediaType on OCI Layers

- .gitignore
- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
- oci/layout/oci_transport.go
> Issue #155 Making sure existing OCI index gets not overwritten

- docs/policy.json.md
- tarball/doc.go
- tarball/tarball_reference.go
- tarball/tarball_src.go
- tarball/tarball_transport.go
- transports/alltransports/alltransports.go
Add a "tarball" transport which can be used to import tarballs of root filesystem as images by treating each tarball as a single layer, adding an empty OCI configuration, optionally merging in parts of one that can be passed to an ImageReference, and generating an OCI manifest for it all when creating an Image or ImageSource.
I think this will simplify the implementation of something like "kpod import" in cri-o, so that it doesn't need to manage any of the details of building manifests.  It'll make it possible to use skopeo to convert something like a root cache from mock into an image, give or take the image configuration, and it will make it possible to start buildah using a previously-exported container's contents.
> Add a "tarball" transport for treating discrete tarballs as image layers

- transports/alltransports/storage_stub.go
We never did rename the `containers-storage:` transport (per https://github.com/containers/image/blob/master/storage/storage_transport.go#L70, give or take), but the stub thought that we had.
> Stub out the right transport name for storage

- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
- oci/layout/oci_src.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
- types/types.go
This is a POC/RFC for allowing users to specify an external blob directory for OCI image layout sources and destinations. The OCI image spec stipulates that image layouts [must have a `blobs` subdirectory](https://github.com/opencontainers/image-spec/blame/master/image-layout.md#L19), but that it [may be empty and implementations may fetch blobs from other sources](https://github.com/opencontainers/image-spec/blame/master/image-layout.md#L59))
For our use case, we're forced to use a Docker V2 registry as a canonical store but prefer to use OCI when building and manipulating images locally. So a typical workflow involves a `skopeo copy docker://image oci:image`; `umoci unpack`; `umoci repack`; `skopeo copy oci:image docker://` sequence. Since we have various shared layers we want to …
> OCI: add a sharedBlobDir mode

- CONTRIBUTING.md
See the updated text for the rationale.
This follows up on the discussion in #366. Feel free to tell me this is wrong and reject it.
> Modify CONTRIBUTING.md to prefer smaller commits over squashing them

- copy/copy.go
- copy/manifest.go
- copy/manifest_test.go
- directory/directory_dest.go
- directory/directory_transport.go
- directory/directory_transport_test.go
- types/types.go
Gives the user the option to switch between the oci, v2s1, and v2s2 manifests
Add directory creation if the directory doesn't exist
Add overwrite functionality only if the directory was a container image directory
Feature added for the pulp team
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Add manifest type conversion support for "dir" transport

- image/docker_schema1.go
Since we already know how to convert from Docker V1 to V2 and from
Docker V2 to OCI, we simply do a transitive manifest conversion.
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
> image: implement Docker v1 -> OCI conversion

- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/tarfile/dest.go
- internal/tmpdir/tmpdir.go
- oci/archive/oci_transport.go
- oci/archive/oci_transport_test.go
- oci/internal/oci_util.go
- oci/internal/oci_util_test.go
- oci/layout/oci_dest.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
Signed-off-by: Hardy Ferentschik <hardy@hibernate.org>
> Issue #368 Making OCI and Docker daemon transport work on Windows

- vendor.conf
We no longer need a private branch of containers/storage, so update vendor.conf to use master.
> Revert to containers/storage master

- storage/storage_reference.go
Log the message about a given reference not being resolvable to an image ID at the debug level rather than as an error, and wrap the error that we return in case the caller wants to relay the reference's value back as part of the error.
> storage: log image-not-resolving at debug level, not error

- ostree/ostree_dest.go
Add a SELinux label to each file imported into OSTree.  The label given
to each file is the same it would have if installed on the host.
This has two advantages:
1) we can use in the container the same policies we use for processes on
the host.
2) we share more files in the OSTree repository with the host since
having the same SELinux label most likely will produce the same
checksum.
> ostree: add selinux label for each file

- image/oci.go
This is the inverse of #380 and unfortunately still necessary in order
to be able to use skopeo to push OCI images to a repository like
quay.io.
As in that issue, we simply do a transitive manifest conversion via
the V2 format, which should be lossless.
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
> image: implement OCI -> Docker v1 conversion

- directory/directory_dest.go
Take the execute bit off of the "version" file that we create when writing images to a "directory:" destination.
> directory: make the "version" file non-executable

- docker/docker_image_dest.go
Using `errors.Cause` one can understand what was the cause of the failure. Unfortunately, when the error is returned due to status code different than 203, 200 or 201 `errors.Cause` is a verbose string.
This patch suggests to set the cause of the error to be the staus text.
For example, if failed to upload a layer, instead of having the following:
`Error initiating layer upload to /path/to/upload, status 401`
This error message will be returned:
`Error initiating layer upload to /path/to/upload": Unauthorized`
It's then easier to handle this error by reading `errors.Cause`:
```Go
if errors.Cause(err) == http.StatusText(http.StatusUnauthorized) {
return errors.New("You are not authorized. Missing credentials?")
}
```
This can help me to fix …
> Change errors structure to handle them gracefully

- ostree/ostree_dest.go
This directory is used by system containers to copy files to the host.  We can benefit of maintaining the same label files would have on the host as we are able to use hard links instead of creating new files.
> ostree: handle /exports/hostfs labelling

- .travis.Dockerfile
Primarily because Zesty is EOL and the repositories are no longer available.
The Ubuntu EOL manifests in failures like
```
W: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu zesty-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu zesty-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/zesty-security/universe/source/Sources  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/source/Sources  404  Not Found [IP: 91.189.88.161 …
```
> Update Ubuntu from Zesty to Atful

- .travis.Dockerfile
This
- Updates Golang to 1.9.2
- ~~Takes advantage of the 1.9 semantics of `./...` to simplify `Makefile` a bit.~~
Both are RFCs:
- We could instead update to 1.8.5 from the current 1.8.3.  Per #403, F26 has 1.8 (with about 7 months til EOL), F27 and EPEL have 1.9.
- ~~The latter commit will break, or at least make life difficult for, 1.8 users. Without it, we would be testing on 1.9 but still probably making it possible to use the repo with 1.8.  And honestly the benefit of that commit is extremely weak.~~
~~Do not merge as is, it includes https://github.com/containers/image/pull/403 and should be rebased on top of it.~~
> Golang update

- docker/docker_client.go
- docker/docker_client_test.go
According to the [docker registry spec](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token) when you request a bearer token from a registry, the response JSON could contain an `access_token` or `token` key. Currently `containers/image` only supports the second option and is therefore incompatible with Azure container registries.
Signed-off-by: Tom Godkin <tgodkin@pivotal.io>
Signed-off-by: Ed King <eking@pivotal.io>
Signed-off-by: Will Martin <wmartin@pivotal.io>
> Make token parsing compatible with Docker's Token Authentication Spec

- docker/docker_client.go
podman search searches a registry for a matching image
this adds the functionality to support that
some registries respond to the v2 endpoint while others
only respond to the v1 endpoint.
This checks both endpoints for a result, and if none is given
the user is informed.
> Add functionality to search registries

- docker/docker_client.go
- docker/docker_client_test.go
Adding /etc/containers/certs.d as another default certs directory
The code will first check /etc/containers/certs.d for the certificates
and if not found at this path it will fall back to /etc/docker/certs.dir
Taking over https://github.com/containers/image/pull/388
> Add /etc/containers/certs.d as default certs directory

- image/docker_schema1.go
Chasing #380; DiffIDs are required in the OCI format, but we were
skipping them because of this check. Without this, converting from a V1
image registry source to an OCI layout results in broken images.
> image: fix docker schema v1 -> OCI conversion

- copy/manifest.go
- copy/manifest_test.go
- manifest/manifest_test.go
Without this, images from misguided registries which return `text/plain` for s1 were treated as needing conversion to any MIME-type-restricted destination (and choosing to convert to the destination's preferred type, usually s2).
Now, if the destination accepts s1, we treat `text/plain` equivalently to specifying s1, and do no conversion.
> Normalize source manifest MIME type before determining possible conversions

- copy/copy.go
- copy/manifest_test.go
- directory/directory_src.go
- docker/archive/src.go
- docker/daemon/daemon_src.go
- docker/docker_image_src.go
- image/docker_schema2_test.go
- image/memory.go
- image/sourced.go
- image/unparsed.go
- oci/archive/oci_src.go
- oci/layout/oci_src.go
- openshift/openshift.go
- ostree/ostree_dest.go
- ostree/ostree_src.go
- signature/policy_reference_match_test.go
- storage/storage_image.go
- storage/storage_test.go
- tarball/tarball_src.go
- types/types.go
add implementation for LayerInfosForCopy so we can provide a modified manifest to be used for `copy`
> ostree, src: support copy of compressed layers

- directory/directory_dest.go
- directory/directory_src.go
- directory/directory_transport.go
- directory/directory_transport_test.go
The config file was being saved as digest.tar for the directory transport.
This is misleading as the config file is not a tar archive.
Dropped the .tar extension from all files now, including blobs.
The user can use a tool like file to determine the format of the files in the directory.
Fixes issue https://github.com/projectatomic/buildah/issues/481
> Remove .tar extension from blob and config file names

- transports/alltransports/ostree.go
- transports/alltransports/ostree_stub.go
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> alltransports: ostree is linux only

- docker/archive/src.go
- docker/archive/transport.go
- docker/daemon/daemon_src.go
- docker/tarfile/src.go
The docker-archive transport pulls in images from tar file
but would fail if the tar file was compressed using gzip.
This adds the functionality of detecting whether the file is
compressed, and if it is the contents are copied to a temp
uncompressed file.
This was supported for the docker-daemon transport, so moving
that functionality to tarfile/src.go for both docker-archive
and docker-daemon.
> Support gzip for docker-archive files

- image/docker_schema1.go
- image/docker_schema1_test.go
- image/docker_schema2.go
- image/docker_schema2_test.go
- image/fixtures/schema1-to-schema2-config.json
- image/fixtures/schema1-to-schema2.json
- image/fixtures/schema1.json
- image/manifest.go
- image/memory.go
- image/oci.go
- image/oci_test.go
- image/sourced.go
- image/unparsed.go
- manifest/docker_schema1.go
- manifest/docker_schema2.go
- manifest/oci.go
- storage/storage_image.go
- types/types.go
This is a set of quite independent cleanups and minor bug fixes on top of #305 .  Notably resolves #413, and adds tests for the schema1 code to decrease risk of similar breakage in the future.
See individual commit messages for more details. I’ll be happy to break this up into several PRs if any part needs more discussion than others.
Cc: @nalind 
- Simplify `types.Image.Inspect` call chain
- Make `ImageInspectInfo.Created` optional
- Move `LayerInfosForCopy` from `UnparsedImage` to `Image`/`sourcedImage`
- Populate labels in `manifest.Schema1.Inspect`
- Clean up manifest types
- Return `""` in `computeID` for unknown manifest types
- Instead of a type switch + cast + error, let the type switch do the conversion
- Rename `manifest.Schema1.ToSchema2` to `ToSchema2Config`
- Load a …
> #305 cleanup

- pkg/sysregistries/system_registries.go
- pkg/sysregistries/system_registries_test.go
It is a common pitfall to add a trailing slash when specifying a
registry (e.g., "docker.io/library/" version "docker.io/library").
Remove trailing slashes to normalize the representation of registries.
> sysregistries: remove trailing slash from registries

- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
especially focus on those from `client.HandleErrorResponse`, which may be very unhelpful, e.g. `"unknown: Not Found"`.
In general, make sure the error includes an expanded Docker reference, or a full URL, or a hostname + path.
Examples:
```console
$ ./skopeo-old inspect docker://www.example.com/busybox
FATA[0001] pinging docker registry returned: error pinging repository, response code 404 
$ ./skopeo inspect docker://www.example.com/busybox
FATA[0001] pinging docker registry returned: error pinging registry www.example.com, response code 404
```
```console
$ ./skopeo-old --override-os linux --policy default-policy.json copy docker://busybox:latest docker://busybox:thisisnotpermitted
…
FATA[0005] Error writing manifest: Error uploading manifest to …
```
> Improve docker/* error messages

- pkg/sysregistries/system_registries.go
- pkg/sysregistries/system_registries_test.go
Remove all (instead of one) trailing slashes from any specified
registry string.
Notice: that's a follow-up fix for https://github.com/projectatomic/registries/pull/32#discussion_r175369710
> sysregistries: remove all trailing slashes

- directory/directory_dest.go
- doc.go
- docker/archive/dest.go
- docker/archive/transport.go
- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_transport.go
- docker/tarfile/dest.go
- docker/tarfile/src.go
- oci/archive/oci_dest.go
- oci/archive/oci_transport.go
- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
- oci/layout/oci_src.go
- oci/layout/oci_transport.go
- openshift/openshift.go
- openshift/openshift_transport.go
- ostree/ostree_dest.go
- ostree/ostree_src.go
- ostree/ostree_transport.go
- storage/storage_image.go
- storage/storage_reference.go
- tarball/tarball_src.go
A few trivial clean-ups on top of #431 . Needs to be rebased after #431 is merged.
> context.Context cleanups

- oci/layout/oci_dest.go
Add what the syntax of the oci and oci-archive transport should be if an error
is returned when preparing the destination.
> Add more information to error returned for oci

- vendor.conf
This commit closes #443, however, some of the dependencies listed in the issue were transitive dependencies that were still needed.
I have check that everything still works without these deps running a `make test`, if you require something else please let me know.
> Remove unused dependencies from vendor.conf

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
Introduce sysregistriesv2, which changes the format of the
`registries.conf` TOML configuration.  Instead of having different lists
to specify search registries, blocked and insecure ones, all data is
encapsulated into one registry type.  The registry type allows to
specify a list of mirrors, which can be used in the endpoint lookup to
serve, for instance, as pull through caches for the associated registry.
An example configuration may look as follows:
```toml
[[registry]]
url = "https://registry.com"
prefix = "another-registry.com"
[[registry.mirror]]
url = "http://registry-mirror.com"
insecure = true
```
The upper example shows the configuration for `https://registry.com`.
The prefix is used for matching images, and to translate one namespace
to another.  If `prefix="example.com/bar"`, …
> introduce sysregistriesv2

- docker/daemon/daemon_transport.go
- docker/daemon/daemon_transport_test.go
This is necessary for verification / policy enforcement of in-daemon images. (#288)
It is awkward in that an image may have no name and be usable only by an ID; such IDs could have a policy identity but they can’t really be namespaced.
For now, implement policy configuration scopes only for named image references; ID-only references use the root scope.  This allows users to make ID-only images untrusted or to reject them, forcing users to use image names if they want the policy to approve.  This gives a fairly natural semantics, equivalent to `docker:` policies.  ID-like policy configuration scopes are forbidden.  If truly necessary, we can add support for single-ID policy IDs into the policy in the future, but that’s unlikely to be too useful—IDs change over time, so such a policy would …
> Implement policy configuration scopes in docker-daemon:

- docker/archive/dest.go
- docker/archive/transport.go
- docker/tarfile/dest.go
- types/types.go
Add support to create a docker-archive with more than one RepoTag,
enabling users such as skopeo, to create or copy multitag archives.
Support for other transports can be added in the future.
Fixes: https://github.com/containers/image/issues/447
> docker-archive: multiple tag support

- internal/tmpdir/tmpdir.go
- storage/storage_image.go
This commit exposes a variable `unixTempDirForBigFiles` to allow some
Linux distributions to use `/tmp`.
On NixOS for instance, `/tmp` is not a tmpfs and Nix sandboxed builds
do not allow to write to `/var/tmp`, only to `/tmp`.
Note the `tmpdir.TemporaryDirectoryForBigFiles()` is now also used in
the `storage` package to create temporary directories.
Signed-off-by: Antoine Eiche <lewo@abesis.fr>
> tmpdir: unixTempDirForBigFiles can be overridden at build time

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
To be backwards compatible with the v1 config format, fallback to using
https when no URI scheme is specified (e.g., "docker.io").
> sysregistriesv2: fallback to https for v1 backwards compat

- docker/archive/dest.go
- docker/archive/transport.go
- docker/archive/transport_test.go
- docker/tarfile/dest.go
- oci/layout/oci_dest.go
- oci/layout/oci_transport.go
The docker-archive and oci-archive transport should allow the
destination of the image to be valid without the reference part also.
Format is transport:path[:reference] where reference is optional.
This is for the case where a user just wants to save/push an image with
the image ID only and not the name.
Creates archives with empty repotags.
Fixes one of the issues in https://github.com/projectatomic/libpod/issues/649
> Allow image to be saved without a reference name

- vendor.conf
This is a newly required dependency of containers/storage.
> Add github.com/syndtr/gocapability to vendor.conf

- docker/daemon/client.go
- vendor.conf
Previous docker/docker/* dependency versions replaced with the corresponding versions from the latest checked docker's vendor.conf.
Added containerd/continuity dep since it is required by docker code.
Signed-off-by: Max Goltzsche <max.goltzsche@gmail.com>
> Updated docker dependencies.

- pkg/sysregistries/system_registries.go
We are seeing lots of issues with people taking podman and buildah and just
building them and installing them without greating registries.conf file.
They end up doing
buildah from fedora
or
podman from fedora
And we report that fedora does not exist.
I would like to make podman/buildah smarter so that they could state something like
podman from fedora
fedora does not exist.  
/etc/containers/registries.conf and /etc/containers/registries.d directory are missing.
> Add functions to return Registries paths, tools can use them to help users debug

- ostree/ostree_dest.go
Since https://github.com/ostreedev/ostree/pull/1555, locking is
enabled by default in OSTree.  Unfortunately it uses thread-private
data and it breaks the Golang bindings.  Force the same thread for the
write operations to the OSTree repository.
> ostree: use the same thread for ostree operations

- copy/copy.go
- directory/directory_dest.go
- docker/docker_image_dest.go
- docker/tarfile/dest.go
- image/docker_schema2_test.go
- oci/archive/oci_dest.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- ostree/ostree_dest.go
- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
- types/types.go
This is a follow-up, and on top of, #416.  Unlike that one, which should be overwhelmingly uncontroversial, this one involves a few design choices.
See individual commit messages for more details. (…and not to read #416 again; start at “Make TestStorageReferenceDockerDeference table-driven“.); please pay particular attention to the “RFC” and “UNTESTED” marked ones. I’ll be happy to break this up into several PRs if any part needs more discussion than others.
General themes:
- Increase test coverage of various accepted, and invalid, reference formats
- Fix various uncovered corner cases, e.g. reject `@`_digest_ without a name, or _name_`@`_digest_`@`_digest_`@`_ID_
- Support _name_`:`_tag_`@`_digest_, which is actually a recognized syntax.  (Or would we refuse it instead?)
- Eliminate …
> #305 cleanup 2: Reference handling

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
This PR is based on a discussion at projectatomic/libpod#721 and includes the following changes:
- sysregistriesv2: forbid URI schemes
- sysregistriesv2: improve config validation
> Cleanup sysregsv2

- pkg/sysregistriesv2/system_registries_v2.go
This follows up on #464 to clarify why/how we expect both `url.Parse(input)` and `url.parse("http://"+input)` to succeed.
> Document the subtleties of using url.Parse for validating registry prefixes

- docker/docker_client.go
docker.SearchRegistry was not calling config.GetAuthentication
to get the credentials of a registry from the authfile.
Fixes https://github.com/projectatomic/libpod/issues/976
> Search was not looking for credentials in authfile

- pkg/docker/config/config.go
- pkg/docker/config/config_test.go
Fixes #471 , adds unit tests, and cleans up the constants a bit.
See individual commit messages for more details.
@umohnani8 (@runcom ) PTAL
> Fix the RootForImplicitAbsolutePaths case of getPathToAuth

- transports/alltransports/alltransports.go
- transports/alltransports/alltransports_test.go
- transports/alltransports/docker_daemon.go
- transports/alltransports/docker_daemon_stub.go
Make the docker-daemon transport something that can be stubbed out by supplying the `containers_image_docker_daemon_stub` build tag.  While this is currently useful for letting me bypass a difference between the versions of the docker client package used here and the one used in `openshift/source-to-image`, it could be useful elsewhere.
> Make the docker-daemon transport stubbable

- manifest/docker_schema2.go
Add the StartPeriod field to the manifest.Schema2HealthConfig type.  It was added to the Docker API in 2016, but we picked up our definitions from a version that predated it.
> Add manifest.Schema2HealthConfig.StartPeriod

- Makefile
Right now, `make .gitvalidation` takes 2 minutes on my system, mostly re-validating commits that have been validated many times before. That means slow `make`, and slow CI.
Instead, inspired by `skopeo`'s `hack/make/.validate`, only validate commits not present in the upstream master brach.  This, even with the added network access, takes less than two seconds on short branches.
> Only run git-validation on commits not already present upstream

- docker/docker_image_src.go
We need `"pull"` to be able to read the manifest, and `"delete"` to delete it.
Note that until docker/distribution commit ccb839e0e30c3b6992fb4084dfd6550d0ddd4d1a (Jan 3 2017), the action checked for deleting manifests was `"*"`; this does not add it.
(Also, neither of these actions are documented at https://github.com/docker/distribution/blob/master/docs/spec/auth/scope.md . At least https://github.com/docker/distribution/blob/master/docs/spec/auth/jwt.md says that requesting permissions that the server does not grant should not be an error, so this kind of non-compliance is hopefully safe enough.)
This should not affect OpenShift, where the token is an API token and does not actually include any scopes or permissions; that is also probably why noone has noticed before.
@jwhonce @runcom …
> Fix requested token actions when deleting images

- ostree/ostree_dest.go
This adds error checking on ostree commit, which was previously
missing.
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
> ostree: add missing error check on commit

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
Change the order in which a search happens. Try the v1 endpoint
first without any authentication token and if that fails, get a
token and try the v2 endpoint.
Also add feature to search with an empty query, which only works
with the v2 endpoint. If the query is empty skip the v1 endpoint
and go straight to the v2 endpoint.
This helps fix issues we were seeing when searching quay.io and also
adds the ability to search a whole registry without a specific query
parameter.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Update search for registries

- storage/storage_image.go
If we get a `storage.ErrDuplicateID` error back from `PutLayer()`, assume that some other party has created the layer that we were attempting to create, and continue with committing the image.
> storageImageDestination.Commit(): ignore ErrDuplicateID

- docker/docker_client.go
When logging a debug message about an error that we get back when trying to ping a registry, log the error text, too.
> dockerClient.detectProperties: debug log the error string

- pkg/tlsclientconfig/tlsclientconfig.go
- pkg/tlsclientconfig/tlsclientconfig_test.go
When we encounter an IsNotExist error when reading root CA certificates as part of setting up a TLS client, log the error but continue.  Continue to bail if we encounter errors loading client credentials.  This should resolve https://github.com/containers/buildah/issues/1065.
> Ignore but log an error on IsNotExist errors reading root CAs

- pkg/docker/config/config.go
Non-`IsNotExist` errors are currently ignored, causing misleading failures like
```
error unmarshaling JSON at "/run/containers/1000/auth.json": unexpected end of JSON input
```
Fix that.
> Don’t ignore errors reading pkg/docker/config config files

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- openshift/openshift.go
e.g. `504 (Gateway timeout)` instead of just `504`.
Note that for unknown status codes this will output `99999 ()`; this seems not worth worrying about and building a helper for right now.
(Also fixes one instance of using `%q` for integer parameters, which results in gibberish.)
> Include http.StatusText with every HTTP status code in errors

- docker/docker_client.go
For me, this seems to work and only results in a weird
```
Ping https://registry-1.docker.io/v1/_ping err <nil>
```
(with the last `(%#v)` element completely lost;
OTOH https://github.com/containers/buildah/issues/1079 reports a crash most likely attributable to this.
> In debug logs of Docker v1 ping, only call err.Error() if err != nil

- Makefile
Fix the following error in CI:
```
package github.com/golang/lint/golint: code in directory /gopath/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Makefile:48: recipe for target 'tools.timestamp' failed
make: *** [tools.timestamp] Error 1
```
Signed-off-by: Antonio Murdaca <runcom@linux.com>
> Makefile: fix golint

- README.md
- libostree-devel is now ostree-devel
- make test-skopeo requires device-mapper-devel and btrfs-progs-devel
> README.md: Update fedora package requirements

- manifest/docker_schema1.go
- oci/archive/oci_dest.go
- oci/archive/oci_src.go
- openshift/openshift.go
- storage/storage_transport.go
There have been multiple build failures found when running `go test` through the git repo. Fix them to avoid test failures.
Signed-off-by: Dongsu Park <dongsu@kinvolk.io>
> Fix build failures regarding error functions

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
While working on https://github.com/containers/buildah/pull/909 I have noticed that that the order of entries returned by `FindUnqualifiedSearchRegistries` is randomized; this should fix it.
Cc @vrothberg
> Fix search order returned by sysregistriesv2 for v1 config files

- vendor.conf
c/storage now depends on https://github.com/opencontainers/selinux/pull/36/files .
> Update the version of github.com/opencontainers/selinux used for tests

- doc.go
The example code in godoc were formatted inconsistently due to
indentations issues. This fixes the indentations, moving the example
into proper code block.
Signed-off-by: Sunny <me@darkowlzz.space>
> Fix godoc code formatting

- docker/docker_client.go
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- types/types.go
Based on a discussion from: https://github.com/containers/image/pull/464#issuecomment-397744605
- sysregistriesv2: adjust API to SystemContext
- dockerClient: skip TLS verification if configured in registries
> dockerClient: skip TLS verification if configured in registries

- vendor.conf
Vendor the latest ostree commit 56f3a639dbc0f2f5051c6d52dade28a882ba78ce
to fix build warnings poluting the output.
> vendor latest ostree

- .travis.yml
- copy/copy.go
- ostree/ostree_dest.go
- ostree/ostree_src.go
- pkg/compression/compression.go
- tarball/tarball_src.go
- vendor.conf
from my tests, I've seen a net improvement of around 30% on the wall
clock time in decompressing layers.
> vendor: use github.com/klauspost/pgzip instead of compress/gzip

- copy/copy.go
- directory/directory_dest.go
- directory/directory_src.go
- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/tarfile/dest.go
- docker/tarfile/src.go
- image/docker_schema2_test.go
- oci/archive/oci_dest.go
- oci/archive/oci_src.go
- oci/layout/oci_dest.go
- oci/layout/oci_src.go
- openshift/openshift.go
- ostree/ostree_dest.go
- ostree/ostree_src.go
- storage/storage_image.go
- tarball/tarball_src.go
- types/types.go
- vendor.conf
```
$ podman pull docker.io/nginx:latest
Trying to pull docker.io/nginx:latest...Getting image source signatures
Copying blob a5a6f2f73cd8: 21.44 MiB / 21.44 MiB [==========================] 8s
Copying blob 1ba02017c4b2: 21.18 MiB / 21.18 MiB [==========================] 8s
Copying blob 33b176c904de: 203 B / 203 B [==================================] 8s
Copying config 568c4670fa80: 5.88 KiB / 5.88 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
568c4670fa800978e08e4a51132b995a54f8d5ae83ca133ef5546d092b864acf
```
Tests on my notebook show improvements between **6 and 16 percent** when pulling an image (tested with a remote and a local registry and varying sizes and amounts of layers).
> parallel copying

- copy/copy.go
Set the output of the progress bars and the progress pool, respectively,
to the specified io.Writer passed through the copy options.  Otherwise,
the output will be printed to Stdout breaking users which are parsing
the output and expect the progress bars to be printed on Stderr.
> copy.Copy: progressbars: set correct output

- docker/docker_image_dest.go
Mark dockerImageDestination to not be thread safe as there is a race
condition in dockerClient.extraScope causing copy.Copy() to error out
with `[...]dockerClient.extraScope was set before TryReusingBlob`,
which must be addressed in future changes.
> dockerImageDestination: HasThreadSafePutBlob -> false

- copy/copy.go
If the reportWriter is not a tty then print a single line for copy
operations and discard the output of the progress poll and the
progress bars.  This avoid long and hard to parse output when not
using a tty, for instance, when piping the output to a file.
> copy: print singles lines when reportWriter is not a tty

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
* make dockerImageDestination's `PutBlob` "thread safe" by moving the `extraScope` member into parameters
* tested locally
> Parallel push

- copy/copy.go
- docker/docker_client.go
This merge request removes unnecessary newlines from the logging output.
> Remove newlines from logging

- docker/tarfile/src.go
This fixes #567, and *should* be safe from what I can tell (according to the
reasoning I mention in that issue).
> Make docker/tarfile's GetBlob thread-safe

- pkg/sysregistriesv2/system_registries_v2.go
Need the v1 registries structs to be public so that I can
use it in the CRD and controller stuff for container runtime
config in the machine-config-operator repo.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> sysregistriesv2: Export registries struct for v1 format

- ostree/ostree_src.go
The `bytes.Reader` that we use to read the decompressed copy of the tar split data in `ostreeImageSource.GetBlob()` was being closed when we returned using `defer`, at which time the goroutine that was feeding the `io.ReadCloser` that we returned could still be running.  Move its `Close()` call so that it's closed along with the `io.ReadCloser` that we return.
> ostreeImageSource.GetBlob(): close mfz when we're done with it

- ostree/ostree_src.go
The pipe was used before commit c809f3dc87c2a04086d766b72e9f8d15cd10b181 to integrate a `gzip.NewWriter`; now it is not necessary, so drop it.
> Remove an unnecessary pipe in ostreeImageSource.GetBlob

- docker/docker_image_src.go
makeRequestToResolvedURL() can return {nil, err} for all
given urls. In that case, resp.Body can cause SIGSEGV
because resp is nil.
Signed-off-by: Arjun Sreedharan <arjun024@gmail.com>
> docker-image-src/getExternalBlob: handle nil resp

- docker/docker_image_dest.go
Uploading a spec-compliant OCI manifest which contains no top-level media type fails on AWS ECR with an Unsupported error code and  an 'Invalid JSON syntax' error message.
As suggested in containers/libpod#1719 catch this case as an invalid manifest error so that we automatically fallback to other accepted media types in copyOneImage().
> Fallback to v2s2 if OCI manifest upload fails on ECR

- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_transport.go
Now that containers/storage can handle storing multiple manifests for a single image record, name manifests that we save to an image using their digests, repurposing the original name that we used for the manifest (when it only supported holding one) to hold a copy of the most-recently saved one.  This is done by directly incorporating the patch from #582.
When we're asked for a specific manifest by including its digest in an image reference, look for the manifest that matches that digest and set the returned Image's Digest field to a matching value.  Otherwise, try to return the most-recently-saved manifest's digest in the field.
> Storage multiple manifests

- copy/copy.go
- vendor.conf
Use the github.com/vbauerster/mpb library for displaying the progress
bars.  It is actively maintained, is designed for multi-bar usage and
just gets the job done.
This will fix issues with single bars being displayed multiple times.
Note that updating the bar's prefix does not work anymore.  We're now
logging those entries, for instance, when we skip a blob as it's
already present.
The output now looks as follows (e.g., when pulling jboss/wildfly):
```
Copying blob aeb7866da422 [======================================] 71.2 MiB / 71.2 MiB
Copying blob 157601a0b538 [======================================] 10.3 MiB / 10.3 MiB
Copying blob 642f4164f381 [======================================] 1.9 KiB / 1.9 KiB
Copying blob bda512e97517 …
```
> progress bars: use github.com/vbauerster/mpb

- copy/copy.go
Primarily, this fixes the `.Wait` call in `copyUpdatedConfigAndManifest`, terminating the pool before all its possible uses, by using several shorter-lived pools.  Also ensures that the pools are always cleaned up, and other small cleanups.
See the individual commit descriptions for details.
@vrothberg PTAL.
> Fix progress bar cleanup, and other small cleanups

- storage/storage_image.go
containers/storage dropped its dependency on containers/image but
requires to pass a `Digest()` function as a callback.
Pass `manifest.Digest` to make the two libraries compatible again.
> pass `manifest.Digest` to `storage.store.SetImageBigData`

- README.md
These are from f4d6188f (#474).  I dunno if they were intentional or not, but I thought they might be footnote markers so I scrolled down to the bottom of the README looking for a footnote.  Remove them to save other people from that same confusion ;).
> README: Drop '**' from "Contributing" header

- docker/docker_client.go
There have been redundant calls here since two `ref.ref.Hostname()` calls were added in aaedc642 (#52).  At that point the two calls were separated by a `dockerHostname` check which could have been shifted by two lines to avoid the doubled function calls.  But in f28367e1 (#333) the `dockerHostname` check moved to a separate function entirely (`newDockerClientWithDetails`) while the `Domain()` calls remained together in `newDockerClientFromRef`.  So now there is no longer any reason for the second call, and this pull request drops it.
> docker/docker_client: Drop redundant Domain(ref.ref) call

- storage/storage_transport.go
- vendor.conf
DefaultStorageOptions now is a function and takes a rootless argument
and the UID of root within the container.
> Vendor in latest containers/storage

- pkg/blobinfocache/default.go
for tools in containers/ we are using the env variable
_CONTAINERS_ROOTLESS_UID when running in a user namespace to refer to
the rootless UID that created the user namespace.
Closes: https://github.com/containers/libpod/issues/2510#issuecomment-480066763
> blobinfocache: correctly detect the UID in a namespace

- storage/storage_transport.go
- vendor.conf
correctly detect the UID when running in rootless mode.
> storage: fix UID detection in a namespace

- pkg/docker/config/config.go
And refactor it to use `GetAuthentication`, which is just as convenient for callers.  This also removes the lookup differences between lookup logic between the two functions (e.g. `GetUserLoggedIn` used to ignore `DockerAuthConfig`).
Spun off from #588 [here][1] and #596.
[1]: https://github.com/containers/image/commit/480020500db2b2ca5ab850c6657a5df4d0b98904#diff-45d77e7dc3a84219aeb2aaad81b6bf96R298
> pkg/docker/config: Deprecate GetUserLoggedIn

- pkg/blobinfocache/boltdb/boltdb.go
- vendor.conf
github.com/boltdb/bolt is no longer maintained.
Fixes: #560
> Switch to github.com/etcd-io/bbolt

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_src.go
- docker/docker_transport.go
- docs/containers-registries.conf.5.md
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- registries.conf
This change relates to #559 and enables registry mirror support for the docker client.
* The first working mirror will be used for the pull
* The main registry will be the fallback if no mirror works
* The `Insecure` flags will be used from system context and now from the corresponding registry / mirror as fallback too
* Configuring a prefix will be considered (see test cases)
The following test cases has been verified by manual testing via cri-o:
<details><summary><strong>It should succeed to pull an image from a working registry mirror</strong></summary>
<p>
*Given*
`/etc/containers/registry.conf`
```toml
[[registry]]
url = "gcr.local"
mirror = [
{ url = "wrong.local" },
{ url = "gcr.io" },
]
```
*When*
```fish
> sudo crictl pull gcr.local/google-containers/hyperkube:v1.13.2
```
*Then* …
> Add registry mirror support to docker client

- pkg/docker/config/config_test.go
- pkg/docker/config/testdata/abnormal.json
- pkg/docker/config/testdata/example.json
- pkg/docker/config/testdata/full.json
- pkg/docker/config/testdata/legacy.json
We're primarily interested in maintaing compatibility with user's on-disk configurations, and using fixtures makes it harder to get that wrong.
While I'm touching these tests, also use `t.Run` and `assert.Equal` to make it easier to read both the source and any test failure messages.
> pkg/docker/config/testdata: Add credential-file fixtures

- Makefile
The execution of 'trash' in the 'vendor' target of the 'Makefile'
assumes that GOBIN is part of PATH and therefore 'trash' can be called
directly. This commit enables executing 'trash' if neither GOBIN nor
GOPATH/bin are in PATH.
Closes #620
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>
> Makefile: don't assume that GOBIN in PATH

- docs/containers-signature.5.md
We no longer use the term atomic, renaming atomic to containers.
> Rename atomic-signatures to containers-signatures

- types/types.go
Add comment for DockerAuthConfig. In SystemContext, the fileds value of DockerAuthConfig can be empty.
Related PR [#646](https://github.com/containers/skopeo/pull/646)
> Add comment DockerAuthConfig

- .travis.Dockerfile
Use the latest stable version of Ubuntu, since Ubuntu 17.10 (i.e.,
ArtfulAardvark) hit EOL.
Fixes: https://github.com/containers/skopeo/issues/648
> .travis.Dockerfile: use ubuntu:18.04

- docker/docker_image_src.go
This was brought up sometime during the reviews, but was apparently lost.
Consider `registries.conf`:
```
[[registry]]
location = "example.com"
mirror = [
{ location = "docker.io" },
{ location = "registry.access.redhat.com" },
{ location = "registry.redhat.io" },
{ location = "registry.fedoraproject.org" },
]
```
Then
```
skopeo --registries-conf registries.conf copy --src-creds foo:bar docker://example.com/foo/bar dir:t
```
currently sends the `foo:bar` to every mirror that requires authentication, not just to `example.com`; that seems clearly undesirable.
So, clear `SystemContext.DockerAuthConfig` when using a mirror at a different registry than the one specified by the user; if the mirrors require credentials, they have to be set up in the auth file, e.g. by `podman login`.
@vrothberg …
> Reset SystemContext.DockerAuthConfig when using mirrors at different registries

- pkg/docker/config/config_test.go
In 1c0fb51d9b (#593), I changed the test data for this test from:
```go
makeTestAuthConfig(testAuthConfigDataMap{
"docker.io":      testAuthConfigData{"user", "pw"},
"localhost:5000": testAuthConfigData{"joe", "pass"},
})
```
to the `full.json` fixture which includes:
```json
{
"auths": {
"example.org": {
"auth": "ZXhhbXBsZTpvcmc="
},
"index.docker.io": {
"auth": "aW5kZXg6ZG9ja2VyLmlv"
},
"docker.io": {
"auth": "ZG9ja2VyOmlv"
},
...
}
}
```
That lead ordering instability matching the normalized `docker.io`, with it occasionally matching the expected `docker.io` entry, and occasionally matching the `index.docker.io` entry.  With this commit, I'm adjusting the hostname to be based on `example.org` to avoid such ambiguity in target matching while still excercising all the normalization logic …
> pkg/docker/config/config_test: Stabilize "normalize registry" test

- transports/alltransports/alltransports.go
- transports/alltransports/alltransports_test.go
This change adds a new transports.TransportFromImageName procedure
to get the transport's name of an image without parsing the store
reference.
> Add TransportFromImageName procedure

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/blocked-conflicts.conf
- pkg/sysregistriesv2/testdata/find-registry.conf
- pkg/sysregistriesv2/testdata/insecure-conflicts.conf
- pkg/sysregistriesv2/testdata/invalidate-cache.conf
- pkg/sysregistriesv2/testdata/mirrors.conf
- pkg/sysregistriesv2/testdata/missing-mirror-location.conf
- pkg/sysregistriesv2/testdata/missing-registry-location.conf
- pkg/sysregistriesv2/testdata/mixing-v1-v2.conf
- pkg/sysregistriesv2/testdata/unmarshal.conf
- pkg/sysregistriesv2/testdata/unqualified-search.conf
- pkg/sysregistriesv2/testdata/v1-compatibility.conf
This is a hopefully-noncontroversial subset of #633: Modify `sysregistriesv2` tests to use ordinary files instead of hooking into the internals of the config parsers.
> Sysregistriesv2 test fixtures

- docker/reference/README.md
- docker/reference/normalize.go
- docker/reference/normalize_test.go
- docker/reference/reference.go
- docker/reference/regexp.go
- docker/reference/regexp_test.go
- docs/containers-registries.conf.5.md
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/invalid-prefix.conf
- pkg/sysregistriesv2/testdata/invalid-search.conf
- pkg/sysregistriesv2/testdata/missing-mirror-location.conf
- pkg/sysregistriesv2/testdata/missing-registry-location.conf
- pkg/sysregistriesv2/testdata/mixing-v1-v2.conf
- pkg/sysregistriesv2/testdata/unqualified-search.conf
- pkg/sysregistriesv2/testdata/v1-compatibility.conf
- pkg/sysregistriesv2/testdata/v1-invalid-block.conf
- pkg/sysregistriesv2/testdata/v1-invalid-insecure.conf
- pkg/sysregistriesv2/testdata/v1-invalid-search.conf
- registries.conf
This primarily modifies the v2 format to use a top-level `unqualified-search-registries` array instead of an `unqualified-search` boolean in each of the per-prefix (which is not per-registry) entry.
In addition:
- `V1RegistriesConf` and `V2RegistriesConf` are now explicitly public types, with a `Nonempty` method
- There is a public `V1RegistriesConf.ConvertToV2`, to allow callers to _persistently_ upgrade a v1 config (e.g. to add a v2-only property to it, notably the mirror configuration).
<s>Do not merge as is: This currently includes #636.</s>
> Registries v2 explicit search

- docker/docker_image_src.go
- docs/containers-registries.conf.5.md
- registries.conf
This follows up on #564 ; see the individual commit messages for details, I can drop any part you don’t like.
Notable parts:
- This drops most of the big comment before `newImageSource`. @vrothberg you asked for that documentation, or more documentation; is this OK with you?
- The documentation has been rewritten to hopefully make more sense to a first-time reader (notably it starts with the “prefix” value and how it is used to find the relevant entry), but I’m still not really happy with how it turned out. Maybe we should use a bulleted/definition list. Or maybe it’s because I’m not all that familiar with TOML and I struggle with the terminology. Either way, comments and suggestions (including “drop that, the original was better”) are very welcome.
Cc: @vrothberg @saschagrunert
> Mirror documentation changes

- version/version.go
This is a major version bump because the API changes; while we will try to minimize API changes in the future, past experience shows that it is still extremely likely that they will be very frequent, unless the API is significantly restructured and/or large parts of it hidden or declared out of bounds.  Expect the major number to increase several times before this can settle.
> Release 2.0

- ostree/ostree_dest.go
when lsetfilecon_raw fails we also print the context it tried to
set.
> ostree: improve error message

- docker/docker_image_src.go
Fixes: containers/skopeo/issues/667
> docker: allow deleting OCI images

- docker/tarfile/src.go
- Move single-method members into the right section
- Use a separate helper which returns err as usual, to centralize the `cacheDataResult` usage and make sure future updates don’t have to deal with less unusual error reporting mechanism.
The second commit is RFC — I do think centralizing the `cacheDataResult` use is worth it, but I’m less certain about making the inner function public, even with a `…Private` name. It could instead be created as a variable inside `ensureCachedDataIsPresent` (`actualImplementation := func() error { … }` or so).
> Clean up docker/tarfile a bit

- pkg/sysregistriesv2/system_registries_v2.go
This tidies up the TOML generated by marshaling a `sysregistriesv2.V2RegistriesConf`:
- by skipping fields with the default value
- by making sure that the lookup key (`prefix`/`location`) is the first entry in a `registry`
> Beautify registries.conf TOML

- docker/docker_image_src.go
Accept the types listed in `manifest.DefaultRequestedManifestMIMETypes`.
> docker: delete: support all MIME types

- docker/docker_image_src.go
Primarily removes a no-longer-accurate comment; also uses a literal to hopefully be a bit more readable.
> Trivial c/image/docker cleanups

- image/docker_schema1_test.go
- image/docker_schema2_test.go
- image/oci_test.go
- manifest/docker_schema1.go
- manifest/docker_schema2.go
- manifest/oci.go
- types/types.go
Adds the "Env" field in the image schema. Allow the library user
gets the "Env" value available in the image JSON data. Close #248
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>
> Add "Env" to ImageInspectInfo

- Makefile
- README.md
- ostree/ostree_dest.go
- ostree/ostree_src.go
- ostree/ostree_transport.go
- ostree/ostree_transport_test.go
- transports/alltransports/ostree.go
- transports/alltransports/ostree_stub.go
Since only Skopeo uses the OStree transport for fetching images from
OStree repositories, making default no support for OStree. It
simplifies building on other components like libpod and buildah.
This PR is completely different approach to address #432 motivated by [this](https://github.com/containers/image/pull/562#issuecomment-458071484) and [this](https://github.com/containers/image/pull/562#issuecomment-458177678) comments of @giuseppe 
It will require changes in Skopeo, Buildah, CRI-O and libpod to have support for the c/image OStree backend only for Skopeo.
Closes #432.
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>
> ostree: default is no OStree support

- copy/copy.go
- vendor.conf
Schema1 manifests don't include blob sizes causing the BlobInfo sizes to
be -1 and ultimately preventing the progress bars from displaying
meaningful data.  Use a spinner for such cases.  The spinner renders a
sequence of dots (".", "..", "...", "....", "").
> progress bar: use spinners for -1 blob sizes

- version/version.go
The main motivation is to propagate the latest progress-bar fixes (i.e., using spinners for unknown blob sizes) and to ultimately close https://bugzilla.redhat.com/show_bug.cgi?id=1695236 once it's in Fedora.
@mtrmac @rhatdan PTAL
> Release v2.0.1

- pkg/docker/config/config.go
- pkg/docker/config/config_linux.go
- pkg/docker/config/config_unsupported.go
- pkg/keyctl/key.go
- pkg/keyctl/keyring.go
- pkg/keyctl/keyring_test.go
- pkg/keyctl/perm.go
- pkg/keyctl/sys_linux.go
- pkg/keyctl/sys_linux_386.go
- pkg/keyctl/sys_linux_amd64.go
Add package from https://github.com/jsipprell/keyctl to store authentication for `podman login` to kernel user keyring.
close [#2167](https://github.com/containers/libpod/issues/2167)
> Add keyring package

- docs/containers-signature.5.md
- signature/policy_types.go
- transports/alltransports/alltransports.go
Catching up with be91505 (docs: rename manpages to *.5.md, 2019-03-01, #594).
Generated with:
$ sed -i 's/policy.json.md/containers-policy.json.5.md/g' $(git grep -l policy.json.md)
Looking to carry this over the finish line for Wking.
Replaces: https://github.com/containers/image/pull/638
> *: Fix policy.json.md -> containers-policy.json.5.md references

- docker/docker_client.go
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
Return an error whenever we attempt to create a docker client when the
underlying registry is configured to be blocked in the registries.conf.
Until now, users of the c/image library implemented this behaviour but
it has not been enforced.
Now, it's time to pull the trigger and enforce the configuration.
---
Entirely untested. Just want to throw it at Skopeo and continue working on it later.
> docker client: error if registry is blocked

- docker/docker_client.go
Fixes #654.
Alternative to #655.
> Use the same HTTP client for contacting the bearer token server and the registry

- .travis.Dockerfile
- .travis.yml
The `$GOCACHE` seems not writeable by the user executing the tests
inside the docker container. This PR should fix this and unblock the CI
pipeline. To make skopeo build with go modules we have to rely on the
latest dot release of go 1.11.
> ci: change `$GOCACHE` to a writeable path

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/try-update-cache-invalid.conf
- pkg/sysregistriesv2/testdata/try-update-cache-valid.conf
The function can be used to reload the registries without harming the
cache on failure. On success, the cache will be updated as intended.
This function can be reused by the current `GetRegistries` API.
> Add API function `TryUpdatingCache`

- pkg/keyctl/key.go
- pkg/keyctl/keyring.go
- pkg/keyctl/perm.go
- pkg/keyctl/sys_linux.go
This addresses my review comments from #675.
> Follow-up to #675

- copy/copy.go
`DestinationCtx` can conventionally be nil, so add some checks around
references to avoid potential nil dereferences.
> copy: add nil checks

- internal/testing/explicitfilepath-tmpdir/tmpdir.go
Handle cases where $TMPDIR isn't set by reading it by calling `os.TempDir()` instead of reading the environment variable directly.  This allows tests to pass for `directory` when $TMPDIR is not set.
> internal/testing/explicitfilepath-tmpdir: handle unset TMPDIR

- copy/copy.go
Fix the nil check for options.DestinationCtx which
has been inverted mistakenly.
> copy: fix options.DestinationCtx nil check

- pkg/keyctl/keyring_test.go
A number of the `pkg/keyctl` tests link keys to keyrings, but weren't unlinking them at the end of the test, causing subsequent runs of the same test to fail.
> keyctl: clean up after tests

- docker/docker_client.go
fix https://github.com/containers/libpod/issues/3884
Add http response message log to show server-side error message.
> add http response to log

- go.mod
- go.sum
* Update generated files
* ImageBigData: distinguish between no-such-image and no-such-item
* ImageSize: don't get tripped up by images with no layers
* tarlogger: disable raw accouting
> update c/storage to v1.13.4

- go.mod
- go.sum
- manifest/manifest.go
- manifest/manifest_test.go
<s>**Do not merge:** Includes unmerged #714.</s>
... instead of using the `replace` directive in `go.mod`, which changes absolutely nothing for consumers of this library.
Cleans up after #701.
(`docker/libtrust` remains listed in `go.mod` because it is a dependency of the `docker/distribution` _module_; it’s not used by the `docker/distribution` _subpackages_ we call. See https://github.com/golang/go/wiki/Modules#why-does-go-mod-tidy-record-indirect-and-test-dependencies-in-my-gomod .)
> Explicitly replace docker/libtrust with containers/libtrust

- pkg/compression/compression.go
- pkg/compression/internal/types.go
- pkg/compression/types/types.go
- types/types.go
<s>**Don’t merge:** Includes all of #714.</s>
Fixes #659, see the commit message as for how.
@vrothberg @giuseppe RFC. This is a bit baroque, but it is a local thing that does not require any discussion about how to redesign the interfaces in some other way; AFAICT all existing public indentifiers continue to work with the existing semantics.
We can redesign pkg/compression in some other way in some future major version, if there is ever a good enough reason, and we obviously can completely tear down what this PR does at that time.
> Don’t drag in compression implementations into c/image/types

- manifest/manifest.go
Don't require OCI image manifests to have layers in order for us to be able to recognize that we're looking at an OCI image manifest.
This should help with https://github.com/containers/libpod/pull/4165.
> GuessMIMEType: recognize OCI images with no layers

- version/version.go
This has to be done right now because `go get github.com/containers/image/v4@master` refuses to work with the v4.0.0 tag not being a proper /v4 module, even if the declaration is correct in the referred commit.
We can’t test that this will be accepted in consumers without actually creating the tag, so, that’s what I’ll do.
> Release 4.0.1

- Makefile
The current `go mod edit c/image=...` did not affect the actually used version at all.
> Use the correct module path in (make test-skopeo)

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/errors.go
Consolidate checking the http-status codes to allow for a more uniform
error handling.  Also treat code 429 (too many requests) as a known
error instead of an invalid status code.
When hitting 429, perform an exponential back off starting a 2 seconds
for at most 5 iterations.
> docker: handle http 429 status codes

- copy/copy.go
Go back to selecting which image instance we copy in CopySystemImage mode using the source context rather than the destination context, as we did before #400.  Using the destination context made more sense to me, but it's probably worth breaking that out that as a separate decision.
> copy.Image(): select the CopySystemImage image using the source context

- docker/docker_client.go
- docker/errors.go
follow https://github.com/containers/image/pull/709
return and wrap http response message to show server-side error message.
> return resp error message

- copy/copy.go
- copy/progress_reader.go
- copy/progress_reader_test.go
- types/types.go
The progress reader will be now created via the new `newProgressReader`
function. This way we have the possibility to trigger a new event called
`ProgressEventNewArtifact` and `ProgressEventDone` to indicate the
boundaries of the artifact download to the API consumer. During the
download, we additionally provide the `OffsetUpdate`, which can be used
to report the downloaded data during the last elapsed time interval.
Unit tests have been added as well to the progress reader, whereas the
documentation for the new types has been enhanced as well.
Needed for metrics improvements for CRI-O: https://github.com/cri-o/cri-o/pull/2912
> Improve progress reader to report start/end and offset update

- docker/archive/dest.go
- docker/archive/src.go
- docker/archive/transport.go
- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/tarfile/dest.go
- docker/tarfile/src.go
- internal/tmpdir/tmpdir.go
- oci/archive/oci_dest.go
- oci/archive/oci_src.go
- oci/archive/oci_transport.go
- storage/storage_image.go
- storage/storage_reference.go
- types/types.go
Fixed #495 
Added possibility to overwrite default tmp dir for big files.
The problem in this PR is in that fact that not in all usage places it is possible to use SystemContext.
Signed-off-by: bpopovschi <zyqsempai@mail.ru>
> Added possibility to overwrite default tmp dir for big files

- .travis.yml
See https://github.com/containers/image/pull/744#issuecomment-557291005 below.
> Update the Ubuntu host to get newer kernel

- copy/copy.go
- directory/directory_dest.go
- docker/daemon/daemon_dest.go
- docker/docker_image_dest.go
- docker/tarfile/dest.go
- oci/archive/oci_dest.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- ostree/ostree_dest.go
- storage/storage_image.go
- types/types.go
When pulling images for consumption by the current runtime, reject images that target a different architecture: https://bugzilla.redhat.com/show_bug.cgi?id=1753019 .
WIP:
- Absolutely untested, beyond that it compiles.
- I have no idea how this interacts with manifest lists yet.
- We might want to look for images that would be broken by this (is it possible to run i386 images on x86_64?)
- This should ideally be tested directly in CRI-O to ensure it behaves reasonably, and the error is propagated all the way up to the pod status.
- I’d really love to hear opinions on the semantics change of `MustMatchRuntimeOS`.
> Untested: Enforce runtime architecture

- copy/copy.go
The new-initialization of the `io.Reader` `destStream` caused to break
the progress reader calling `Read` at all, which is now fixed.
> Fix destination stream overwrite on progress

- storage/storage_test.go
Revert a previous change that removed the checks for storage interfaces
as golangci-lint complained about them.  Those checks are still desired
to catch errors early in case storage doesn't implement those
interfaces.  Silence golangci-lint by explicitly ingoring any lint
report for these specific lines.
> storage_test.go: check storage interfaces

- .cirrus.yml
- .golangci.yml
- .travis.yml
- Makefile
- internal/pkg/keyctl/keyring.go
- internal/pkg/keyctl/keyring_test.go
Split the installation of required tools into dedicated .install.$tool 
targets and only install them if they're absent.  Remove the sudo call 
when installing golangci-lint by properly setting GOBIN.               
> Make: split out installing tools

- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_src.go
- docker/errors.go
@vrothberg RFC.
This is a set of small updates to #703 .  The support for `context.Context` timeouts is the only really important part; other than that, there are a few adjustments to user-visible output, and other than that mostly user-invisible tinkering, and I’d be perfectly happy to drop or change any of them.
> Retry logic cleanups

- docker/docker_image_dest.go
- types/types.go
This commit adds DockerDisableDestSchema1MIMETypes to types.Context
which, if set to true, will omit DockerV2Schema1SignedMediaType and
DockerV2Schema1MediaType from
dockerImageDestination.SupportedManifestMIMETypes.
Signed-off-by: Scott Seago <sseago@redhat.com>
> Allow for disabling schema1 MIME types for docker destinations

- docker/docker_image_src.go
- go.mod
Primarily, ensure that errors reported by `docker.newImageSource` (i.e. most errors trying to access registries) also contain failures when accessing _all_ mirrors, not just the last error = the error accessing the primary endpoint.
The resulting error is extremely ugly (see below) but hopefully informative, and we can tinker with that later after this is not as urgent (in two ways: by dropping some context and shortening the error in common failure cases, and by by heuristically prioritizing some of the errors vs. others, e.g. a TLS / user authentication failure for a mirror is more likely to be relevant than a DNS not found for the primary).
In addition:
- Some errors (notably an endpoint being configured as blocked) are now not immediately fatal, the other endpoints continue to be …
> Improve error reporting on mirror failures

- go.mod
- go.sum
This primarily includes https://github.com/proglottis/gpgme/pull/23 , fixing use-after-free crashes.
> Update to github.com/mtrmac/gpgme@v0.1.1

- signature/mechanism_gpgme.go
- signature/mechanism_openpgp.go
… instead of by value.
AFAICS this did not have any actual undesirable impact (the mechanism object is either not used at all, or used only to read another object reference), but it was not intentional and passing the data by value could lead to surprises later.
> Always use SigningMechanism implementations by reference

- directory/directory_dest.go
This fixes the chmod and file handle problem on windows for dir destination following the same code pattern used in oci_dest.go
Signed-off-by: Boris Kuschel <boris.kuschel@qlik.com>
> Windows fixes for dir: destination

- docs/containers-registries.conf.5.md
- docs/containers-registries.d.5.md
We now document the already existing internal `/library` suffix for
docker.io mirrors and provide an example how to deal with them.
I also fixed two typos in `containers-registries.d.5.md`.
Closes https://github.com/containers/image/issues/775
> Add documentation about rewriting docker.io registries

- copy/copy.go
- go.sum
Relax the platform checks of the source images architecture and OS when
copying.  Some images do not set these attributes correctly in their
config which unexpectedly broke previously running deployments.
Instead of returning an error, just info-log about the mismatch.
> copy: relax platform checks

- docker/archive/transport.go
- docker/archive/transport_test.go
- go.sum
- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
- tarball/tarball_reference.go
- tarball/tarball_transport.go
`New*Reference` allows creating references from well-typed data without string formatting and parsing; this adds it to a few transports that were missing the functionality.
Also adds `storage.Transport.GetStoreIfSet` (naming?) to allow checking that the default store is not set to two different values in a single application.
> Add NewReference to a few transports, + storage.GetStoreIfSet

- copy/copy.go
While debuging skopeo copy feature I ran into an issue where the remote image registry was reporting an absent blob error during a Manifest upload.
The error, from skopeo's point of view was:
FATA[0015] Error writing manifest: Error uploading manifest latest to registry/repo/image: manifest blob unknown: blob unknown to registry
By further reading image registry logs I noticed that skopeo never did upload the missing blob, I also noticed that we were ignoring an error during config's upload and decided to add a debug there. With my debug I discovered that the error being returned by the registry was:
received unexpected HTTP status: 503 Service Unavailable
The problem is indeed on the image registry(most likely in a load balancer) but we should never ignore errors, hence this patch.
> Bubbling up errors returned by copyBlobFromStream

- docs/containers-registries.conf.d.5.md
- go.mod
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/base-for-registries.d.conf
- pkg/sysregistriesv2/testdata/registries.conf.d/config-1.conf
- pkg/sysregistriesv2/testdata/registries.conf.d/config-2.conf
- types/types.go
When loading the registries.conf, allow for loading additional files
from `/etc/containers/registries.conf.d`.  The files are loaded in
alpha-numerical order and specified fields will overwrite the previous
config.
> registries.conf.d: add stances for the registries.conf

- docs/containers-registries.conf.5.md
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
provide per-user configuration of registries.conf under $HOME/.config/containers/registries.conf for other tools.
> Add $HOME/.config/containers/registries.conf to config path

- docker/docker_client.go
- docker/docker_client_test.go
- docs/containers-certs.d.5.md
- docs/containers-registries.conf.5.md
We want to allow users to store certs in their homedir when running in rootless mode.
We want rootless podman and rootless buildah to add $HOME/.config/containers/certs.d
to the search path for certificates by default.
Currently there is no way for a non privileged user to get certs without being root on
the system or specify the certs dir on ever call.
> Add $HOME/.config/containers/certs.d to perHostCertDirPath

- docs/containers-auth.json.5.md
The initial man page for the authfile used by
the container tools.
Fixes: https://github.com/containers/libpod/issues/4359
> Intial authfile man page

- pkg/sysregistriesv2/system_registries_v2.go
Only print the debug message in `(*Endpoint).rewriteReference()` if the
reference has actually been rewritten.
> sysregistriesv2: only print debug message if ref was rewritten

- docker/docker_client.go
- docker/docker_image_src.go
- types/types.go
Close https://github.com/containers/image/issues/689
I tried not to break backward compatibility, so I didn't change `config.GetAuthentication`. If I can do it, I'd like to make `config.GetAuthentication` return `registryToken` as well, but I'll follow your thought anyway.
Also, are there any tests against private images?  I looked for the test with `sys.DockerAuthConfig` because I wanted to add tests for `sys.DockerRegistryToken` to it, but I couldn't find it. Although I've added only the failing test, I should add happy path as well. Would you tell me how to achieve it?
> feat(docker): support docker registry token

- image/docker_schema1.go
- image/docker_schema1_test.go
- image/docker_schema2.go
- image/docker_schema2_test.go
- image/manifest.go
- image/oci.go
Addressing Issue https://github.com/containers/image/issues/746
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Make UpdatedImage update after conversion of MIME type

- docker/docker_client.go
- pkg/docker/config/config.go
- pkg/docker/config/config_test.go
- pkg/docker/config/testdata/example_identitytoken.json
- types/types.go
Adding the support for using identitytoken in the .docker/config.json
files. It's part of oauth2 and Azure Container Registry is one of the case that uses this.
Since containers/image implemented it's own docker registry client, we want to make it working with oauth2. The identitytoken can be used to get an access/bear token in place of password. Instead of setting basicAuth in the request, we follow the oauth2 definition to send a post request with grant_type.
Reference:
1. Docker registry oauth2 documentation: https://docs.docker.com/registry/spec/auth/oauth/
2. Azure Container Registry oauth2 documentation: https://github.com/Azure/acr/blob/7eddc1c5866ce5cc80e95df37d9d119e70d8c15e/docs/AAD-OAuth.md
Test: Tested with podman and logging into azure container registry, which uses …
> Support IdentityToken in registry authn

- copy/copy.go
- image/manifest.go
- types/types.go
The additional interface "SupportsEncryption" was required temporarily due to https://github.com/containers/image/issues/746 
Quote from the TODO in code:
>Remove src.SupportsEncryption call and interface once copyUpdatedConfigAndManifest does not depend on source Image manifest type. Currently, the way copyUpdatedConfigAndManifest updates the manifest is to apply updates to the source manifest and call PutManifest of the modified source manifest. The implication is that schemas like docker2 cannot be encrypted even though the destination supports encryption because docker2 struct does not have annotations, which are required.
Reference to issue: https://github.com/containers/image/issues/746
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Remove manifest interface SupportsEncryption

- image/oci_test.go
- manifest/docker_schema2_list.go
- manifest/oci.go
- manifest/oci_index.go
- manifest/oci_test.go
69aa1e85460f ("media type checks") introduced a whitelist of required mime
types for individual layers.
However, this actually violates the OCI spec,
https://github.com/opencontainers/image-spec/blob/master/manifest.md which
says:
"An encountered mediaType that is unknown to the implementation MUST be ignored."
Indeed, we have code that uses manifest types not defined in this
whitelist, so it breaks our code.
Signed-off-by: Tycho Andersen <tycho@tycho.ws>
> oci manifest: do not require whitelist of layer types

- copy/copy.go
- copy/manifest.go
Similarly to how we fall back to trying to push single-image manifests in alternate formats when the original/preferred type is rejected by a registry, attempt to do the same for manifest lists.
> copy: try list conversions on list push failures

- copy/copy.go
- copy/manifest.go
- image/fixtures/schema2list.json
- internal/pkg/platform/platform_matcher.go
- internal/pkg/platform/platform_matcher_test.go
- manifest/docker_schema2_list.go
- manifest/list_test.go
- manifest/oci_index.go
- types/types.go
This carries over #786 , updating it on top of the later changes to warn instead of reporting an error.
Then, the error messages were updated (now that they don’t abort) to make more sense with multiple platform options. See the added test for an example.
> Add the option to choose an image by the variant field in a manifest

- internal/pkg/platform/platform_matcher.go
Otherwise, on ARM, users with `ArchitectureChoice: "amd64"` still end up with a `wantedVariant: "v7"`.
Fixes: #864 .
> Only auto-detect platform variant if we are also auto-detecting the architecture

- openshift/openshift-copies.go
- openshift/openshift-copies_test.go
imdario/mergo, despite its official documentation, does not merge public fields inside private fields as of v.0.3.9: https://github.com/imdario/mergo/issues/139
Fixing that seems non-trivial.
Instead, make the `restTLSClientConfig` a public field of `restConfig`.
The `restConfig` type itself remains private, so this does not make anything actually public outside the subpackage. This way, the calls to mergo work as expected with both 0.3.8 and 0.3.9.
> Make restTLSClientConfig in restConfig a public field

- internal/pkg/platform/platform_matcher.go
> getCPUVariantWindows uses arch provided to getCPUVariant

- docker/docker_client.go
could be elaborated to include release however this fixes a problem with missing the *required* `client_id` form field  
per https://tools.ietf.org/html/rfc6749#section-4.1.3
> set client_id

- copy/copy.go
When copying a manifest list, if we don't change any of its contents and don't change its type, use the original serialized version instead of one that we re-encoded ourselves.
> copy: avoid unnecessary re-encoding of source lists

- docker/docker_client.go
Per https://github.com/containers/image/issues/843
https://github.com/metallkopf provided a patch which is now needed in 2 paces
copy from makeRequestToResolvedURLOnce()
> Add User-Agent to docker oauth requests

- copy/copy.go
If `copySemaphore.Acquire()` fails, other goroutines continue to run and may use `progressPool`.  Wait for them to finish before closing the pool.
> Fix use of progressPool after it is closed.

- manifest/oci_index.go
This field is optional per the spec "SHOULD be present if its target
is platform-specific", and as noted in
https://github.com/containers/skopeo/issues/901 this happened in
practice.
Signed-off-by: Alexander Larsson <alexl@redhat.com>
> OCI: Don't crash if OCI1Index.Manifests[].Platform is nil

- manifest/common.go
- manifest/common_test.go
- manifest/docker_schema2.go
- manifest/list.go
- manifest/manifest.go
- manifest/manifest_test.go
- manifest/oci.go
In preparation to fixing #733, this simplifies MIME type updates in manifests by factoring out the code common to all cases, and by making the mapping itself table-driven instead of a large set of manually written switch statements.
Should not change behavior, apart from some error strings.
> Simplify MIME type updates

- registries.conf
Version 2 of the registries.conf has been used long enough in the wild
to consider it stable.  Hence, remove the references in the
registries.conf file to the previous version in hope to increase v2
adoption.
> registries.conf: remove references on v1

- docker/docker_image_dest.go
- internal/uploadreader/upload_reader.go
- internal/uploadreader/upload_reader_test.go
This should
fix #750 , fix #756 .
primarily by preventing the net/http layer from using the input stream after it returns a response to the request.
So far I don’t know of a reliable way to add a test for this (after all, it is a race); a reliable way to trigger the race with the original code is https://github.com/containers/image/issues/750#issuecomment-619107393 , but that violates the rules of the used API.
> Fix panic on terminated blob uploads

- image/fixtures/schema2list-variants.json
- internal/pkg/platform/platform_matcher.go
- internal/pkg/platform/platform_matcher_test.go
- manifest/list_test.go
- When a variant is autodetected (or specified), always try a `Variant: ""` image as well – and only as the last attempt. This is necessary for images like `docker://k8s.gcr.io/pause:3.1` .
NOTE: This includes the case of `VariantChoice` with a completely unrecognized variant, even in that case we try `Variant: ""`.
- When a variant is not specified with `OverrideArch`, or perhaps not autodetected, try an image with a "base variant" as well. This is necessary for images like `docker://busybox:1.27.2` . If the available images contain _both_ a `Variant: ""` and a `Variant: baseVariant` image, the two are equivalent in priority and the outcome is ambiguous; in that case, prefer the `Variant: ""` image to more closely match the `VariantChoice` made; the caller can always explicitly use …
> Improve handling of Variant: ""

- docs/containers-registries.conf.5.md
We don't want users using VERSION 1 any longer.  So remove all references
to depracated configuration.
> Remove registries.conf VERSION 1 references from man page

- docker/docker_image_dest.go
… and clean up parameters a bit.
> Use the correct instance digest when uploading signatures using X-R-S-S

- docker/docker_image.go
- docker/docker_image_src.go
- docker/docker_image_src_test.go
... because that value is used for signature verification.
<s>WIP because I need to figure out how to add test coverage. In the mean time, let’s at least run the Skopeo and Podman tests.</s>
> Don't change dockerImageSource.Reference() if a mirror is used

- go.mod
These show up on every single `make`.
Dependabot should probably be including them with its PRs, for now just commit them separately to exclude this from unrelated PRs.
> Commit Go-created go.mod updates

- docker/docker_image_src.go
Often, manifests fail to pull because of a MIME type mismatch and have
to be debugged manually to figure out what the server/proxy is sending
the client.  This is much easier to see when it's just printed for you.
Signed-off-by: Robb Manes <rmanes@redhat.com>
> Add debug line to get Content-Type from manifests

- docs/containers-policy.json.5.md
- signature/policy_config.go
- signature/policy_config_test.go
Add support for default rootless policy path of $HOME/.config/containers/policy.json
> Add defaults for using the rootless policy path

- pkg/docker/config/config.go
1. Using os.Stat() without checking that the result is a directory is
error-prone: there might be a file with the same name as target dir.
2. There is no need to use os.Stat() before calling os.MkdirAll() as
the latter does it as well.
3. Reverse the checks, error out early in case of legacyFormat.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
> pkg/docker/config/ModifyJSON: fix MkdirAll usage

- go.sum
- manifest/oci.go
Don't use the schema2 config field, which is a pointer that may be nil; the OCI config is an embedded struct and accessing it is always possible.
Using the OCI config is more correct anyway.
Should fix https://github.com/containers/libpod/issues/6361 .
> Fix crash on inspecting an OCI image with no config

- docs/containers-auth.json.5.md
- pkg/docker/config/config.go
Add hardcode Authfile for windows and mac used for the credential store.
fix https://github.com/containers/skopeo/issues/923
> Add hardcode Authfile for windows and mac

- docs/containers-auth.json.5.md
Add documentation for credHelper. Close https://github.com/containers/libpod/issues/1675
> Add documentation for credHelper

- copy/copy.go
- If `LayerInfosForCopy` returns a modified list, report it as an user-targeted error instead of an internal one: this is the first place a `podman push` of a signed image would fail.
- In error messages, report both possible causes (signed image or a digested destination).  I took the simple approach here, listing both options , instead of determining which one applies in the current situation.
> Fix error messages on !canModifyManifest

- copy/copy.go
- types/types.go
The new event indicates that a blob has been skipped. This information
can be used by CRI-O for more detailed image layer re-use metrics.
> Add support for ProgressEventSkipped

- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
In ca5fe04cb38a ("Add manifest list support"), the code was changed from a
single step (match on the name annotation) to a two step process: 1. untag
the existing name, and 2. match on the manifest's digest and change the tag
of this match to the new tag.
However, this means that if there were two tags:
"foo": sha256:c0ffee55
"bar": sha256:deadbeef
And we update "bar" to point to c0ffee55, we'd end up doing:
1. remove any "bar" tags:
"foo": sha256:c0ffee55
"": sha256:deadbeef
2. re-tag the first c0ffee55 thing:
"bar": sha256:c0ffee55
"": sha256:deadbeef
Thus losing the "foo" tag entirely.
Instead, let's make sure that we only re-tag something with the empty
string, so we don't delete existing tags.
Signed-off-by: Tycho Andersen <tycho@tycho.ws>
> oci: don't overwrite tags pointing at the same manifest

- copy/copy.go
Currently the error message is:
> Can not copy signatures: X-Registry-Supports-Signatures extension not supported, and lookaside is not configured
which does not tell the user whether to check the source or the destination.
Mention the destination explicitly.
> When we can't store signatures, point the user at the destination.

- docs/containers-registries.conf.d.5.md
- pkg/sysregistriesv2/system_registries_v2.go
Document the ConfigPath() and ConfigDirPath() as deprecated API. Add new ConfigurationSourceDescription() API returning the config file and directory sources.
Load the rootless registries.conf.d for override
> Load the rootless registries.conf.d for override

- pkg/blobinfocache/default_test.go
- pkg/docker/config/config_test.go
Some tests were leaking their dirs in /tmp.
> Cleanup tests

- docker/docker_client.go
Enable search registry specifying the number of results rather than using default API 100 limit.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1827794
> enable search using pagination

- pkg/docker/config/config.go
`auth.json` contains sensitive info which should not be seen or modified by other people
and no need for execution right, so we change the default filemode from
0755 to 0600
Fix: #974
Signed-off-by: CooperLi <a710905118@gmail.com>
> pkg/docker/config: correct default file mode when create auth.json file

- .travis.Dockerfile
Skopeo (via `make test-skopeo` ) now uses github.com/hashicorp/go-multierror , which requires Go 1.13.
> Update to Go 1.13

- Makefile
- docker/docker_client.go
Backports pagination fix #964 to release-5.5
Enable search registry uses the pagination until the search result reaches the limit, instead of returning default 100 limit from registry API.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1866153
> backports pagination fix

- docker/archive/dest.go
- docker/archive/reader.go
- docker/archive/src.go
- docker/archive/transport.go
- docker/archive/transport_test.go
- docker/archive/writer.go
- docker/daemon/daemon_src.go
- docker/internal/tarfile/reader.go
- docker/internal/tarfile/src.go
- docker/internal/tarfile/src_test.go
- docker/tarfile/src.go
- docker/tarfile/types.go
- docs/containers-transports.5.md
- Add support for choosing an image to read from a `docker-archive:`, either by reference (using the existing syntax) or by index (`docker-archive:/some/path:@0`).
- Add `docker/archive.Reader` that allows listing all images in a `docker-archive`-formatted file, and reading any/all of them, only copying/extracting the archive once.
> Support reading any/all images from docker-archive: tarballs

- go.mod
v1.23.1 is causing regressions in Podman's `apiv2` tests.
I do not have the time to track it down but need to get
work done that's currently blocked by the regression [1].
```
[+0064s] not ok 291 [40-pods] POST libpod/pods/bar/start [] : status
[+0064s] #  expected: 200
[+0064s] #    actual: 500
[+0064s]   expected: 200
```
> revert containers/storage to v1.23.0

- docker/lookaside.go
- docker/lookaside_test.go
- docs/containers-registries.d.5.md
Support per user  ~/.config/containers/registries.d to allow rootless podman push image sign.
> Support per user registries.d

- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/errors.go
Format the error message use the response body if the original error is returned as client.UnexpectedHTTPResponseError type
Use this pach:
```
$ skopeo copy --dest-tls-verify=false docker://library/alpine:latest docker://127.0.0.1:5000/cp:latest
FATA[0000] Error writing blob: Error initiating layer upload to /v2/cp1/blobs/uploads/ in 127.0.0.1:5000: StatusCode: 405, Method not allowed
```
> Return error body if UnexpectedHTTPResponseError

- signature/policy_config_test.go
policy_config_test.go was created by copy&pasting the same ideas quite a few times, consolidate most of the JSON-related test code and parametrize only the parts that actually differ.
See individual commit messages for a bit more detail.
This is +385-648, or +243-506 when ignoring white space changes.
> Reduce duplication in signature/policy_config_test.go

- oci/archive/oci_transport.go
Pass NoLchown in the Taroptions to avoid the lchown permission denied error dealing with archive.
Fix https://github.com/containers/image/issues/1017
> Set NoLchown to true in untar opts

- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/lookaside.go
- docker/lookaside_test.go
- docs/containers-registries.d.5.md
- internal/rootless/rootless.go
- pkg/blobinfocache/default.go
Set default rootless sigstore to ~/.local/share/containers/sigstore if the caller is non-root.
Fix rootless podman push --sign-by.
> Set default rootless sigstore

- pkg/docker/config/config.go
Use $DOCKER_CONFIG/config.json as an auth path to match the behavior of the docker CLI.
Fixes #1055
Signed-off-by: Jesse Rittner <rittneje@gmail.com>
> use DOCKER_CONFIG if set

- docs/containers-auth.json.5.md
- pkg/docker/config/config.go
Add XDG_CONFIG_HOME to the paths to be searched when login a registry. If XDG_CONFIG_HOME is empty, search under $HOME/.config. In the order that first search for authfile, XDG_RUNTIME_DIR, XDG_CONFIG_HOME, and docker config file.
Close: https://github.com/containers/podman/issues/7563
> Search credentials under XDG_CONFIG_HOME

- docker/docker_image_src.go
While container/image is not affected by CVE-2020-15157 future
generations may wonder why authentication is turned off on additional
URLs provided by certain blobs.
> add comment on CVE-2020-15157

- docker/docker_image.go
Docker Hub is instituting [pull rate-limits for anonymous and free users](https://www.docker.com/increase-rate-limits) since Nov 2, 2020.
> You are receiving this email because of a policy change to Docker products and services you use. On Monday, November 2, 2020 at 9am Pacific Standard Time, Docker will begin enforcing rate limits on container pulls for Anonymous and Free users. Anonymous (unauthenticated) users will be limited to 100 container image pulls every six hours, and Free (authenticated) users will be limited to 200 container image pulls every six hours, when enforcement is fully implemented. Docker Pro and Team subscribers can pull container images from Docker Hub without restriction, as long as the quantities are not excessive or abusive.
With this limit in place, every time …
> Image's digest from HEAD request

- go.sum
- pkg/sysregistriesv2/shortnames.go
- pkg/sysregistriesv2/shortnames_test.go
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/aliases.conf
- pkg/sysregistriesv2/testdata/invalid-aliases.conf
- pkg/sysregistriesv2/testdata/invalid-short-name-mode.conf
- pkg/sysregistriesv2/testdata/registries.conf.d/config-1.conf
- pkg/sysregistriesv2/testdata/registries.conf.d/config-2.conf
- pkg/sysregistriesv2/testdata/registries.conf.d/config-3.ignore
- types/types.go
The use of unqualified-search registries entails an ambiguity as it's
unclear from which registry a given image, referenced by a short name,
may be pulled from.
There have been reports of squatting on some registries to trap users
into pulling from a registry that may have pull precedence over the
intended registry; all depending on the relative order of the entries
in the `unqualified-search-registries` field in the `registries.conf`.
Removing the feature of unqualified-search registries is not an option,
as many users depend on it.  The agreed on alternative is to introduce
aliases.  Aliases make short-name resolution explicit.  Similar to bash
aliases, the new `[aliases]` table (internally a `map[string]string`)
has a left-hand name and a right-hand value:
```TOML
[aliases] …
```
> sysregistriesv2: short-name aliasing

- pkg/sysregistriesv2/shortnames.go
- pkg/sysregistriesv2/shortnames_test.go
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- pkg/sysregistriesv2/testdata/registries.conf.d-usr1/no-usr.conf
- pkg/sysregistriesv2/testdata/registries.conf.d-usr2/empty-usr.conf
This is a “rebase” of #1076 on top of #1060, but that more than doubles the scope.
> sysregistriesv2: Split configuration loading and merging

- version/version.go
> 5.8 release

- go.sum
- pkg/sysregistriesv2/shortnames.go
The Docker version only checks for $HOME being set,
the storage version falls back to looking in the /etc/passwd
file for the current UID running the command "RootlessUID"
> Use storage/pkg/homedir rather then docker version

- copy/copy.go
- pkg/compression/compression.go
When copying a blob where we know to associate a compression algorithm with its MIME type, check if the blob was in fact compressed using that algorithm, and log a diagnostic message at level "debug" if it isn't.  Our local storage backend is less sensitive to this than others, but it's useful to me at least to be able to tell.  I'm not too sure about just adding a table for it, though.
> copy: check our assumptions about compression

- pkg/sysregistriesv2/system_registries_v2_test.go
Now that empty strings are rejected, don't include a valid value in the result.  This does not actualy change what is being tested, just makes it a tiny bit more readable.
> Tidy up TestParseShortNameMode

- docs/containers-policy.json.5.md
- signature/fixtures/policy.json
- signature/policy_config.go
- signature/policy_config_test.go
- signature/policy_reference_match.go
- signature/policy_reference_match_test.go
- signature/policy_types.go
This allows accepting signatures for a complete or partial mirror of some other repository namespace in a single step, similar in signing effect to setting up mirrors in `registries.conf`, but letting image consumers refer to the mirrors directly.
For tag/digest matching, this currently only implemnents the default `matchRepoDigestOrExact`-like semantics; it's the right choice for almost all users, and we can add other alternatives later if it turned out to be necessary.
> Add a signedIdentity choice "type": "remapIdentity"

- pkg/shortnames/shortnames.go
- pkg/shortnames/shortnames_test.go
When a short-name could not be resolved to an alias and if there's no
unqualified-search registry, throw an error.
Reported-in: github.com/containers/podman/issues/8573
> shortnames: error if there's no alias and no search registries

- tarball/doc.go
Looks like the `copy.Image` interface has changed, small update to example documentation for new interface.
> fix tarball example code

- docker/docker_image_src.go
- types/types.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1881694
This BZ needs change the log level of the image pull location from the debug to info.
Add DockerLogMirrorChoice to types.SystemContext for keeping log level of the physical pull source of images.
Crio could set it to log the image source if it's from a mirror.
> Add logMirrorChoice to ctx for log

- copy/copy.go
- directory/directory_dest.go
- docker/docker_image_dest.go
- docker/internal/tarfile/dest.go
- docker/tarfile/dest.go
- image/docker_schema2.go
- image/oci.go
- internal/blobinfocache/blobinfocache.go
- internal/blobinfocache/types.go
- manifest/common.go
- manifest/common_test.go
- manifest/docker_schema2.go
- manifest/oci.go
- oci/archive/oci_dest.go
- oci/layout/oci_dest.go
- openshift/openshift.go
- ostree/ostree_dest.go
- ostree/ostree_transport_test.go
- pkg/blobinfocache/boltdb/boltdb.go
- pkg/blobinfocache/boltdb/boltdb_test.go
- pkg/blobinfocache/internal/prioritize/prioritize.go
- pkg/blobinfocache/internal/prioritize/prioritize_test.go
- pkg/blobinfocache/internal/test/test.go
- pkg/blobinfocache/memory/memory.go
- pkg/blobinfocache/memory/memory_test.go
- pkg/blobinfocache/none/none.go
- pkg/blobinfocache/none/none_test.go
- storage/storage_image.go
- types/types.go
Extend the blob info cache to also cache the name of the type of compression used on a blob in a known location.  (An earlier version of this patch cached the full MIME type, but required additional logic to map the MIME types in cases where we converted images during copying, so the patch was larger.)
Pass an updated MIME type and information about compression changes to PutBlob() in its input BlobInfo, so that it can populate the blob info cache with correct compression information when it succeeds.  Some of the local tables we kept in `manifest/common.go` were moved to an internal package (`internal/mediatypes`) so that they could be reused there.
Make sure that when `dockerImageDestination.TryReusingBlob()` successfully uses a blob from the blob info cache, that it provides updated …
> blobinfocache: cache compression types

- copy/copy.go
The `copyConfig` caller already sets `canModifyBlob` to `false`, set it explicitly inside the function just to make the relationship easier to follow.
Also fix some comments.
Motivated by https://github.com/containers/image/pull/1089#discussion_r558475506 .
> Clarify the canModifyBlob condition in copyBlobFromStream

- pkg/shortnames/shortnames.go
When short name expansion is happening in Podman and Buildah there
are two many useless words being repeated on the screen. Also the
actual expansion is never shown. This PR shortens the text to only
the key descriptions and displays the actual long name.
podman pull ubi8
Resolved "ubi8" (/etc/containers/registries.conf.d/shortnames.conf)
...
> Cleanup description of shortname expansion

- copy/copy.go
- directory/directory_dest.go
- docker/docker_client.go
- storage/storage_test.go
Users should be able to set the number of ParallelDownloads so that
they can customize how container/tools perform based on the
characteristics of their network.
> Allow callers to set the MaxParallelDownloads field

- docker/docker_client.go
- docker/docker_client_test.go
Currently, the User-Agent defaults to a golang default of either:
Go-http-client/1.1
Go-http-client/2.0
This makes it rather difficult to distinguish this client from any other
random golang program in registry logs.
Instead, set the default User-Agent to `"containers/$VERSION (github.com/containers/image)"`.
Context: https://github.com/containers/skopeo/issues/1109
Signed-off-by: Jon Johnson <jonjohnson@google.com>
> Set a default User-Agent if unset

- docker/lookaside.go
- internal/tmpdir/tmpdir.go
- pkg/sysregistriesv2/system_registries_v2.go
- signature/policy_config.go
Tweak the path in the comment, to avoid the next reader hitting the same copy&paste error (but in general, it seems annoying that this comment will go out of date next module version)
> Fix 'systemDefaultPolicyPath' linker flag comment

- copy/copy.go
Primarily fixes writing of signatures if a manifest of a multi-arch image is updated.
Also cleans up the documentation of the blob copy pipeline to be a bit more consistent.
> Copy cleanups

- docs/containers-registries.conf.5.md
- pkg/sysregistriesv2/shortnames.go
As shown in github.com/containers/podman/issues/8559, writing to the
$HOME directory or root may be undesired.  Using /var/cache for root and
$HOME./cache for ordinary users, however, is common practice.
> short-name-aliases.conf: use cache folders instead of $HOME

- version/version.go
Since we created a `release-5.10` branch, let's move the main branch
over to v5.11.0-dev to prevent any ambiguity or reduce potential
confusion.
Anything we want in 5.10.X must from now on be backported to the branch.
@rhatdan @lsm5 @giuseppe PTAL
> bump to v5.11.0-dev

- pkg/shortnames/shortnames.go
When a short name could not be resolved via `shortnames.Resolve(...)`
the error message attempts to help the users solve the issue by pointing
to short-name aliases and the registries.conf.
Until now, the error implied the existence of a registries.conf which
may not always be the case.  Hence, check whether a registries.conf
was used during short-name resolution and point to the manpage if none
was present.
@rhatdan @giuseppe  @lsm5 @umohnani8 PTAL
> shortnames: resolution error: point to manpage if config is absent

- README.md
Update the godoc link to point to v5.
Fixes: #1154
> README: godoc: point to v5

- copy/copy.go
Teach `BlobInfoCache2` implementations to be able to retrieve the type of compression that was applied to a blob with a given digest, if we know it.
If we successfully reuse a blob while writing an image, and we know how a blob with that reused blob's digest was compressed, use that information when updating the MIME type for the reused blob.
This covers situations where `TryReusingBlob()` returns a `BlobInfo` containing a different digest and MIME type than the one we originally asked it to reuse.  `copy.imageCopier.copyLayers()` sets it up as part of the `LayerInfos` in update info that `copy.imageCopier.copyUpdatedConfigAndManifest()` passes to `src.UpdatedImage()`, and the `UpdateLayerInfos()` implementations discard the MIME type from the new `BlobInfo` in favor of the MIME type in …
> copy: compute blob compression on reused blobs based on source MediaType

- copy/copy.go
Teach BlobInfoCache2 implementations to be able to retrieve the type of compression that was applied to a blob with a given digest, if we know it.
If we successfully reuse a blob while writing an image, and we know how a blob with that reused blob's digest was compressed, use that information when updating the MIME type for the reused blob.
This covers situations where TryReusingBlob() returns a BlobInfo containing a different digest and MIME type than the one we originally asked it to reuse. copy.imageCopier.copyLayers() sets it up as part of the LayerInfos in update info that copy.imageCopier.copyUpdatedConfigAndManifest() passes to src.UpdatedImage(), and the UpdateLayerInfos() implementations discard the MIME type from the new BlobInfo in favor of the MIME type in the original layers …
> [release-5.10] copy: compute blob compression on reused blobs based on source MediaType

- storage/storage_image.go
When reading blobs (e.g., layers) from the storage, write the data to a
temporary file first and return its file descriptor.
The main goal is to keep the time of the storage being locked as short
as possible.  With this approach we are disk-bound which is generally
faster than being network bound.
The motivation for this change is the desire to allow for accessing the
storage during pushes.  We have attempted to optimize certain execution
paths in containers/storage but those require the callers to know
whether data will be manipulated or read, which is far from being
trivial.  The daemon-less nature of the storage also requires to write
certain data.
This approach here is entirely transparent to the storage.
> storage: GetBlob: write to a local tempfile

- storage/storage_image.go
Since #1138, we've been paying attention to the MediaType values returned by LayerInfosForCopy(), so lying about layer data being compressed when the data we provide isn't would cause uncompressed layers to be mistakenly marked as compressed when we copied the image without attempting to add or modify the compression of layers.
> storageImageSource.LayerInfosForCopy(): return uncompressed MediaTypes

- storage/storage_image.go
Since v5.10.4, we've been paying attention to the MediaType values returned by LayerInfosForCopy(), so lying about layer data being compressed when the data we provide isn't would cause uncompressed layers to be mistakenly marked as compressed when we copied the image without attempting to add or modify the compression of layers.  Cherry picked from #1168.
> [release-5.10] storageImageSource.LayerInfosForCopy(): return uncompressed MediaTypes

- docs/containers-registries.conf.d.5.md
Signed-off-by: Dominic Yin <yindongchao@inspur.com>
The files loaded in `registries.conf.d` are filtered by suffix but not prefix, I think this is a typo.
https://github.com/containers/image/blob/71dd98800529ab55cc64da3735ff7675c2a84d8b/pkg/sysregistriesv2/system_registries_v2.go#L529
> fix typo in docs/containers-registries.conf.d.5.md
