containers/image

docker/docker_client.go, docker/docker_image.go, docker/docker_image_src.go
fix socket leak for this:
- `docker.GetDigest (even on success)`
- `docker.makeRequestToResolvedURL`
- `docker.getExternalBlob`
=> fix docker socket leak

copy/copy.go, internal/types/types.go, storage/storage_image.go
When copying an image to a storage destination, make sure to commit
downloaded layers as early as possible.  Since layers are committed in
sequence, we need to preserve the index of each layer: layer N can only
be committed to the storage when all N-1 previous layers are already
present in the storage, in the given order.
Two new methods are added to the storage destination to pass down the
index to TryResusingBlob and PutBlob.  The idea is fairly simple:
* PutBlobWithOptions and TryReusingBlobWithOptions can "queue in" work.
* Exaclty one caller of them may enter a second stage which is
committing the previously queued in blobs to the storage while
preserving the order.  If one caller is already in stage two,
others will return early freeing up goroutines workers to continue
pulling more …
=> copy to storage: commit layers as early as possible

manifest/fixtures/ociv1.artifact.json, manifest/manifest.go, manifest/manifest_test.go, oci/layout/oci_src.go
If a schema version 2 manifest doesn't include a top-level media type,
default to "guessing" it's an OCI v1 manifest.
Previously, we defaulted to a Docker v2s2 manifest which is causing
issues for OCI artifacts which may ship a custom config media type.
In that case, we guessed it's a Docker image which is wrong.
To harden the code a bit further, add an additional media-type check for
the config to not only check for an ordinary OCI config but also a
Docker one.
Found the issues while prototyping source containers in Buildah. @rhatdan @nalind @giuseppe @lsm5 PTAL
=> manifest: GuessMIMEType: support OCI artifacts

docs/containers-registries.conf.5.md, go.mod, go.sum, pkg/docker/config/config.go, pkg/docker/config/config_linux.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/cred-helper-with-auth-files.conf, pkg/docker/config/testdata/cred-helper.conf, pkg/docker/config/testdata/docker-credential-helper-registry, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go, pkg/sysregistriesv2/testdata/cred-helper.conf, pkg/sysregistriesv2/testdata/registries.conf.d-empty-helpers/empty.conf, pkg/sysregistriesv2/testdata/registries.conf.d/config-1.conf, pkg/sysregistriesv2/testdata/registries.conf.d/config-2.conf
Allow for configuring credential helpers in `registries.conf` files.
Credential helpers are configured as a top-level field
`credential-helpers`.  This is an array of strings.  Items listed in the
array are consulted in the specified order when looking up or removing
credentials.
Note that there is a built-in credential helpers `containers-auth.json`
for using auth files.  If no global defaults are specified, we will
fallback to using auth files.  This assures backwards compat and a
working default setting.
The traces of the disabled "keyring" functionality have largely been
removed.  If we ever want to re-enable support, we can follow the
example of auth files and specify a new built-in keyring helper.
Using a built-in helper simplifies the code quite a bit since the code
structure …
=> registries.conf: configure credential helpers

docs/containers-registries.conf.5.md, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go, pkg/sysregistriesv2/testdata/find-registry.conf, pkg/sysregistriesv2/testdata/missing-registry-location.conf, pkg/sysregistriesv2/testdata/registries.conf.d/subdomain-override-1.conf, pkg/sysregistriesv2/testdata/registries.conf.d/subdomain-override-2.conf, pkg/sysregistriesv2/testdata/registries.conf.d/subdomain-override-3.conf, registries.conf, version/version.go
This commit allows the prefix field in registries.conf to be of the
form: `prefix = "*.example.com" for wildcard subdomain matching.
refMatchesPrefix now returns the length of the prefix if there's a match
and the prefix doesn't contain `*.`. If prefix contains `*.` and there's
a match, then refMatchesPrefix returns the length of the refString
without the image. This change removes the need for
any additional string comparison in `rewriteReference`.
Co-authored-by: Valentin Rothberg <rothberg@redhat.com>
/cc @ashcrow
=> Enable subdomain matching in registries.conf

oci/layout/oci_src.go
Commit 8e3a21bd0271 missed to remove a debug log from diagnosing the
issue.
=> oci/layout: remove debug log

copy/copy.go, storage/storage_image.go
Temporarily disable committing blobs early to fix a bug related to
mistakenly committing empty layes [1].  The plan is to reeanble the
feature when a solid solution for passing down the layer information
is found.
[1] https://github.com/containers/image/pull/1205#issuecomment-822459523
=> copy: temporarily disable early commits

.cirrus.yml, contrib/cirrus/runner.sh, hack/get_ci_vm.sh
The `test_skopeo_task` must be substantially duplicated between this
repository and containers/skopeo.  Make this easier to maintain by
implementing a runner script to contain any/all differences.  This
allows the `test_skopeo_task` definition to remain 100%
identical across the two repositories.
=> Cirrus: Improve test synchronization with c/skopeo

version/version.go
* Update F34beta -> F34 and U2010 -> U2104
* Bump github.com/containers/storage from 1.30.0 to 1.30.1
* Skip pulling layers reusable from additional layer store
* Bump github.com/containers/storage from 1.29.0 to 1.30.0
* Cirrus: Improve test synchronization with c/skopeo
=> Bump to v5.12.0

storage/storage_image.go
Set the names on an image last, after we've stored its config blob, manifests, and signatures.  This will keep callers that look up an image and then immediately try to inspect it from getting tripped up if they hit the window between when we set the names and save the data that's used when we inspect an image.
=> storage: set image names last

copy/copy.go, internal/types/types.go, storage/storage_image.go
The early committing of blobs has been temporarily disabled in #1205.
There was a regression in deciding whether an empty layer may be
committed to the storage or not [1].
Initially, the early committing considerred a layer to empty (and hence
not commit it to storage) when it matched the shasum of an empty GZIP
layer.  As it turned out, that is not a reliable indicator since some
images may still include these layers in the diff IDs [2].
Re-enable the early committing of blobs by passing down the emptiness
information down by querrying the image's manifest.
[1] https://github.com/containers/image/pull/1205#issuecomment-822459523
[2] https://github.com/containers/image/pull/1205#issuecomment-822458565
=> copy: re-enable early commits

copy/copy.go, go.mod, go.sum
Update the mpb library we use to create progress bars to version 7.0.2.
Adjust the code for creating a custom spinner for blobs with an unknown
size.  This usually happens for v2s1 images.
Tested manually by pulling quay.io/vrothberg/test:nginx.
=> update mpb to v7.0.2

.cirrus.yml, Makefile, hack/validate.sh, pkg/docker/config/config.go, signature/policy_config_test.go
An error was introduced in
https://github.com/containers/image/pull/1140 that incorrectly changed
the command.  However, it was observed the previous command contained
a hidden bug WRT pipefail being unset by default.  Fix both problems by
ensuring golang tooling is present, and calling out to a shell-script
where the environment can be more carefully controlled and verified.
=> Fix missing gofmt and validate runtime environment

Makefile, pkg/docker/config/config_linux.go, pkg/docker/config/config_unsupported.go
This at least allows `make` not to fail (on non-Linux, and after the master/main rename).
https://github.com/containers/image/issues/1252 still needs addressing.
=> Fix (make)

pkg/docker/config/config.go
Small cleanups for #1204, primarily documenting that the value returned from `SetCredentials` is not an API.
=> SetCredentials nits

storage/storage_image.go
Do it from `defer`, so that any new error paths (and quite a few pre-existing ones that missed this) delete the image without
having to specifically care.  Also makes the code a bit shorter.
Note also the added comment; is deleting the image always the right thing to do?
Cc: @nalind . Looking at the existing code paths that didn’t clean up the image, it kind of looks as if failures to write to c/storage should cause the image to be deleted, but other failures (e.g. error computing a digest) should not delete it — but nothing documents such an intent and the code is not consistently behaving that way either.
=> RFC: Consolidate deleting a partial c/storage image on Commit failure

copy/copy.go, copy/manifest.go, copy/manifest_test.go, directory/directory_dest.go, directory/directory_test.go, directory/directory_transport_test.go, docker/archive/dest.go, docker/daemon/daemon_dest.go, docker/docker_image_dest.go, manifest/list_test.go, manifest/manifest_test.go, oci/archive/oci_dest.go, oci/layout/oci_dest.go, oci/layout/oci_dest_test.go, openshift/openshift.go, storage/storage_image.go, storage/storage_test.go, storage/storage_transport.go, types/types.go
An assorted set of small cleanups and some test extensions, mostly related to #400 .
=> Manifest list support nits

storage/storage_reference.go
- If the digest references a single-platform manifest, all matching images will have the same manifest, same config,
and same behavior of the dummy index created by `imageMatchesSystemContext`; so don't build that dummy index and  rename the function to `multiArchImageMatchesSystemContext` .
- If the digest references a multi-platform list, just check whether `ChooseInstance` would chose the current image; don’t check _both_ `ChooseInstance` based on the multi-platform list and config values through the dummy index. The original pull did both (`ChooseInstance` to choose a per-platform image, and `copy.checkImageDestinationForCurrentRuntime()`, so they are expected to match (and we don't do a config check vs. the current `SystemContext` to refuse handling single-platform images in …
=> RFC: Simplify digest references to manifest lists in c/storage

pkg/cli/environment/environment.go
Add a function that reads the env variables that Podman and Buildah are
sensitive to to set the registries conf path in the provided system
context, unless already set.
The motivation to move the functionality here is to consolidate
duplicate code across various places in Podman.
@mtrmac WDYT?
=> pkg/cli/environment: UpdateRegistriesConf

pkg/sysregistriesv2/shortnames.go, pkg/sysregistriesv2/shortnames_test.go, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go
primarily for v1/v2 mismatches.
=> Fix “empty config file” detection

pkg/sysregistriesv2/shortnames.go, pkg/sysregistriesv2/shortnames_test.go, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go
A RFC improvement on top of #1283 .
This is more expensive, but it automatically handles any future member additions.
Preserve the existing semantics of treating non-nil but empty slices and maps as “not non-empty”, just because the old implementation did so; I didn't check whether that actually ever happens and whether it matters for any existing callers.
=> Implement "non-empty configuration" using reflect.DeepEqual

Makefile, docker/docker_image_src.go, types/types.go
Backport 6e02506 and a3a6d00 for crio 1.19.
Close: https://bugzilla.redhat.com/show_bug.cgi?id=1976293
Add DockerLogMirrorChoice to types.SystemContext for keeping log level of the physical pull source of images.
Crio could set it log the image source if it's from a mirror.
=> release-5.5 Add DockerLogMirrirChoice

docker/docker_client.go, docs/containers-auth.json.5.md, pkg/docker/config/config.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/refpath.json
This patch adds support for `host[:port]/ns/…repo` to auth.json while keeping the backwards compatible behavior.
Refers to https://github.com/containers/image/issues/1276
=> Add support for registry paths in auth.json

README.md, docker/docker_client.go, docker/docker_transport.go, docker/errors.go, docs/containers-policy.json.5.md, manifest/manifest.go, openshift/openshift.go, pkg/docker/config/config.go, types/types.go
Will leave references to distribution spec until there is an OCI Spec we
can point at.
=> Change all references to docker registry to container registry

pkg/docker/config/config.go
… to not include the unwanted exact format specification, and now to make it consistent with `GetCredentialsForRef`.
#1256 claims to do this already, but I somehow didn’t actually remove the format documentation; trying again.
=> Fix documentation of SetCredentials

docker/docker_client.go
When searching via v2/catalog make sure that a full match is returned as
the first item.  The change is motivated by a conversation in a BZ [1]
on the rather undefined nature/semantics of searching images.
While this change does not fix the BZ, it may be a small improvement
when using the v2/catalog endpoint.
[1] bugzilla.redhat.com/show_bug.cgi?id=1976283
=> search: catalog: return full match as first item

copy/copy.go
Commit 3250f2da77d61931d38513846f2bb7fbf9352460 from #1084 removed the code that ensures the pipe is closed with error on a goroutine panic, i.e. that the caller does not hang indefinitely, for no clear reason; restore that.
=> Make compressionGoroutine panic-safe again

docs/containers-registries.conf.5.md
Fix a number of indentation issues in the containers-registries.conf man
page which caused rendering issues both in the man pages and the
upstream markdown on GitHub; move all to the root indent level/scope.
=> docs: fix indentation in registries.conf

docs/containers-auth.json.5.md, pkg/docker/config/config.go, pkg/docker/config/config_test.go
We now error on login if repositories or repository namespaces are used
for other credential helpers than the `AuthenticationFileHelper`. On
logout we ignore them and debug log a warning that nothing has been
modified.
The functions `SetCredentials` (for login) as well as
`RemoveAuthentication` (for logout) already feature support for path
based registries for the `AuthenticationFileHelper`. This patch adds
unit tests to ensure that the support will not break in the future.
Refers to https://github.com/containers/image/issues/1276
=> Support updating registry credentials scoped to namespaces/repos

pkg/docker/config/config.go, pkg/docker/config/config_test.go
As mentioned in containers/common#659 (comment), we now do not normalize the registry when being in non legacy format. This means we do not match "quay.io/foo" if "quay.io/bar" is provided as credentials, because both would be normalized to "quay.io" before this patch.
We also add a new corner case where auth.json has been external modified to contain an entry like "https://quay.io/v1/", which now also matches if "quay.io/foo" has been provided via the credentials.
=> Disable registry fallback for repository credentials

docker/docker_client.go, pkg/docker/config/config.go
We cannot use `GetCredentialsForRef` if we want to retrieve the
credentials for a single registry. This use case is still valid which
makes the deprecation of the API obsolete.
Refers to https://github.com/containers/common/pull/659#discussion_r672568675
=> Remove `GetCredentials` deprecation

docker/docker_transport_test.go
... to avoid docker.io pull limits.
`NewImageSource` and `NewImage` actually access the remote server (because `NewImageSource` is looking for a working mirror); update `NewImageDestination` basically for symmetry.
=> Use quay.io in docker unit tests instead of docker.io

pkg/compression/compression.go, pkg/compression/internal/types.go
Because `compressionAlgorithms` is a map, it is traversed in an unpredictable order, so using the same prefix for `zstd` and `zstd:chunked` meant that the caller could get either.
Define empty prefix as "opt out of detection", to always return `Zstd`.
=> Fix unpredictable outcome of compression.DetectCompression*

copy/copy.go, copy/copy_test.go, internal/blobinfocache/blobinfocache.go, manifest/common.go, manifest/common_test.go, manifest/docker_schema2.go, manifest/oci.go, pkg/blobinfocache/internal/prioritize/prioritize_test.go, pkg/compression/compression.go, pkg/compression/types/types.go
A partial fix for a #1146 .  See individual commit messages for details.
=> Remove dependency of c/image/manifest on pkg/compression

go.mod, go.sum, pkg/compression/compression.go
<s>WIP, includes #1310 and unmerged https://github.com/containers/storage/pull/972 </s>.
Take advantage of https://github.com/containers/storage/pull/972 so that pkg/compression doesn’t depend on all of c/storage including the graph drivers; this matters for various metadata-only or metadata-mostly users of (parts of) c/image.
Another partial fix to #1146 .
=> Reduce the dependency of pkg/compression on c/storage/pkg/chunked

docker/docker_client.go
`SearchRegistry` can return nil error when registry returns a status code that indicates an error, such as 401, because `err` is nil, which is ignored by `errors.Wrap` function.
=> Return an actual error instead of nil when registry returns bad status code

directory/directory_dest.go, directory/directory_transport.go, types/types.go
This is the accompanying PR for https://github.com/containers/skopeo/pull/1365
=> Add support for decompressing while copying to dir://

pkg/docker/config/config.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/full.json, pkg/docker/config/testdata/legacy.json
- Don't build a map just to access one element. NOTE: This might change behavior with ambiguous files, we now use the first matching entry, not the last one.
- Don't unnecessarily strip schema:// and /path from registry on search, and adjust tests
=> Simplify credential normalization, fix tests

docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, go.mod, oci/layout/oci_src.go, openshift/openshift.go
A few trivial cleanups of how we use `net/http`. Should not change behavior.
Fixes #1158.
=> HTTP cleanups

copy/copy.go
drop FetchPartialBlobs option and always try to pull the partial
image.
The partial pull is performed only when the image has an annotation,
so there is no need to request this information to the user.
=> copy: drop FetchPartialBlobs option

version/version.go
Since we now have a release-5.15 branch, the v5.15.x series will be cut
from there.
@mtrmac PTAL
=> bump main branch to v5.16.0-dev

go.mod, go.sum
It seems Dependabot can't handle the current version requirement as expected; the latest now is v20.10.8.
Intentionally update to v20.10.7 to verify that Dependabot will now find ...8.
=> Update docker/docker to v20.10.7+incompatible

copy/copy.go
Per the discussion in https://github.com/containers/image/issues/1013 and https://github.com/vbauerster/mpb/issues/93 , we must ensure all progress bars terminate, but doing that by canceling a context may prevent the final “complete” progress bar state to be rendered.
So, remove the context cancellation, and make every progress bar responsible for terminating itself.
Fixes #1013.
=> Rework progress bar termination

.cirrus.yml
otherwise Skopeo tests fail with
> ERROR: Environment variable 'SKOPEO_CIDEV_CONTAINER_FQIN' is required by contrib/cirrus/runner.sh:_run_setup() but empty or entirely white-space.  (/usr/share/automation/lib/console_output.sh:97 in req_env_vars())
=> Define SKOPEO_CIDEV_CONTAINER_FQIN

copy/copy.go
With destination transports where `DesiredLayerCompression() == Compress`, notably c/image/docker, only recompress layers if the user has explicitly requested a specific format in `SystemContext`; don't default to recompressing `zstd` layers to `gzip`.
See individual commit messages for more details.
Should address https://github.com/containers/skopeo/issues/1406 .
=> Don't recompress non-gzip data without an explicit request

pkg/docker/config/config.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/docker-credential-helper-registry
When calling a credential helper, there are two types of credentials
that may be returned: a username and password pair, or an identity
token. The credential helper uses the same struct for returning both
types of credentials. From the `docker login` [documentation]:
> If the secret being stored is an identity token, the Username should
> be set to `<token>`.
When an identity token is provided, the Docker client should
authenticate using OAuth2 rather than the standard bearer challenge
response.
This changeset modifies the credential helper code to recognize this
special username, and sets the IdentityToken field of DockerAuthConfig
instead of Username and Password.
[documentation]: https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol
Signed-off-by: Terin …
=> accept identity tokens from credential helpers

.cirrus.yml, go.mod, go.sum
Bump c/storage to v1.34.0 in the release-5.15 branch
Also backport #1334 to handle CIDEV container in Google cloud.
=> [release-5.15] Bump c/storage to v1.34.0

storage/storage_image.go
This is the smaller half of #1160.
Please see individual commit messages for details.
Cc:
- @nalind : Is there some subtlety about using `digest.Digest.Validate()`? Are there callers of `PutBlob()` that can’t be relied on to provide correct digests?
- @mrunalp
=> Don’t compute a digest of the compressed blob twice when pulling

internal/pkg/keyctl/key.go, internal/pkg/keyctl/keyring.go, internal/pkg/keyctl/keyring_test.go, internal/pkg/keyctl/perm.go, internal/pkg/keyctl/sys_linux.go, ostree/ostree_dest.go, ostree/ostree_src.go, ostree/ostree_transport.go, ostree/ostree_transport_test.go, pkg/docker/config/config_unsupported.go, signature/mechanism_gpgme.go, signature/mechanism_gpgme_test.go, signature/mechanism_openpgp.go, signature/mechanism_openpgp_test.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_reference_test.go, storage/storage_test.go, storage/storage_transport.go, storage/storage_transport_test.go, transports/alltransports/docker_daemon.go, transports/alltransports/docker_daemon_stub.go, transports/alltransports/ostree.go, transports/alltransports/ostree_stub.go, transports/alltransports/storage.go, transports/alltransports/storage_stub.go
Go 1.17 introduces a much more reasonable build constraint format, and `gofmt` now fails without using it.
Sadly we still need the old format _as well_, to support <1.17 builds.
=> Run (gofmt -s -w)

directory/directory_dest.go, directory/directory_test.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, docker/tarfile/dest.go, image/docker_schema2_test.go, internal/putblobdigest/put_blob_digest.go, internal/putblobdigest/put_blob_digest_test.go, oci/archive/oci_dest.go, oci/layout/oci_dest.go, openshift/openshift.go, ostree/ostree_dest.go, storage/storage_image.go, types/types.go
Document that `PutBlob` callers must only provide validated digests. This was always sort of implied, and we now rely on that explicitly to avoid computing the digests; it turns out the digest computation can consume a very noticeable amount of CPU time.
Then Introduce `internal/putblobdigest.Digester` and use it to let `PutBlob` use caller-provided digest values, if any.
Fixes #1160 (the last part).
=> Only compute digests in PutBlob if truly necessary

go.mod, go.sum, storage/storage_image.go
... so that it doesn't need to compute them again.
Fixes #1160 (the second part).
<s>Completely untested at this point.</s>
Depends on merged but unreleased https://github.com/containers/storage/pull/1003 .
=> Pass OriginalDigest and UncompressedDigest to c/storage.Store.PutLayer

go.mod, go.sum
The v7.1.1 we refer to has been untagged(?), which broke Dependabot.
=> Update github.com/vbauerster/mpb/v7 to v7.1.3 manually

go.mod, go.sum
`go get github.com/containerd/containerd@v1.5.4`
@vrothberg @mtrmac @rhatdan PTAL
=> bump containerd to v1.5.4

version/version.go
The v5.16.0 release has been triggering the https://github.com/vbauerster/mpb/issues/100 hang, causing unaware users who just update c/image (in particular CRI-O today) to encounter these hangs.
So, tag a new version where we depend on a newer MPB, to avoid breaking any other users.
=> Tag v5.16.1

pkg/docker/config/config.go
If the file based credentials helper is being used, then it would be
useful for debugging scenarios if we know the location of the file where
the credentials have been found.
We now debug log this location in case it is available.
cc @QiWang19 @mrunalp
=> Log credentials helper path if available

doc.go
=> Add simple documentation how to use c/image with podman's rootless mode

docker/docker_image_src.go, oci/layout/oci_src.go
Fixes https://github.com/containers/podman/issues/12231
Currently, c/image cannot pull OCI images that contain non-`http(s)://` urls.
This commit fixes this issue by allowing fallback when pull fails on non-`http(s)://` urls.
=> Fix c/image fails to pull OCI image with non-`http(s)://` urls

manifest/common.go, manifest/common_test.go, manifest/docker_schema1.go, manifest/docker_schema1_test.go, manifest/docker_schema2.go, manifest/docker_schema2_list.go, manifest/docker_schema2_list_test.go, manifest/docker_schema2_test.go, manifest/oci.go, manifest/oci_index.go, manifest/oci_index_test.go, manifest/oci_test.go
Refuse to process manifest / manifest list data that could possibly be interpreted as two different manifest formats, because differences in how those ambiguities are resolved could be used to bypass image verification or review mechanisms.
Fixes CVE-2021-41190 / GHSA-77vh-xpmg-72qh .
=> Reject ambiguous manifest formats

copy/copy.go, copy/manifest.go, copy/manifest_test.go
A digest-stable copy seems popular, even when not copying signed images.
Using --all can still change digests. Adding an option to ensure digests
are preserved.
Will follow up with a skopeo PR if/when this is merged to use it.
See:
https://github.com/containers/skopeo/issues/1440
https://github.com/containers/skopeo/issues/1378
https://github.com/containers/skopeo/issues/1102
https://github.com/containers/skopeo/issues/1451
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
=> Add option to preserve digests

pkg/shortnames/shortnames.go, pkg/shortnames/shortnames_test.go, types/types.go
Podman's Docker-compatible REST API is in need of a mechanism to enforce
resolving to Docker Hub only.  Yet there is the desire for the rest of
the stack to continue honoring the system's registries.conf.
We recently added a new field to containers.conf [1] which allows for
opting out from enforcing Docker Hub for Podman's compat API but we
still lack a way of enforcement when resolving short names; which
ultimately is *the* place to do that.
This change does the necessary plumbing.  The compat REST handlers will
set the new field in the `types.SystemContext` and pass that down to
libimage and buildah.
[1] https://github.com/containers/common/commit/e698b8caca9413a437a3d5ade87d690ba0969f22
Context: containers/podman/issues/12320
=> shortnames: mechanism to enforce resolving to Docker Hub

copy/copy.go
Per https://github.com/containers/image/pull/1413#discussion_r758159747 .
=> Link the two variants of cannotModifyManifest*Reason together.

go.mod, go.sum, image/fixtures/oci1-all-media-types.json, image/fixtures/oci1.json, image/fixtures/schema1-to-oci1.json, image/fixtures/schema2-all-media-types-to-oci1.json, image/fixtures/schema2-to-oci1.json, manifest/fixtures/ociv1.image.index.json, manifest/fixtures/ociv1.nondistributable.gzip.manifest.json, manifest/fixtures/ociv1.nondistributable.manifest.json, manifest/fixtures/ociv1.nondistributable.zstd.manifest.json, manifest/fixtures/ociv1.uncompressed.manifest.json, manifest/fixtures/ociv1.zstd.manifest.json, manifest/fixtures/ociv1nomime.artifact.json, manifest/fixtures/ociv1nomime.image.index.json, manifest/fixtures/ociv1nomime.manifest.json, manifest/manifest.go, manifest/manifest_test.go, manifest/oci.go, manifest/oci_index.go
Newer versions of the OCI spec include the mediaType field in image manifests and image indexes, and if they include them, save ourselves some work by using that information.
=> manifest.GuessMIMEType(): recognize self-described OCI manifests

go.mod, go.sum
just to keep various dependency checkers happy.
> go get github.com/containerd/containerd@v1.5.8
NOTE: This is NOT a fix for CVE-2021-41190 / GHSA-77vh-xpmg-72qh , that was fixed in containers/image v5.17.0 .
=> Update github.com/containerd/containerd to v1.5.8

pkg/docker/config/config.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/config.json, pkg/docker/config/testdata/docker-credential-helper-registry
A credential helper may not have the credentials we are looking for and
exits with 1 (and specific error).  Make sure we're treating this case
correctly and don't error but return empty credentials.
Fixes: containers/podman/issues/11636
@rhatdan @giuseppe @umohnani8 PTAL
=> docker/config: handle credentials not found errors

copy/copy.go
Use a new function available in MPB 7.3.0, and avoid passing around unnecessary data.
This could probably go further in unifying the three cases, e.g. the partial pull case could probably still use `decor.CountersKibiByte`; this is limited to purely mechanical refactoring.
Cc: @giuseppe in cause there’s a subtlety I am missing.
=> Simplify partial pull progress code

docker/docker_client.go
Noticed this during the current AWS outage...
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
=> docker: less bears :(

pkg/docker/config/config.go, pkg/docker/config/config_test.go
- Don't check for `credentials.IsErrCredentialsNotFoundMessage`, which is handled by `GetCredentials` and is not reachable here
- Do check for an empty struct, which is the outcome of that handling. Don't add that empty struct, meaning "nothing found", to the returned data.
- A somewhat-related cleanup.
This is a follow-up to https://github.com/containers/image/pull/1427#issuecomment-991109516 .
=> Fix handling of missing data in GetAllCredentials

go.mod, go.sum
```
go get github.com/containerd/containerd@latest
```
... because 1.5.9 contains a vulnerability fix, and we want to silence scanners.
NOTE: c/image DOES NOT use the vulnerable code that was fixed in containerd 1.5.9, so it is NOT vulnerable to GHSA-mvff-h3cj-wj9c .
---
This PR also updates opencontainers/image-spec to fix using c/image along with other Go modules that reference the 1.0.2 release tag, like https://github.com/containers/buildah/pull/3678 (that includes this containerd update).
=> Update github.com/containerd/containerd to 1.5.9

go.mod, go.sum, signature/mechanism.go, signature/mechanism_openpgp.go
This is a fallback code; the primary recommendation is to use the gpgme mechanism implementation, which is out-of-process and more appropriate for handling long-term private key material than any Go implementation.
For this verify-only fallback, we haven't reviewed any of the existing alternatives to choose; so, for now, continue to use this frozen deprecated implementation.
=> RFC: Update golang.org/x/crypto, and silence warnings about openpgp

version/version.go
=> Release c/image v5.18.0

docs/containers-auth.json.5.md
According to [documentation](https://docs.podman.io/en/latest/markdown/podman.1.html?highlight=XDG_CONFIG_HOME#xdg-config-home), the default value for `XDG_CONFIG_HOME` is `$HOME/.config/containers`.
Hence, `${XDG_CONFIG_HOME}/containers/auth.json` would be expanded to `$HOME/.config/containers/containers/auth.json`, which is clearly one `containers` too many. I changed that.
I also removed some obsolete backslashes in the variable name.
=> Corrects wrong default path for auth.json in docs

pkg/docker/config/config.go
... to make it easier for users to diagnose situations where no credentials are found.
=> Log every credential path we consult

go.mod, go.sum
Manually audit and update some of the direct dependencies.
For the most part, Dependabot is sufficient.
- Update some old no-module dependencies, or dependencies without tagged releases
- Ignore indirect dependencies (github.com/gorilla/mux
- Ignore the constant golang.org/x/… treadmill, except for x/term, which hasn’t been updated for some time.
For the most part this is cosmetic, without any behavior changes expected.
=> Update some of the more obscure dependencies

copy/copy.go, copy/progress_reader.go, copy/sign_test.go, docker/docker_image_src.go, docker/docker_image_src_test.go, internal/imagedestination/wrapper.go, internal/imagesource/wrapper.go, internal/private/private.go, storage/storage_image.go, storage/storage_test.go
Another part of the #1439 concept.
- Add `private.ImageSource`, similar to the existing `private.ImageDestination`.
- Introduce `internal/imagesource.FromPublic` and `internal/imagedestination.FromPublic`; the copy pipeline can now always use the private API without cluttering the code with compatibility paths.
- Replace the use of optional `ImageSourceSeekable` and `PutBlobPartial` interfaces with mandatory methods on the private interfaces, along with "Supports…” methods. For now, this is more wordy and risks inconsistency between the supports flags and actual implementations, but we’ll eventually make it cleaner and type-safe again, by providing mix-ins (so that a transport that doesn’t support a feature, or does support a feature, needs just to add a mix-in).
See individual commit …
=> Wrap public transport implementations to consistently use a private API

copy/copy.go, copy/progress_reader.go
Have `imageSourceSeekableProxy` directly update the progress bar, instead of sending the data to a channel and updating the progress bar in a separate goroutine.
In theory, this might slow down `GetBlobAt` a bit, because it will block on a progress bar update (but not on a repaint IIRC). We already pay the same price for `bar.ProxyReader()` on ordinary copies, so it's almost certainly not worth worrying about, and worth the simplification.
=> Eliminate a goroutine

pkg/blobcache/blobcache.go, pkg/blobcache/blobcache_test.go
Buildah's blobcache is a cache to speed up builds by avoiding CPU
intensive (de)compressing of blobs.
Move the code from Buildah into containers/image to allow for extending
internal interfaces (e.g., image destination/source) *and* supporting
newly added features in the blobcache.
There are a number of planned features (e.g., sigstore/cosign) which
will likely be implemented entirely by extending the internal interfaces
and by casting to internal types in containers/image/copy as already
done.  Having Buildah's blobcache here allows for extending its internal
interface more easily.
@mtrmac @nalind PTAL
Once merged, I can prepare a follow-up PR in Buildah and do the aliasing.
=> add pkg/blobcache from Buildah

storage/storage_image.go
Another part of #1439 : modify `storageImageDestination` so that `PutBlob` is just a trivial wrapper over `PutBlobWithOptions`, and `TryReusingBlob` is just a trivial wrapper over `TryReusingBlobWithOptions`.
Later we’ll replace those wrappers with uses of universally-usable adapters.
=> Reorganize storageImageDestination to prioritize the private …WithOptions methods

pkg/blobcache/blobcache.go, pkg/blobcache/blobcache_test.go
To allow for callers of Buildah's pkg/blobcache to continue building [1].
[1] https://github.com/containers/buildah/pull/3795#issuecomment-1047873727
=> blobcache: export clearCache

docker/reference/regexp-additions.go, docker/reference/regexp_test.go
containers/common/libimage is in need to check whether a given input
looks like a full image ID (i.e., a 64-byte hex string).  Since
compiling regexes has a negative impact on init- and run-time, let's
expose a function to check whether a given string matches the already
compiled regex in docker/reference.
@mtrmac PTAL
I want it for optimizing the fixes for https://github.com/containers/podman/issues/12761.
=> docker/reference: add IsFullIdentifier

go.mod
After https://github.com/containers/image/pull/1477 has removed the last direct user of the package, update also the dependency.
Don't completely remove it so that updating c/image can't cause a downgrade of `golang.org/x/sys` in consumers;
eventually some dependency will start requiring a newer version of `golang.org/x/sys` and the entry will completely
drop out (or we eventually update to the newer `go.mod` format that lists indirect dependencies as well).
=> Remove a direct dependency on golang.org/x/sys

oci/layout/oci_dest.go
This PR follows up the discussion in #1466.
I did another round of practical tests with Skopeo 1.6.1 built on top of this change.
I was able to successfully copy to OCI layout format the following images: 
| Image reference                                                        | Number of blobs | Size on registry |
|------------------------------------------------------------------------|-----------------|------------------|
| `quay.io/madeeks/pyfr:1.10.0-cuda11.2-openmpi4.1.0-ubuntu20.04`          |        18       |       2.3GB      |
| `quay.io/madeeks/horovod:0.22.0-tf2.5.0-cuda11.2-mpich3.1.4-ubuntu18.04` |        23       |       4.1GB      |
| `quay.io/madeeks/gromacs:2020.4-cuda11.2.0-mpich3.1.4-centos7`           |        15       |       2.3GB      |
| …
=> Change OCI layout transport to thread-safe destination

version/version.go
- `docker/referece`: add `IsFullIdentifier`
- Changed oci layout transport to thread-safe destination
- add `pkg/blobcache` from Buildah
- blobcache: drop import on `buildah/docker`
- blobcache: drop history comment
- blobcache: make `ClearCache()` private
- blobcache: remove `CacheLookupReferenceFunc`
- blobcache: turn `BlobCache` into a struct
- blobcache: export `clearCache`
- Remove (unused and unreachable) keyring support
- Eliminate a goroutine
- Also introduces internal-only interfaces to allow extending the transport feature set in the future
=> Release v5.20.0

go.mod, go.sum, storage/storage_image.go
Commits from parallel builds using `SetNames` removes `names` from
storage for other builds.
Use race-free atomic `AddNames` to prevent breaking of parallel builds.
Uses `c/storage` from PR: https://github.com/containers/storage/pull/1153
Fixes issue: 
**Builds fail with image not known.**
```console
#!/bin/bash
x=1
sudo ./podman rmi -af
rm -f log*.*
sudo ./podman build -t first . &> logfirst.log
while [ $x -le 30 ]
do
echo "$x times"
sudo ./podman build --log-level debug -t $x . &> log$x.log &
x=$(( $x + 1 ))
done
```
```console
FROM quay.io/jitesoft/alpine
```
PS: I am not sure how to ensure parallel builds in CI and produce a race so not sure how to test this in CI.
=> storage: use race-free `AddNames` instead of `SetNames`

signature/mechanism.go, signature/mechanism_openpgp.go
We already silence the CI linters, this silences warnings in the Visual Studio Code default configuration.
=> Silence go-staticcheck about openpgp use

Makefile, pkg/tlsclientconfig/tlsclientconfig_test.go
This is an attempt to fix (make lint), which complains:
```
pkg/tlsclientconfig/tlsclientconfig_test.go:37:20: SA1019: tlsc.RootCAs.Subjects is deprecated: if s was returned by SystemCertPool, Subjects will not include the system roots. (staticcheck)
for _, s := range tlsc.RootCAs.Subjects() {
^
pkg/tlsclientconfig/tlsclientconfig_test.go:43:20: SA1019: systemCertPool.Subjects is deprecated: if s was returned by SystemCertPool, Subjects will not include the system roots. (staticcheck)
for _, s := range systemCertPool.Subjects() {
^
pkg/tlsclientconfig/tlsclientconfig_test.go:53:20: SA1019: tlsc.RootCAs.Subjects is deprecated: if s was returned by SystemCertPool, Subjects will not include the system roots. (staticcheck)
for _, s := range tlsc.RootCAs.Subjects() {
```
... but the same …
=> Try to make (make lint) pass with Go 1.18

directory/directory_test.go, docker/daemon/client_test.go, docker/lookaside_test.go, manifest/common_test.go, oci/layout/oci_dest_test.go, oci/layout/oci_transport_test.go, pkg/docker/config/config_test.go, pkg/sysregistriesv2/system_registries_v2_test.go, signature/docker_test.go
...added in github.com/stretchr/testify 1.7.1.
=> Use assert.ErrorContains

docs/containers-registries.conf.5.md
Mention that wildcarded prefixes match an arbitrary number of
subdomains.
Closes: #1397
@mtrmac @rhatdan PTAL
=> registries.conf: prefixes: subdomain matching

docs/containers-registries.conf.5.md
The dot in a `*.` prefix is mandatory.
=> registries.conf: fix typo in prefix

docs/containers-registries.conf.5.md, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go, pkg/sysregistriesv2/testdata/invalid-config-level-mirror.conf, pkg/sysregistriesv2/testdata/invalid-conflict-mirror.conf, pkg/sysregistriesv2/testdata/invalid-value-mirror.conf, pkg/sysregistriesv2/testdata/pull-sources-mirror-reference.conf
Close: https://github.com/containers/image/issues/1407
Add pull-from-mirror: all, digest-only, tag-only for adding per-mirror level restrictions
The `mirror-by-digest-only` for primary is still allowed configuring,
and it is honored for compatibility
=> Add pull-from-mirror for adding per-mirror level restrictions

version/version.go
Mirrors defined in `registries.conf` can now be restricted for tag/digest references only, using the new `pull-from-mirror` option.
New option `copy.Options.SignIdentity`.
The library now formally requires Go 1.15 (which was, in practice, already the case).
- vendor: bump c/storage to main/d06b0f8
- storage: use race-free AddNames instead of SetNames
- build(deps): bump github.com/klauspost/compress from 1.14.4 to 1.15.0
- Update github.com/containerd/containerd
- build(deps): bump github.com/docker/distribution
- build(deps): bump github.com/sylabs/sif/v2 from 2.3.2 to 2.4.0
- build(deps): bump github.com/docker/docker
- build(deps): bump github.com/klauspost/compress from 1.15.0 to 1.15.1
- Silence go-staticcheck about openpgp use
- Try to make (make lint) pass with Go 1.18
- …
=> Release v5.21.0

pkg/docker/config/config.go
... so that users can't observe an intermediate empty, or partial, file.
(Note that there is still no locking, so two simultaneous updates to `auth.json` might lose some updates.)
Fixes at least the worst impact of https://github.com/containers/image/issues/1365 .
=> Use c/storage/pkg/ioutils.AtomicWriteFiles to update auth.json

docs/containers-registries.conf.5.md
Clarify that a `[[registry.mirror]]` is associated only with the
previous `[[registry]]`.
Fixes: #1523
=> man containers-registries.conf: clarify mirror association

docker/docker_client.go, docker/internal/tarfile/src_test.go, storage/storage_test.go
Just a micro-optimization: avoid maintaining state for a read/write buffer, and the allocation inherent in a `string` → `[]byte` conversion.
=> Use strings.NewReader instead of bytes.NewBufferString

docs/containers-registries.conf.5.md
Four leading spaces are interpreted by go-md2man as a code block.
Add a new line to start a new paragraph, so that go-md2man recognizes the list syntax.
=> Use correct list syntax in containers-registries.conf(5)

docker/docker_image_src.go
Per https://github.com/containers/image/issues/1010 , it seems the header is not populated by AWS ECR.
We were actually computing the digest from the manifest bytes already, so this is both more robust and simpler.
<s>WIP: Untested manually (there is a system test for `skopeo delete` that will exercise this), and we should get a confirmation that this fixes #1010 .</s>
=> Don't require a Docker-Content-Digest header when deleting images

.cirrus.yml, contrib/cirrus/runner.sh
Ref: https://github.com/containers/automation_images/pull/115
=> Cirrus: Update to F36 VMs

go.mod, go.sum
The two latest commits in c/ocicrypt get rid of OAEPDefaultHash envvar
and default to sha256.
They are waiting for confirmation on their rust side before cutting a
release. So, hoping to get this in assuming dependabot could take a
while.
@mtrmac @vrothberg @rhatdan PTAL.
=> Bump github.com/containers/ocicrypt to 566b808

copy/copy.go
Per https://github.com/containers/image/pull/1314 :
Operations that involve encryption/decryption are already restricted e.g. not to use `TryReusingBlob`; but operations that don't themselves involve encryption could still find encrypted blobs in the blob info cache, and potentially use them in other contexts.
To avoid that, use a somewhat big hammer of just not calling `RecordDigestUncompressedPair` on that.  Note that this does not help if the blob info cache has already added such entries before this change; it only makes a difference for the future.
We continue to call `RecordKnownLocation` with encrypted data; simple copies of encrypted images from one registry to another (which don't encrypt/decrypt as part of the copy) can benefit from e.g. cross-repo blob reuse just fine.
It seems …
=> Fix unwanted reuse of encrypted layers

Makefile
The Skopeo branch to test against is now driven by `SKOPEO_CI_TAG` in `.cirrus.yml`, these are not used by anything.
=> Remove unused Makefile variables

go.mod, go.sum
The two latest commits in c/ocicrypt get rid of OAEPDefaultHash envvar
and default to sha256.
They are waiting for confirmation on their rust side before cutting a
release. So, hoping to get this in assuming dependabot could take a
while.
@vrothberg @mtrmac @rhatdan PTAL. This is for subsequent vendoring into podman v4.0-rhel branch.
RE: https://github.com/containers/podman/pull/14102#issuecomment-1117204950
=> [release-5.19 backport] Bump github.com/containers/ocicrypt to 566b808

version/version.go
As the title says.
@mtrmac @flouthoc @rhatdan PTAL
This includes an ocicrypt library bump and we need to get this c/image later vendored into podman / buildah rhel support branches.
=> Release 5.19.3 bump

docker/docker_client.go, docker/lookaside.go, docker/paths_common.go, docker/paths_freebsd.go, pkg/sysregistriesv2/paths_common.go, pkg/sysregistriesv2/paths_freebsd.go, pkg/sysregistriesv2/system_registries_v2.go, signature/policy_config.go, signature/policy_paths_common.go, signature/policy_paths_freebsd.go
Signed-off-by: Doug Rabson <dfr@rabson.org>
=> Config files should live in /usr/local on FreeBSD

Makefile
If both GOBIN and GOPATH aren't set in the system environment then the
makefile will attempt to install to /bin. go env uses a sensible default
of $HOME/go if GOPATH isn't set.
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
=> Use go env to fetch the go path

docker/docker_image_src.go, docker/docker_image_src_test.go
CloudFront returns an unquoted ':' in the boundary, special handle it.
It is needed for partial pulls from quay.io.
=> docker: add workaround for CloudFront

copy/copy.go, image/docker_list.go, image/oci_index.go
When using an image index (manifest list/fat manifest) from a registry,
but the specific image is missing from the registry, be more clear about
the error.
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
=> Improve errors messages when image missing from list

Makefile
As of the just-updated `github.com/proglottis/gpgme` 0.1.2, the `gpgme` subpackage uses CGo’s native `#cgo pkg-config` support to find the relevant libraries, and we no longer need to manually set `CGO_CFLAGS` and `CGO_LDFLAGS`. So stop doing that.
Note that the `proglottis/gpgme` update (already before this commit) means the minimal supported version of GPGME is 1.13.0.
=> Stop calling gpgme-config

go.mod, go.sum
... to silence Dependabot alerts about CVE-2022-29162 = GHSA-f3fp-gc8g-vw66.
Note that nothing in c/image actually calls this package, so the vulnerability could only be triggered by some other code path.
=> Make sure github.com/opencontainers/runc >= 1.1.2 is used

copy/sign_test.go, docker/docker_client.go, go.mod, openshift/openshift-copies_test.go, pkg/blobinfocache/default_test.go, pkg/docker/config/config_test.go, signature/mechanism_test.go
Per https://github.com/containers/image/pull/1570#issuecomment-1149876963 , Go 1.17 will be required; so, update c/image to benefit from it.
=> Update to benefit from Go 1.17

copy/copy.go, copy/manifest.go, copy/manifest_test.go, internal/image/sourced.go
Another part of #1574 (but note that this approach is rather different from an earlier version):
Use an `internal/image.SourcedImage` directly instead of a `types.Image` interface for most of c/image/copy. The implementation/tests of `copy.determineManifestConversion` currently mock the `types.Image` interface; instead, turn `determineManifestConversion` into a ~pure function, with all inputs and outputs as fields in a struct.
Also add the first benefit of using the non-public `SourcedImage`: access the manifest and manifest’s MIME type directly without having to worry about (impossible) failures.
Should not change behavior overall. See individual commit messages for details.
=> Use a SourcedImage struct in c/image/copy

storage/storage_image.go
Fixes https://github.com/containers/storage/issues/1263
Multiple parallel pullings of an image with additionallayerstore can occur the
following error:
```
Error: copying system image from manifest list: trying to reuse blob sha256:93ef9da9c5f3db2ac7fd52cab0e63c7e6fc9a722aec43d1b936a130e979ab8e8 at destination: failed to put layer from digest and labels: that ID is already in use
```
This commit fixes this issue by ignoring `ErrDuplicateID`. When the same layer
ID already exists in the storage, we can just reuse it instead of returning the
error. This is the same behaviour as when c/image uses `PutLayer`.
=> Fix error on parallel multiple image pullings with additionallayerstore

copy/blob.go, copy/compression.go, copy/copy.go, internal/image/docker_schema1.go, internal/image/docker_schema1_test.go, internal/image/docker_schema2.go, internal/image/docker_schema2_test.go, internal/image/fixtures/oci1-artifact.json, internal/image/manifest.go, internal/image/oci.go, internal/image/oci_test.go, internal/manifest/errors.go, manifest/common.go, manifest/docker_schema1_test.go, manifest/docker_schema2.go, manifest/docker_schema2_test.go, manifest/manifest.go, manifest/oci.go, manifest/oci_test.go
This broadly follows the plan from https://github.com/containers/image/pull/1408#issuecomment-1029487477 :
- Reject image-specific operations (like inspect, image ID) on OCI artifacts
- Don’t change compression of artifact layers
- FIXME: Should we also reject encryption/decryption operations?
See the individual commits for details.
FIXME: At this point I’m rather unhappy about the `CanChangeLayerCompression` API. It’s good enough for internal use for now, exposing it in `c/image/manifest` is not great. OTOH I’d rather not spend time investigating the more general which-image-formats-can-support-which-compression-and-what-to-do-if-they-don’t problem space.
At this point absolutely untested apart from unit tests (which don’t cover most of the `copy` code); this will be the first run …
=> Support OCI artifacts

docker/docker_image_src_test.go, ostree/ostree_transport_test.go, storage/storage_test.go
... for a trivial improvement in readability.
Should not change behavior.
=> Use strings.ReplaceAll instead of strings.Replace(..., -1)

directory/directory_dest.go, directory/directory_test.go, docker/archive/dest.go, docker/archive/dest_test.go, docker/daemon/daemon_dest.go, docker/daemon/daemon_dest_test.go, docker/docker_image_dest.go, docker/docker_image_dest_test.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/src_test.go, docker/tarfile/dest.go, internal/imagedestination/impl/compat.go, internal/imagedestination/impl/properties.go, internal/imagedestination/stubs/put_blob_partial.go, internal/imagedestination/stubs/signatures.go, internal/imagedestination/stubs/stubs.go, internal/imagedestination/wrapper.go, internal/private/private.go, oci/archive/oci_dest.go, oci/archive/oci_dest_test.go, oci/layout/oci_dest.go, oci/layout/oci_dest_test.go, openshift/openshift.go, openshift/openshift_test.go, ostree/ostree_dest.go, ostree/ostree_dest_test.go, storage/storage_image.go
This is a superset of the remaining part of #1439.
- Most importantly, have all transports implement `private.ImageDestination`, leaving the task of compatibility with public `types.ImageDestination` to an `internal/imagedestination/impl.Compat` helper. All transports will now think purely in terms of the private interface.
- `BlobInfoCache` is not yet included: that needs to happen, but that will be a later PR (notably because it needs to deal with forwarding between private and public-only users).
- Try to significantly reduce copy&pasted boilerplate in transports. This doesn’t change the provided interface, just the code.
- Instead of a bunch of methods that just return a single value, consolidate them into `imagedestination/impl.Properties`, and let the transport just provide the …
=> Implement private.ImageDestination in all transports, improve transport helpers

pkg/blobcache/blobcache.go, pkg/blobcache/blobcache_test.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, pkg/blobcache/src_test.go
… so that we can extend the signature representation (and possibly add other features), which is why we moved `pkgblobcache` to c/image in the first place.
See individual commits for details.
=> Implement private.ImageSource / ImageDestination in blobcache

ostree/ostree_src.go
Fixes FTBFS with go 1.18.3
Fixes: "Update users of deprecated io/ioutil" 7152f888
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>
=> Use "io.ReadAll" instead of "os.ReadAll"

internal/image/docker_schema2_test.go, internal/image/oci_test.go
`configBlobImageSource.f` is only called if the digest is exactly one value, so the function doesn't need to use it (and none of them do).  So, remove it; this also drops a recently-introduced warning in VS Code.
Should not change (test) behavior.
=> Silence a "potentially unused parameter" warning

copy/copy.go, copy/sign.go
Consolidate figuring out which signatures from the source to copy, and whether that can work, into a helper.
@vrothberg RFC — I’m honestly _rather_ unhappy about passing the progress messages into the helper (and, at the same time, unwilling to make the messages less descriptive just to share a few lines of code); basically just to show that something like this is possible, and solicit better ideas.
At this point I’d really prefer only the first commit to be merged.
=> RFC: Consolidate getting signatures

go.mod, go.sum
… both direct and indirect.
This is a random pass through primarily because GitHub’s Dependabot doesn’t update from commit references to later releases, and also to possibly compensate for direct dependencies that depend on other packages but don’t check for updates.
A few commit dependencies that are already just a month or two old were left alone; those much older than that were updated.
(I don’t think it makes sense to commit to keeping all commit references updated — some projects apparently do do that using (some version of?) Dependabot, but that’s a _lot_ of noise for repos like `golang.org/x/…` that never make releases. A manual pass from time to time seems a reasonable compromise to me.)
=> Manually update various old dependencies

.cirrus.yml, Makefile
**Depends on**: https://github.com/containers/skopeo/pull/1711
Note: Removed disused `PRIOR_FEDORA*` and `UBUNTU_*` references since
they're not actually used in this CI.  Further, F35 VM images were not
built as part of `c6013173500215296` due to a missing golang 1.18
requirement for podman.
=> Cirrus: Update CI VM images

doc.go, docker/daemon/daemon_transport.go, docker/reference/reference.go, internal/imagedestination/impl/compat.go, internal/imagedestination/stubs/stubs.go, internal/imagesource/impl/compat.go, internal/imagesource/stubs/stubs.go, openshift/openshift-copies.go, pkg/blobcache/src_test.go, pkg/shortnames/shortnames.go, sif/transport_test.go, signature/policy_eval.go, tarball/doc.go, types/types.go
This is primarily `gofmt` updates (the minimal version, not a full review to benefit from the new syntax).
=> Fix building with Go 1.19

copy/sign_test.go
… instead of the external dependency, which snuck in by IDE autocomplete.
=> Use c/image's reference package

internal/image/docker_schema1_test.go, internal/image/docker_schema2_test.go, internal/image/oci_test.go, manifest/common.go, manifest/docker_schema1.go, manifest/docker_schema2.go, manifest/oci.go, types/types.go
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
=> enhance inspect

docker/archive/dest.go, docker/archive/transport.go, docker/archive/writer.go
Per https://github.com/containers/skopeo/issues/1708 ,  `skopeo copy --retry-times 3 docker://… docker-archive:…` cannot retry because the first failing copy creates a partial archive, and the subsequent retry refuses to modify it (we only support creating archives from scratch).
So, if we are creating a regular file, and we have not _successfully_ written at least one image, delete the destination file.
_Note:_ If the destination already exists as a zero-sized file, this deletes it. That’s a weird corner case — right now we always open the destination with `O_CREATE`, and just use that file whether it is a pipe or a regular file. Conceptually, we could do the check for non-regular files and non-empty destinations separately, and then use a temporary file + `Rename()` on success if the …
=> Delete partial docker-archive files, to allow retries

docs/containers-transports.5.md
When using remote podman client, not all transports work as expected. So
document this limitation.
Fixes: containers/podman#15141
Signed-off-by: Tomas Volf <tomas.volf@showmax.com>
=> Document limitations of transports for remote podman client

docker/docker_client.go, docker/docker_client_test.go, docker/docker_image_dest.go, docker/wwwauthenticate.go
This is a rebase of https://github.com/containers/image/pull/1079 and fixes https://github.com/containers/image/issues/1478
=> docker_client: Handle "invalid_scope" errors

docker/wwwauthenticate.go
Also start with the function name, as linters prefer.
=> Update comment to conform to Go 1.19 formatting

docker/distribution_error.go, docker/distribution_error_test.go, docker/docker_client.go, docker/errors.go, docker/errors_test.go, go.mod, go.sum
Using the github.com/docker/distribution/registry/client package will
import many huge prometheus dependencies, e.g.
* github.com/prometheus/client_golang/prometheus/promhttp
* github.com/prometheus/client_golang/prometheus
* github.com/prometheus/procfs
and even more...
All of these dependencies are completely unused AFAICT but will still end
up in a binary because they are imported transitive.
github.com/docker/distribution/registry/client is only used to check
http errors so I think it makes sense to copy only the required code
into the docker package.
I vendored this commit into podman and it saves over 700KB in binary
size.
=> Remove github.com/docker/distribution/registry/client package

.github/renovate.json5
Updating dependencies is important, make PRs standout from the crowd so humans can spot (or search for) them easily.
Also added a comment to help future maintainers.
=> [skip-ci] Renovate: Label renovate PRs & use preset

oci/archive/oci_src.go, oci/layout/oci_src.go, oci/layout/oci_transport.go
… for https://github.com/containers/skopeo/pull/1757 .
Warning: Absolutely untested.
=> Introduce oci/{archive,layout}.ImageNotFoundError

docker/docker_client.go, docker/docker_client_test.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/errors.go, docker/errors_test.go
See https://github.com/containers/image/issues/1293#issuecomment-875791392 and the added comment.
The primary expected benefit is that this should turn
```
Error initializing source docker://foobar:latest: Error reading manifest latest in docker.io/library/foobar: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```
into
```
Error initializing source docker://foobar:latest: Error reading manifest latest in docker.io/library/foobar: denied: requested access to the resource is denied
```
⚠️ 
- <s>Currently absolutely untested. We should see what this changes in practice for a variety of registries and situations.</s>
- <s>This could potentially _silently_ break callers; notably https://github.com/containers/common/blob/a38eda676e2adea08a5138aa6 …
=> Improve registry client error handling

directory/directory_dest.go
Just like #1481 did for OCI Layout Destination, this patch marks Directory Transport Destination as thread-safe. The `PutBlobWithOptions` implementation of both transports are almost identical, differing only on the path where the blob will be stored.
```diff
- 	blobPath := d.ref.layerPath(blobDigest)
+ 	blobPath, err := d.ref.blobPath(blobDigest, d.sharedBlobDir)
+	if err != nil {
+		return types.BlobInfo{}, err
+	}
+	if err := ensureParentDirectoryExists(blobPath); err != nil {
+		return types.BlobInfo{}, err
+	}
```
=> Set Directory Transport Destination as Thread-Safe

docker/docker_client.go, docker/docker_client_test.go, docker/errors_test.go
... when checking for missing images.
In particular, this is necessary for `use-sigstore-attachments` not to cause failures when pulling from registry.redhat.io.
Red Hat internal reference: RITM1310318
=> Recognize invalid error responses of registry.redhat.io

docker/docker_image_dest.go
... to placate quay.io's validation.
=> Make the pseudo-config used in sigstore attachments a bit more valid

.github/renovate.json5
Discovered the golang-version update behavior is recent and up for some debate.  Reference open issue on the topic in case the config. needs to be corrected in the future due to a fix.
=> [CI:DOCS] Update renovate config. comment

.github/renovate.json5
This saves having to repeat the same options over and over in every
repo.
Ref: https://github.com/containers/automation/commit/56579d17501230b1b9a230c903fe6acf18872033
=> [CI:DOCS] Move boiler-plate golang config to automation repo

.cirrus.yml, Makefile, docker/docker_client.go, docker/docker_client_test.go, docker/docker_image_dest.go, docker/errors.go, version/version.go
<s>WIP, untested at this point.</s>
=> 5.22 backports

.cirrus.yml, docker/docker_client.go, docker/docker_client_test.go, docker/docker_image_dest.go, docker/errors.go
This corresponds to #1695, just to be sure there won’t be a regression.
=> [release-5.23] 5.23 backports

docker/daemon/client.go, docker/docker_client.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/fixtures/registries.d/internal-example.com.yaml, docker/registries_d.go, docker/registries_d_test.go, openshift/openshift.go
… because we shadow the `net/url` package by a `url` local variable. To be extra sure, rename all `url` variables.
Fixes https://github.com/containers/podman/issues/16301 .
=> Fix a panic on scheme-less lookaside base

copy/compression.go, directory/explicitfilepath/path_test.go, docker/archive/writer.go, docker/docker_image_dest.go, internal/imagesource/stubs/stubs.go, oci/layout/oci_src.go, oci/layout/oci_transport.go, pkg/blobcache/src.go, pkg/shortnames/shortnames.go, storage/storage_test.go
_very_ selectively from `golangci-lint run --enable-all ./...`, limiting to obvious bugs or constructs that seem fairly likely to risk becoming a bug.
=> Some warning cleanups

.github/renovate.json5
The `behind-base-branch` setting means:
Renovate will rebase whenever the branch falls 1 or more
commit behind its base branch
=> Renovate: Override global no-rebase option

docker/reference/regexp.go
Improve the code such that a given raw regex string is compiled only once.
Before:
init 1341880 bytes, 11453 allocs
After:
init 485600 bytes, 4501 allocs
@mtrmac @rhatdan 
I did all changes manually (i.e., not copied over).  While it would be best to avoid the redundancy in the packages, I do not see a viable solution at the moment.  This is a smaller improvement but an improvement nonetheless.
=> docker/reference: reduce regex compilations

docker/docker_image_dest.go, docker/internal/tarfile/writer.go, oci/internal/oci_util_test.go
... as identified by one of the non-default `golangci-lint` linters.
=> Don't incorrectly report success on failure paths

storage/storage_src.go
The hard-coded 0 is defined in the API, so this works fine; this is just a readability improvement.
Should not change behavior.
=> Use io.SeekStart instead of a hard-coded 0

pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go, pkg/sysregistriesv2/testdata/mixing-v1-v2-empty.conf
We already rely on the TOML parser's behavior of setting specified arrays to `[]`, but missing arrays to `nil`; so just use it to be more strict.
This can help situations like
```toml
[registries.search]
registries = []
[registries.insecure]
registries = []
[registries.block]
registries = []
unqualified-search-registries = ["docker.io"]
[[registry]]
...
```
although only indirectly: From the TOML parser's point of view, the `unqualified-search-registries` field is `block.unqualified-search-registries` and therefore invisible to us. Conceptually, the same thing could happen with
```toml
[arbitrary-unknown]
unqualified-search-registries = ["docker.io"]
[[registry]]
...
```
and we wouldn't warn about that.
Even so, the config file author specifying even empty fields is suspect and suggests a …
=> Reject files mixing v1 and v2 registries.conf, even with empty fields

docker/docker_client.go
Clarify that exponential backoff only happens if the registry does not specify otherwise.
And in `parseRetryAfter`, do not talk about backoff at all, because that function is not involved in that.
Fixes #1565 .
=> Fix comments about exponential backoff with Retry-After

types/types.go
This is not #755, but it should help prevent the problem from spreading.
The _next_ user who needs to add an edit operation should be forced to provide a new internal edit API, and then we can add the existing fields to that API and deprecate the old fields.
=> Add comments to BlobInfo to warn against adding more edit fields

pkg/tlsclientconfig/tlsclientconfig.go
A small cleanup that should not affect behavior; see individual commit messages for details.
Motivated by https://github.com/containers/image/issues/161 .
Note that this does not change anything about the TLS configuration, or express any opinions about the HTTP configuration. Also, the dependency is still used indirectly due to other sub packages.
=> Remove go-conections uses in tlsclientconfig

docs/containers-signature.5.md
=> Clarify the semantics of the optional.creator field in simple signature payload

pkg/docker/config/config.go
This means that users setting up AuthFilePath can rely on that config file, without influences from the external environment.
OTOH it might break existing users.
Fixes #596 — but I’m not really sure we want to make this change after all these years.
=> Don't use any default path fallbacks if the user specified a path

storage/storage_src.go, storage/storage_test.go
To avoid locking the store for a large time we currently make a copy of the blob into TemporaryDirectoryForBigFiles (i.e. /var/tmp) when getting a stream to the blob. During a simple "podman run" this happens 6 time.
The time spent for this is not huge, but takes some time (seems to be just below 1msec according to strace output) and it will create io/ write pressure, and SSD wear.
This changes the code so that if the size is known and it is smaller than 8k, we just read it into memory and use a direct-from-memory reader instead.
Signed-off-by: Alexander Larsson <alexl@redhat.com>
=> storage source: Don't store small blobs on disk in GetBlob()

pkg/docker/config/config.go, pkg/docker/config/config_test.go
config: use `authPath` struct consistently
Instead of packing and unpacking it into two variables in
various places.  Prep for adding a third member of this struct
as part of https://github.com/containers/image/pull/1746
Signed-off-by: Colin Walters <walters@verbum.org>
---
config: Make parsing function a method on authFile
Just a general cleanup.
---
=> config: use `authPath` struct consistently

copy/sign_test.go, internal/testing/gpgagent/gpg_agent.go, signature/docker_test.go, signature/mechanism_gpgme_test.go
This:
- Refactors `copy/sign_test.go` to be table-driven, and cleans it up a bit more, to make it easier to update in #1776 
- Ensures we terminate `gpg-agent` processes spawned by tests (compare #224 )
Only modifies tests, should not change behavior.
=> GPG signing test improvements

pkg/blobcache/blobcache_test.go
- Use an invalid SystemContext.BlobInfoCacheDir to trigger use of blobinfocache/memory instead of blobinfocache/boltdb, thus avoiding some Fsync calls. This alone more than halves the total test time.
- Also don't repeat the test with 5 different file sizes; file contents are not _that_ much of a focus of the tests that we need to test so many variants.
On macOS, this reduces test time by 81% (measured by -count=3), from (in this particular instance) 8.8s to 1.6s per iteration.
=> Speed up pkg/blobcache tests

docs/containers-sigstore-signing-params.yaml.5.md, go.mod, pkg/cli/sigstore/params/sigstore.go, pkg/cli/sigstore/sigstore.go
This defines a new file format (`containers-sigstore-signing-params.yaml(5)`), and provides an API to integrate it into callers.
That way, `skopeo` and `podman` can add a single `--sigstore-sign-by=`_param-file_ option, instead of 9 options; and users can maintain their site-specific configuration in one file, instead of manually copy&pasting 6 options in a typical case.
The parameter file format definition is a separate package that does not drag in the Rekor and Fulcio dependency tree; only actually _using_ the file has that cost.
I’m not too happy about the “containers sigstore signing parameters” name, nor about the `sigstore/params` subpackage name; I’ll certainly welcome suggestions.
(One possibility would be to make this a “containers signing parameters file”, not …
=> Add a sigstore signing parameter file format, and CLI utility

manifest/docker_schema1.go, manifest/oci.go
When reading fields from an OCI config blob, pull the `Variant` field's value, too.  Stumbled across it while looking for something else.  Read it from a v2s1 config blob, too, even if it's almost certainly going to be empty.
=> manifest: pull Variant from an OCI config

docker/registries_d.go, go.mod, go.sum, openshift/openshift-copies.go, openshift/openshift-copies_test.go
This attempts to remove a dependency on yaml.v2 which we, sort of, control. This parallels https://github.com/containers/skopeo/pull/1885 .
At the very least this will allow removing `ghodss/yaml` from Skopeo (but not from Podman, because Podman uses this package directly). That’s at least a bit of code.
Note that the whole of c/image will continue to depend on  `yaml.v2` , via a Swagger-generated Rekor client, depending on https://github.com/go-openapi/runtime/issues/245 .
Tested, so far, only using unit tests; that suggests that the migration from `ghodss/yaml` _might_ be fairly tricky. The `openshift` case is one where we would be quite unlikely to notice breakage in practice, but it has fairly good unit tests. The `registries.d` case has worse unit tests, but simpler data types and …
=> Migrate from ghodss/yaml to gopkg.in/yaml.v3

internal/manifest/errors.go
The OCI artifact reference in the generic error message is a bit confusing, and these invalid images do tend to show up every few years.
<s>Draft: Test that at least once against `docker://docker.io/library/ubuntu@sha256:0b0aab2bb85da9e3168407368464cb15f828eda8860eefb4c74a57dea2f139c7` .</s>
=> Add a more specific error message on invalid docker-config-in-OCI-image images

copy/copy.go, copy/progress_bars.go, go.mod, go.sum
Renovate filed #1786, which isn’t sufficient; actually update the users.
I have reviewed the API for changes, but only minimally smoke-tested this in practice with a single copy.
(Note to self: Podman should migrate its users as well.)
=> Update to github.com/vbauerster/mpb/v8

.cirrus.yml
***Depends on:*** https://github.com/containers/skopeo/pull/1888
Image content hasn't changed much, the biggest thing here is the `$IMAGE_SUFFIX` value.  This new schema is also fully manageable by renovate.  Allowing a tag-push to c/automation_images to create image update PRs in all repos automatically.
Ref: https://github.com/containers/automation_images/pull/247
=> Cirrus: Use human-readable CI VM Images

docker/body_reader.go, docker/body_reader_test.go, docker/docker_client.go
Not production-ready at this point; filing this PR early to run through CI, and to generate log entries so that this can be
verified, improved and tuned.
=> Reconnecting blob reader

.github/dependabot.yml
Fixes: https://github.com/containers/image/issues/1836
Ref: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
Disabling it via the WebUI isn't good enough, the configuration file must also be absent.
=> [CI:DOCS] Disable dependabot

Makefile, docker/archive/writer.go, docker/body_reader.go, docker/docker_client.go, docker/docker_image_dest.go, docker/reference/reference.go, docs/containers-sigstore-signing-params.yaml.5.md, internal/image/sourced.go, pkg/blobcache/src.go, pkg/compression/compression.go, signature/fulcio_cert.go, signature/fulcio_cert_test.go, signature/internal/rekor_set_test.go, signature/sigstore/fulcio/fulcio.go
=> Run codespell on codebase

go.mod, openshift/openshift-copies.go
A version of `golang.org/x/net/http2` is bundled into the standard library: https://github.com/golang/go/blob/master/src/net/http/h2_bundle.go and here we certainly don't care about the specific version or details.
So just enable use of the built-in one.
Note that this is very unlikely to actually remove the dependency from binaries, because it is required by `google.golang.org/grpc/internal/transport`, and that one has quite a few uses; so most of the benefit right now is just
one less package to get dependency update PRs from.
---
Also replace deprecated `Dial` by `DialContext`.
=> Remove a direct use of golang.org/x/net/http2

docker/body_reader.go, docker/body_reader_test.go
Even if we didn't make much progress, allow one retry per minute anyway. Notably this allows one retry ~immediately, we see failures a few dozen milliseconds after the connection is set up.
=> Relax retry heuristics

go.mod, go.sum
This removes quite a bit of dependent code (295 kB on macOS).
It also adds a new github.com/go-jose/go-jose.v2 , but we'll get rid of that again after https://github.com/letsencrypt/boulder/pull/6581 lands.
=> Update letsencrypt/boulder after https://github.com/letsencrypt/boulder/pull/6651

copy/copy_test.go, docker/archive/src.go, docker/archive/transport.go, docker/docker_client.go, manifest/oci.go, openshift/openshift-copies.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
The `unparam` linter is quite useful…
=> More warning fixes

version/version.go
⚠️ This is sort of an experiment.
This merges the `release-5.24` branch into main. Effects of this:
- `version.go` on `main` is updated to a version after the last released one, reducing the risk of trying to release the same version again
- The git commit graph now correctly represents that everything in `release-5.24` is present on `main`
- The Go module pseudo-version mechanism should now name commits on `main` to be `v5.24.2-0.…`, not `v5.24.1–0.…`, because the `v5.24.1` tag is reachable on `main`. That should, in turn, help automated upgrade tools to stop proposing downgrades from the `main` branch to the release branch, like https://github.com/containers/skopeo/pull/1903 .
The last part is a somewhat-researched hypothesis, but it’s basically an experiment. We can’t do that …
=> Merge release branch into main

docs/containers-signature.5.md
The current implementation transparently accepts them in `gpgmeSigningMechanism` , but `openpgpSigningMechanism` rejects them; so make it clear that they should be rejected.
See #1852 .
=> Make it clear that cleartext signatures are not accepted in simple signing

internal/signature/signature.go, internal/signature/sigstore.go, internal/signature/sigstore_test.go, signature/internal/sigstore_payload.go, signature/internal/sigstore_payload_test.go, signature/simple.go, signature/simple_test.go
… just to express more precisely how they are used, and to possibly help compilers/linters with scope analysis.
Should not change behavior. All of these types are internal, so we can trivially make them public again if necessary.
=> Make some symbols in internal packages package-private

pkg/tlsclientconfig/tlsclientconfig.go
backported from:
https://github.com/moby/moby/commit/ff408210da8ebcb6d3c333b6270b921442bcc1da
=> distribution: remove use of deprecated dial.DualStack

ostree/ostree_dest.go
I’m afraid I broke this during refactoring; we’ve been releasing broken `ostree` since c/image 5.22.0 (Jul 2022)
It’s tempting to conclude that if no-one has noticed in that time, we really might be able to drop the transport without _noticeably_ breaking API.
This was reported in https://github.com/containers/skopeo/issues/1917 , with the suggestion that the report might volunteer to maintain the transport. So, let’s concentrate the discussion about the future of that transport in that other issue.
---
I have verified that this allows the transport to build; I didn’t actually try using it.
=> Fix builds of the ostree transport

version/version.go
… so that users of the c/image main branch are not offered downgrades, and so that they can continue to use `main` without having to use a `replace` directive.
=> Merge release branch into `main`

docker/daemon/client_test.go, docker/daemon/daemon_dest.go, docker/daemon/daemon_src.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, oci/layout/oci_src.go, pkg/tlsclientconfig/tlsclientconfig.go
Enable HTTP(S) keep-alive to improve network performance and reduce latency.  We need several HTTP(S) requests before we get to request the blob and each of them requires a new HTTP(S) connection and that slows down significantly pulling images, especially on networks with a higher latency (e.g. wifi).
This will allow multiple requests to be sent over a single connection, reducing the overhead of establishing new connections for each request.
=> client: enable HTTP(S) keep-alive

copy/compression.go, copy/copy.go, copy/single.go
There may be needs to modify of selected compression for a single instance so allow setting compression to imageCopier which can be altered while operation is being performed on a single image.
Part of discussion here: https://github.com/containers/image/pull/1875
=> copy: move `c.compression*` to `imageCopier`

copy/copy.go, copy/single.go
Both the referenced features were dropped in the final version of https://github.com/containers/image/pull/673 which added these comments.
=> Remove some inaccurate comments

docs/containers-auth.json.5.md
... to decrease the risk that users might think it doesn't need protecting.
=> Don't claim auth.json contains encrypted information

docs/containers-policy.json.5.md
From the current documentation, one could mistakenly assume, that `use-sigstore-attachments` needs to be enabled by the registry and not in the client. This commit rephrases the part of the documentation to make it more clear, that this needs to be done on the client side.
Signed-off-by: Lucas Humfeldt <lucas@humfeldt.de>
=> refactor(docs): Disambiguate sigstoreSigned documentation

signature/sigstore/copied.go
Don't (yet) generate them, no released version of cosign can work with them.
Compare Cosign’s change: https://github.com/sigstore/cosign/pull/2735
=> Allow using cosign-generated private keys with a "SIGSTORE" type

signature/docker.go, signature/docker_test.go, signature/fixtures_info_test.go
To support https://github.com/containers/skopeo/pull/1950
=> Add ability to verify a signature with a set of fingerprints

go.mod, go.sum, signature/fulcio_cert.go, signature/fulcio_cert_test.go
v1.2.0 deprecates an existing certificate extension, and introduces a new one. So, support that.
Tested _only_ using unit tests, not against a real certificate; at least the public Fulcio server does not yet generate the new extension.
=> Update, and support, Fulcio v1.2.0

copy/compression.go, copy/single.go, pkg/blobcache/src.go, pkg/compression/internal/types.go, storage/storage_src.go
It's completely undefined whether the OCI blob annotations apply to the object as a concept, regardless of representation, or to the specific binary representation. So it's unclear whether we should preserve or drop them when compressing/decompressing/substituting blobs.
In particular, we currently don't truly correctly handle the zstd:chunked annotations on:
- decompression (should be dropped)
- recompression (should be dropped)
- substitution (should be replaced by data about the other blob, if any; we don't record that)
Right now, we drop all annotations on decompression and recompression (which happens to work fine), and preserve annotations on substitution (which is technically invalid).
Luckily, the zstd:chunked use is opportunistic, and if the annotations are invalid or not …
=> Add FIXMEs about handling of zstd:chunked blob annotations on blob changes

version/version.go
Registry accesses now benefit from HTTP keep-alives, instead of making a separate connection for each request.
If an image provides a Zstd variant, it is now read preferentially.
Image copies preserve OCI layer descriptor annotations in more (but not all) cases.
Now requires Go 1.18.
- Convert openshift from ghodss/yaml to gopkg.in/yaml.v3
- Convert docker from ghodss/yaml to yaml.v3
- Add a more specific error message on invalid docker-config-in-OCI-image images
- Cirrus: Use human-readable CI VM Images
- Update to github.com/vbauerster/mpb/v8
- Update to docker/docker v23.0.0
- Manually add dependencies of github.com/docker/docker
- go mod tidy -go=1.18
- Use bytes.Cut instead of bytes.Index
- Use strings.Cut instead of strings.SplitN
- Use golang.org/x/exp to avoid open-coded loops.
- …
=> Release 5.25.0

oci/layout/fixtures/name_lookups/index.json, oci/layout/fixtures/two_images_manifest/index.json, oci/layout/oci_transport.go, oci/layout/oci_transport_test.go
Instead, report that we did find a match and that it is not supported.
Partially fixes https://github.com/containers/skopeo/issues/1975 .
Also, significantly improve unit tests of that code.
=> Don't completely silently ignore non-OCI manifests in OCI layouts

docker/distribution_error_test.go, sif/src.go, storage/storage_test.go, tarball/tarball_src.go
Track layer data in a single `map[digest]struct` instead of 6 separate arrays, some completely unused, and other fields.
Also simplify how that data is created, and fix pedantically-invalid uses of `bytes.NewBuffer`.
(Motivated by https://github.com/containers/podman/issues/18193 but this doesn’t do anything to actually fix it.)
=> Simplify the tarball: transport

copy/blob.go, copy/encryption.go, copy/manifest.go, copy/manifest_test.go
- When encrypting, actually make a choice even if the destination does not care about manifest formats
- Don't try converting to formats that don't support encryption at all
- Fail with a readable error message instead of "internal error"  if we filter out all candidates.
- Explicitly fail encryption/decryption if we can't change the manifest, instead of failing later with an internal error
See individual commit messages for a bit more detail.
=> Fix conversion determination when encrypting

docker/daemon/client.go, go.mod, go.sum
… primarily to stop using a deprecated API, and allow updating docker/docker to v23.0.5; compare https://github.com/containers/image/pull/1931 .
Also, refactor the code a bit, and document even more precisely what is going on.
Finally, update docker/docker (using the Renovate-created commit).
=> Update the docker-daemon: client, and docker/docker dependency

docs/containers-auth.json.5.md, pkg/docker/config/config.go, types/types.go
Finally address my peeve that user name + password forms “credentials”, not “an authentication”.
Also clean up the `containers-auth.json(5)` man page a bit more; and update the code similarly.
See individual commit messages for a bit more detail. Should not change behavior.
=> Clean up auth.json documentation

copy/multiple.go
After https://github.com/containers/image/pull/1896 `c/image` now supports new API `EditInstances` which is more flexible in terms of `Adding` new instances or `Modifying` existing instances so lets use that.
=> copy/multiple: use more flexible `EditInstances` instead of `UpdateInstances`

README.md
Fixes #1988 . (Well, avoids it.)
=> Don't claim that libostree is required by default.

docker/docker_client.go, openshift/openshift-copies.go
Instead, let Go manage the default; this effectively moves the version from TLS 1.0 to TLS 1.2 (because c/image requires Go 1.18 to compile).
(In the worst case, affected users can disable TLS; we don’t provide any other options.) Compare https://github.com/moby/moby/commit/626c097f8c29bf432e5465a961496bf41aa74cad updating to TLS 1.2; it is similarly not configurable. 
Fixes #1962 .
=> Stop having an opinion on TLS version

copy/single.go
Currently, the copy command prints the message 'Storing signatures' and calls the signature storing function, even if there are no signatures present. This can mislead users and make them believe that there are image signatures.
The proposed change modifies the copy function to print the message and invoke the image storing function only if there is at least one signature.
=> Don't store signatures if there is none of them

docs/containers-transports.5.md
Motivated by https://github.com/containers/skopeo/issues/2019 .
=> Clarify how `oci` and `oci-archive` parse colons

version/version.go
Bump to v5.26.0
I bumped to 5.27.0-dev, too, as I'm planning to create a release branch for v5.26.0, and that's where 5.26.1 will get generated.  We'll use v5.26.* for RHEL 8.8/9.3 either in Podman v4.6 or v4.7, the version number is to be decided.
[NO NEW TESTS NEEDED]
=> Bump to v5.26.0

copy/single.go, docker/docker_image_src_test.go, oci/archive/oci_transport_test.go, oci/layout/oci_src_test.go, oci/layout/oci_transport_test.go, openshift/openshift.go, openshift/openshift_dest.go, openshift/openshift_src.go, ostree/ostree_transport_test.go
- Close `ImageSource` objects
- Close the HTTP client used by the `atomic` transport
=> Ensure we close HTTP connections on all paths

go.mod, go.sum, version/version.go
C/storage 1.48.0 is needed for Podman v4.6 due to a late change.  Vendoring that into the v5.26.0 stream, then bumping the version there to 5.26.1 to be tagged, and then 5.26.2-dev for later development.
[NO NEW TESTS NEEDED]
=> [release-5.26] c/storage to 1.48, bump c/image to v5.26.1, and then to v5.26.2-dev

internal/manifest/docker_schema2_list.go, internal/manifest/docker_schema2_list_test.go, internal/manifest/list.go, internal/manifest/oci_index.go, internal/manifest/oci_index_test.go
`c/image` uses `Instance(` API to get the required details of an instance while performing replication, `Platform` of instance is needed so it can use it again while adding an instance hence adding `Platform` to `ListUpdate` 
Needed by: https://github.com/containers/image/pull/1987
See prior comment here: https://github.com/containers/image/pull/1875#discussion_r1128464266
=> manifest: `ListUpdate` add `imgspecv1.Platform` field

pkg/docker/config/config.go, pkg/docker/config/config_test.go, pkg/docker/config/testdata/docker-credential-helper-registry
This was defaulting to "/run/containers/\<uid\>/auth.json" unless the OS was "darwin" or "windows". It makes more sense to use "~/.config/containers/auth.json" instead which removes the need for a "/run" directory on the host.
=> pkg/docker: use the same default auth path as macOS on FreeBSD

directory/directory_dest.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, internal/imagedestination/impl/helpers.go, internal/imagedestination/impl/helpers_test.go, internal/imagedestination/wrapper.go, internal/private/private.go, oci/layout/oci_dest.go, ostree/ostree_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go
TryReusingBlob now contains a new option `RequiredCompression` which filters the blob by checking against a compression of the blob which is considerd to be resued, in case `RequiredCompression` is set and `info` of the blob being reused does not matches, no blob is returned.
=> blob: `TryReusingBlobWithOptions` consider `RequiredCompression` if set

ostree/ostree_dest_test.go, ostree/ostree_transport_test.go
... which I broke on 2022-03-16, and noone noticed.
(The actual non-test code was, at least east as of today, buildable, so this does not prove that noone is using the code... but it's a hint in that direction.)
=> Fix tests of the ostree transport

internal/imagedestination/impl/helpers_test.go
Fixes: https://github.com/containers/image/pull/2023#discussion_r1261581159.
`assert.Equal` expects `assert.Equal(t, expected, actual)` instead of `assert.Equal(t, actual, expected)`.
Ref:https://pkg.go.dev/github.com/stretchr/testify/assert#Assertions.Equal
=> helpers_test,cleanup: correct argument order

docker/internal/tarfile/reader.go, internal/streamdigest/stream_digest.go, internal/tmpdir/tmpdir.go, internal/tmpdir/tmpdir_test.go, oci/archive/oci_transport.go, sif/src.go, storage/storage_dest.go, storage/storage_src.go
If you hit Ctr-C while pulling an image files and directories get left in /var/tmp. By adding "containers_images" prefix, we can use systemd tmpfiles handling to remove them on reboot safely.
Help to make https://github.com/containers/podman/pull/19201 safer.
=> Make temporary names container/image specific

internal/manifest/oci_index_test.go
Setting `SystemContext.ArchitectureChoice` to `""` does not mean "match any/the first platform"; it's the default behavior of `SystemContext`, and it means "choose for the current runtime architecture". (Originally discussed in https://github.com/containers/image/pull/1789#discussion_r1115647449 )
I.e. on `amd64` these two test cases are redundant with the first two instances above, and on other architectures (notably ARM) they cause failures.
So just drop them.
=> Fix TestOCI1IndexChooseInstanceByCompression on non-amd64

copy/blob.go, copy/copy.go, copy/encryption.go, copy/multiple.go, copy/sign.go, copy/sign_test.go, copy/single.go
This is motivated by the concurrent Zstd work, to make it more maintainable to pass data from and to `copySingleImage`.
- Add `copier.options`, `copier.policyContext` and `copier.unparsedToplevel` instead of passing them around in parameters
- Eliminate fields of `copier` and `imageCopier` that are now reachable through `.options`
- Return a `copySingleImageResult` from `copySingleImage`
@flouthoc I realize this is disruptive, and I want to do whatever necessary not to disrupt or slow down your work. Let me know what works for you — feel free to completely ignore this (and I’ll rebase this later as necessary), to reimplement parts yourself in some other way, or to tell me to split this up (maybe only the `copySingleImageResult` part?).
Others: Please don’t merge this without an ACK from …
=> Refactor data passing in c/image/copy

copy/copy.go, copy/multiple.go, copy/single.go, internal/manifest/oci_index.go, internal/set/set_test.go
Needed By: https://github.com/containers/skopeo/pull/2047
* Users can set compression formats while performing `copy` in such cases
`instanceCopyCopy` must honor UpdateCompressionAlgorithms.
* copy/single: set requiredCompression if compressionFormat is changed
- Modifies `copy/single` to correctly use the feature from
https://github.com/containers/image/pull/2023, that is if compression is
changed blob must be resued only if it matches required compression.
* oci_index: init Annotations if nil and required
- If `UpdateCompressionAlgorithms` is set then `Annotations` map must be
initialized if its not set.
Integration tests for `e2e` feature added here: https://github.com/containers/skopeo/pull/2047#issue-1809369600
=> copy/multiple: instanceCopyCopy honor `UpdateCompressionAlgorithms`

copy/copy.go, copy/multiple.go, copy/single.go
After https://github.com/containers/image/pull/2048 there is no room for `copy/multiple` to pass custom options to `copySingleImage` while processing each instance, following PR introduces that functionality again and wraps options to simpler struct.
Needed by: https://github.com/containers/image/pull/1987
=> copy/single: accept custom `*Options` and wrap arguments in `copySingleImageOptions`

docker/policyconfiguration/naming.go, docs/containers-policy.json.5.md, docs/containers-transports.5.md, transports/alltransports/alltransports.go
… in `containers-transports(5)` and `containers-policy.json(5)`.
See individual commit messages for a bit more detail.
Fixes #1501 .
=> Improve transport documentation

copy/copy.go, copy/multiple.go, copy/multiple_test.go, internal/set/set.go, internal/set/set_test.go
* `copy.Options` now contains a new field `EnsureCompressionVariantExists map[string]int` which allows users to specify if they want to clone images with specified `compression`.
* `copyMultipleImages` now implements `instanceCopyClone` and extends function specifically for `zstd` compression.
=> copy: implement `instanceCopyClone` for `zstd` compression

copy/multiple.go, copy/multiple_test.go
When copying multiple images i.e `instanceCopyClone` and no image exists in registry in such case if clones are prepared and copied first then original copies will reuse blobs from the clone which is unexpected since argument `requireCompressionFormatMatch` is by default false for `instanceCopyCopy` case.
Problem described in following PR is easily reproduceable when working with tools such as buildah, because without this PR buildah will push `clones` first instead of originals and later on `originals` will reuse blobs from `clones`.
Reproducer with empty registry
```console
./buildah manifest create localhost:5000/list:latest
./buildah build -t test .
./buildah manifest add localhost:5000/list:latest test
./buildah manifest push --tls-verify=false --all --add-compression zstd …
```
=> copy/multiple: priority of `instanceCopyCopy` must be higher than `instanceCopyClone`

go.mod, go.sum, internal/manifest/oci_index.go, pkg/blobinfocache/internal/prioritize/prioritize.go, pkg/tlsclientconfig/tlsclientconfig_test.go, storage/storage_dest.go
Primarily replaces #2065 ; also a few other changes found during slice usage audit.
=> Update x/exp/slices, and some small slice-related cleanups

copy/copy.go, copy/multiple.go, copy/multiple_test.go
ForceCompressionFormat allows end users to force selected compression format (set in DestinationCtx.CompressionFormat) which ensures that while copying blobs of other compression algorithms are not reused.
Following flag is a frontend wrapper for: https://github.com/containers/image/pull/2023 
Will help in:
* https://github.com/containers/buildah/issues/4613
* https://github.com/containers/podman/issues/18660
=> copy: add support for `ForceCompressionFormat`

.cirrus.yml
Skopeo has updated golang.org/x/exp to an API-incompatible version, so test this stable branch against a corresponding Skopeo stable branch.
=> [release-5.27] Test the release-5.27 branch against the 1.13 branch of Skopeo

.cirrus.yml, copy/blob.go, copy/copy.go, copy/encryption.go, copy/multiple.go, copy/multiple_test.go, copy/sign.go, copy/sign_test.go, copy/single.go, directory/directory_dest.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, internal/imagedestination/impl/helpers.go, internal/imagedestination/impl/helpers_test.go, internal/imagedestination/wrapper.go, internal/manifest/docker_schema2_list.go, internal/manifest/docker_schema2_list_test.go, internal/manifest/list.go, internal/manifest/oci_index.go, internal/manifest/oci_index_test.go, internal/private/private.go, internal/set/set.go, internal/set/set_test.go, oci/layout/oci_dest.go, ostree/ostree_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go, version/version.go
<s>Looking at #2074, CI is not running on the new `release-5.27` branch yet.</s>
This:
- <s>Includes #2074 , to hopefully make tests pass with this older codebase</s>
- Includes the #2071 backport
- Bumps `version.go` to 5.27.0
I.e. this should be all that is necessary to tag a tested 5.27.0 release — **except** that this PR is filed against the 5.26 branch, to trigger a test run.
If the test passes, this can be merged into the 5.27 branch, and (the right commit) tagged as c/image 5.27.0. (Alternatively, if the move to 5.27 were unreasonable, a variant of #2074 can be used on the `release-5.26` branch.
=> [release-5.27] Preparing 5.27 backport

go.mod, storage/storage_dest.go
We already require it, because docker/credential-helpers uses Go 1.19 os/exec.Cmd.Environ(). So make that official, and benefit from a new feature.
=> Update to Go 1.19

storage/storage_dest.go
When committing an image, pass big data items and the image metadata string in as part of the set of options we pass to the storage library when creating the image.
Fall back to setting them individually, as we would have originally, only if we end up updating an image that was already in local storage.
=> storage.storageImageDestination.Commit(): leverage image options

.cirrus.yml, contrib/cirrus/runner.sh
Originally (in https://github.com/containers/image/pull/1272 ) `SKOPEO_CI_TAG` was also a tag of an on-registry image. That's no longer the case.
On c/image stable branches, we typically want to test against a corresponding skopeo stable branch, not against a specific frozen version on that stable branch, so the variable name has become a bit confusing.
So, rename it to `SKOPEO_CI_BRANCH`.
=> Rename SKOPEO_CI_TAG to SKOPEO_CI_BRANCH

.github/workflows/check_cirrus_cron.yml, .github/workflows/rerun_cirrus_cron.yml
Ref: https://github.com/containers/image/pull/2074#issuecomment-1666178820
=> [CI:DOCS] Add cirrus-cron retry/monitor jobs

copy/single.go, docker/docker_client.go, docker/docker_client_test.go, docker/docker_image_dest.go, docker/errors.go, internal/image/docker_schema2_test.go, internal/image/fixtures/oci1-config-extra-fields.json, internal/image/fixtures/oci1-extra-config-fields.json, internal/image/oci.go, internal/image/oci_test.go, internal/manifest/docker_schema2_list.go, internal/manifest/errors.go, internal/manifest/oci_index.go, internal/pkg/platform/platform_matcher.go, manifest/oci.go
This is an assorted set of small changes to support OCI image-spec/distribution-spec 1.1.
Follow #2030 for checklists of things to update/address.
See individual commit messages for details. Note especially the RFC and UNTESTED ones.
=> OCI image-spec / distribution-spec v1.1 updates, first round

.cirrus.yml
Skopeo has updated golang.org/x/exp to an API-incompatible version, so test this stable branch against a corresponding Skopeo stable branch.
=> [release-5.26] Test the release-5.26 branch against the 1.13 branch of Skopeo

go.mod, go.sum, signature/sigstore/copied.go
The `github.com/theupdateframework/go-tuf/encrypted` subpackage is deprecated, switch to the new location.
Separately, this is a BREAKING change: the key encryption parameters of `encrypted.Encrypt` have been changed, so the keys generated by the new code can't be loaded by older implementations. (Old keys can continue to be used by new implementations.)
Let’s coordinate with Cosign on whether to make that change, or whether to keep using the old compatible parameters (using `EncryptWithCustomKDFParameters`).
=> BREAKING: Update for move of github.com/theupdateframework/go-tuf/encrypted

go.mod, go.sum, version/version.go
Bump c/storage to 1.48.1
Bump c/image to 5.26.2
Bump c/image to 5.26.3-dev
in preparation for RHEL 8.9/9.3 final freeze
[NO NEW TESTS NEEDED]
=> [release-5.26] Bump c/storage to 1.48.1, c/image to 5.26.2 and 5.26.3-dev

storage/storage_test.go
Currently that fails with:
```
storage/storage_test.go:183:11: SA5011: possible nil pointer dereference (staticcheck)
spec := ref.StringWithinTransport()
^
storage/storage_test.go:188:6: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
if ref == nil {
```
which is a real bug; and
```
storage/storage_test.go:183:11: SA5011: possible nil pointer dereference (staticcheck)
spec := ref.StringWithinTransport()
^
storage/storage_test.go:180:6: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
if ref == nil {
```
which is a false positive, AFAICS.
See individual commit messages for details; one of them is just a workaround, but it seems worth doing anyway.
=> Fix build with golangci-lint 1.54.2

copy/compression.go, copy/copy.go, copy/single.go, docker/docker_transport_test.go, go.mod, go.sum, internal/blobinfocache/blobinfocache.go, internal/blobinfocache/types.go, pkg/blobinfocache/boltdb/boltdb.go, pkg/blobinfocache/default.go, pkg/blobinfocache/default_test.go, pkg/blobinfocache/internal/test/test.go, pkg/blobinfocache/memory/memory.go, pkg/blobinfocache/sqlite/sqlite.go, pkg/blobinfocache/sqlite/sqlite_test.go
This implements a SQLite-based `types.BlobInfoCache`, using it instead of BoltDB.
---
@mheon @Luap99 @vrothberg PTAL at the SQLite concurrency configuration, at least; this is cribbed from Podman but I haven’t followed the evolving situation there and I don’t know what I don’t know.
---
<s>Marked as draft because I didn’t actually test the implementation (other than existing unit tests), and I’m not sure about lifetime management.</s>
It turns out that the underlying `*sql.DB` (and `*sql.Conn`) objects would benefit from a having the caller call `Close`, which is not currently a part of the `BlobInfoCache` model. (Alternatively, the SQLite implementation could create and tear down SQLite state for every single write…) That, indirectly, means that the `SystemContext.BlobInfoCacheDir` …
=> Implement, and default to, a SQLite BlobInfoCache instead of BoltDB

go.mod, go.sum
`docker/docker` maintains its dependencies in `vendor.mod`, not `go.mod`, so automated tooling doesn't know to follow that.
Do that manually:
```
go get gotest.tools/v3@v3.5.0
```
This is actually _called_ only in tests, so it does not change the built binary. But update to make sure the dependency tree is not behind what docker/docker is testing with.
https://github.com/containers/image/pull/2109 updated `docker/docker` itself.
=> Update dependencies of docker/docker

copy/single.go, internal/image/common_test.go, internal/image/docker_schema1_test.go, internal/image/docker_schema2_test.go, internal/image/fixtures/oci1.encrypted.json, internal/image/oci.go, internal/image/oci_test.go, manifest/docker_schema1.go, manifest/docker_schema1_test.go, manifest/docker_schema2.go, manifest/docker_schema2_test.go, manifest/fixtures/ociv1.encrypted.manifest.json, manifest/oci_test.go
This
- implements decryption and conversion from OCI to non-OCI in a single operation, per #1604 / https://github.com/containers/skopeo/issues/1703
- modifies schema1 and schema2 to fail on requests to edit the manifest with encryption/decryption (which should not typically be reached after #1930, but it is at least available as an API to external callers)
- updates/extends unit tests to handle conversion, decryption, and encryption, of all three supported manifest formats
- fixes logic determining the manifest format when decrypting
=> Correctly handle encryption/decryption changes in non-OCI formats

oci/layout/oci_dest.go, oci/layout/oci_transport.go
Fixes #2118 , along with a microoptimization.
See individual commits.
=> Use constants and types from opencontainers/image-spec/specs-go/v1

copy/single.go
the mpb.Progress doesn't allow to set the Refill value bigger than Current so make sure we set Current before setting Refill otherwise we will report the wrong number of skipped bytes.
=> progress: set Current before Refill

copy/single.go
related to #2047 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xcbbbf7]
goroutine 1 [running]:
github.com/containers/image/v5/copy.(*imageCopier).compareImageDestinationManifestEqual(0xc0000c3860, {0x1b88850, 0xc000044158}, 0xc00001cc08)
/home/crazymax/github.com/containers/image/v5@v5.28.0/copy/single.go:384 +0x677
github.com/containers/image/v5/copy.(*copier).copySingleImage(0xc000427b80, {0x1b88850, 0xc000044158}, 0xc00048dc80, 0xc00001cc08, {0x4?, 0x0?, 0x0?})
/home/crazymax/github.com/containers/image/v5@v5.28.0/copy/single.go:194 +0xde5
github.com/containers/image/v5/copy.(*copier).copyMultipleImages(0xc000427b80, {0x1b88850, 0xc000044158})
/home/crazymax/github.com/containers/image/v5@v5.28.0/copy/multiple.go:24 …
```
=> copy: fix nil pointer dereference when checking compression algorithm

oci/archive/oci_src.go, oci/archive/oci_src_test.go, oci/archive/oci_transport.go
This is for https://github.com/containers/skopeo/pull/2114
which is in turn a dependency of https://github.com/coreos/rpm-ostree/pull/4598
Basically I want to map ENOENT to a clear error, because the build
tooling wants to treat "target image is not present" differently
from "DNS lookup failed" or "we got EPERM".
There's a bit of code motion here because we need to move
the `os.Open()` call before creating a temporary directory.
Signed-off-by: Colin Walters <walters@verbum.org>
---
=> ociarchive: Add new `ArchiveFileNotFoundError`

docker/docker_client.go
This PR attempts to fix this issue https://github.com/containers/podman/issues/20230.
Looking at `moby`, it looks like they are doing a hacky trick when we add `library` to the image.
As seen [here](https://github.com/moby/moby/blob/master/registry/search.go#L99-L102):
```go
if index.Official {
// If pull "library/foo", it's stored locally under "foo"
remoteName = strings.TrimPrefix(remoteName, "library/")
}
```
If the registry is official then we need to trim "library/" from the image name.
Now what registries are set as official? Looking further at [the `newIndexInfo` function](https://github.com/moby/moby/blob/master/registry/config.go#L394-L404):
If the registry name is set in the configuration we will return it.
```go
// Return any configured index info, first.
if index, ok := …
```
=> Fix podman search for docker.io/library images

internal/image/common_test.go, internal/image/fixtures/oci1-all-media-types-config.json, internal/image/fixtures/oci1-all-media-types-to-schema2-config.json, internal/image/fixtures/oci1-all-media-types.json, internal/image/oci.go, internal/image/oci_test.go, types/types.go
For any Zstd layer, do a MIME type update (presumably converting from Zstd to something else) before we do the
format conversion, so that the format conversion doesn't fail with an unsupported MIME type.
Fixes #1260 .
=> Fix conversion of Zstd images to non-OCI formats

docker/daemon/daemon_dest.go
Fixes #955 .
Tested manually (with a modified Skopeo which uses an invalid tag, not with a "disk full" error).
=> Parse the body of (docker load) response to correctly handle errors

copy/multiple.go, copy/single.go, docker/distribution_error.go, docker/docker_image_dest.go, internal/image/docker_schema1_test.go, internal/image/docker_schema2_test.go, internal/image/oci_test.go, internal/manifest/docker_schema2_list.go, internal/manifest/docker_schema2_list_test.go, internal/manifest/oci_index.go, internal/testing/gpgagent/gpg_agent.go, oci/layout/oci_dest.go, pkg/shortnames/shortnames.go, pkg/tlsclientconfig/tlsclientconfig.go, signature/fulcio_cert_test.go, signature/internal/sigstore_payload_test.go
If some code creates a slice with extra capacity, and provides it to more than one user which calls append(), those two users will write conflicting data to the same backing array.
So, use `append(slices.Clone(...), ...)` whenever the origin of the array backing a slice is unclear (or even in cases where it can be traced but the code is a bit remote, making it hard to maintain).
A demonstration of the problem:
```go
package main
import (
"fmt"
"sync"
"time"
)
func goroutine(wg *sync.WaitGroup, sharedSlice []int, i int) {
defer wg.Done()
privateSlice := append(sharedSlice, i)
oldValue := privateSlice[len(privateSlice)-1]
// This is already slow enough that the "full" value is frequently overwritten by another goroutine
fmt.Printf("goroutine %d: immediate %d; full %#v@%v\n", i, oldValue, …
```
=> Don't use append() on slices with unclear origin

.cirrus.yml
Some other containers/* repos use these values in test names; we don't, so remove them so that we don't have to worry about keeping them up to date.
Previously https://github.com/containers/image/pull/2150 ; @cevich PTAL to make sure I’m not missing any non-obvious references to these variables.
=> Remove unused environment variables in Cirrus

storage/storage_test.go
For CRI-O (and, maybe, Podman/libimate), I want to introduce a new reference lookup method, and that needs tests against a locally-created image.
It turns out those tests required root, and we never run them as root. So a large part of storage transport tests have been unused for _4 years_ now.
This fixes that problem:
Fixes #1729 . And at least on a Mac (?), the tests don’t actually require any privileges, so run them unconditionally.
This PR also consolidates the existing code to create/test images to significantly reduce duplication, to benefit from `testify`, and to make it easier to add more test cases, now that I have been reading the code.
@vrothberg PTAL. Cc: @saschagrunert
=> Fix and simplify storage tests

image/unparsed.go, storage/storage_reference.go, storage/storage_reference_test.go, storage/storage_transport.go
We need to implement this locally, instead of having external callers do it, because external wrapping would make the sigstore-relevant `UntrustedSignatures` unavailable.
See conversation in https://github.com/cri-o/cri-o/pull/7046 .
=> Add image.UnparsedInstanceWithReference and storage.ResolveReference

docker/docker_image_dest.go
As the documentation says, "It is always OK to pass nil instead of a SystemContext."
I failed to get a suitable minimal reproduction project, but I got a panic on this line while using the library to copy images around once it decided to recompress a few layers, and I have confirmed that applying the change locally (or passing a suitable DestinationCtx to copy.Image) fixes the panic. Still, let me know if an actual reproduction would be necessary to get this merged.
=> Missed null check in docker_image_dest.go

go.mod, go.sum, storage/storage_test.go
After https://github.com/containers/storage/pull/1735 , we don't need the condition, so remove it.
=> Simplify storage test setup

pkg/blobinfocache/sqlite/sqlite.go
Following check is not needed and can be removed. 
Followup fix from https://github.com/containers/image/pull/1645#discussion_r1379024267
=> blobinfocache,sqlite: remove unnecessary compression check

storage/storage_reference.go, storage/storage_transport.go
- Document the error returned if image is not found
- Also document it for the internal resolveImage, to record the commitment
- Update the deprecation comments to warn about the error return value change
Thanks to @flouthoc for demonstrating the need for this documentation.
Possible alternatives:
- Don’t change the error type; continue using `c/storage.ErrImageUnknown` for the new `ResolveReference`
- Define a new c/image error type; the current `c/image/storage.ErrNoSuchImage` is an alias for `c/storage.ErrNotAnImage`, which is really a different error cause.
- Possibly both? Define a new c/image error type, as an alias to c/storage.ErrImageUnknown.
=> Improve documentation of ResolveReference

Makefile
- Stop installing unused `golint`
- Automate `golangci-lint` version management, so that we get Renovate PRs like Skopeo’s https://github.com/containers/skopeo/pull/2139 . This intentionally does not upgrade the currently-used version, to trigger a Renovate update immediately.
=> Improve lint tool handling

docker/errors.go, docker/errors_test.go
... to make sure we don't output raw control characters, for example.
A probably unexpected outcome of https://github.com/containers/podman/issues/20343 .
=> Quote the response body in an error message

copy/compression.go, internal/imagedestination/impl/helpers.go
Absolutely untested.
For @giuseppe to experiment with.
=> WIP HACK: Do not reuse zstd:chunked blobs

go.mod, go.sum, oci/archive/oci_dest.go, oci/archive/oci_dest_test.go
Fixes #1627 .
<s>Requires unmerged https://github.com/containers/storage/pull/1765 .</s>
=> Don't expose local account details in oci-archive tar files

copy/manifest.go, copy/manifest_test.go, copy/single.go, internal/manifest/manifest.go, internal/manifest/manifest_test.go, manifest/manifest.go
... even if the destination does not restrict manifest schemas.
Fixes #2195.
=> Trigger a conversion to OCI when compressing to Zstd

copy/single.go, go.mod, go.sum, internal/private/private.go, manifest/oci.go, storage/storage_dest.go, storage/storage_src.go
if the computed digest mismatches the expected one for a partial image.  This is expected since partial images are stored by their TOC digest, not the diffID for the layer.
=> copy: do not fail if digest mismatches

Makefile, default-policy.json, default.yaml
It makes more sense to keep these 2 files along with their man pages...in c/image
As discussed in
https://github.com/containers/common/pull/1757
=> Moving policy.json and default.yaml from containers/skopeo

internal/pkg/platform/platform_matcher.go
The PR fixes a corner-case problem in which images for raspberry pi 1 or raspberry pi zero single board computers are downloaded for a wrong architecture, resulting in unability to run containers.
Also, PR adds some prints to improve the debugging.
The problem may be easily reproduced when using a rpi 1 or rpi zero with podman:
current version:
```sh
> podman run --log-level=info --syslog busybox echo ok
INFO[0000] podman filtering at log level info
INFO[0000] Setting parallel job count to 4
Resolved "busybox" as an alias (/home/pi/.cache/containers/short-name-aliases.conf)
Trying to pull docker.io/library/busybox:latest...
Copying blob 0983f321071f done
Copying config 87837ce2bf done
Writing manifest to image destination
Storing signatures
INFO[0011] …
```
=> Fix raspberry pi zero cpu variant recognition

docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/docker_transport.go, docker/docker_transport_test.go, docs/containers-transports.5.md
Backported #2209 to release-5.29 branch for Podman 4.9, as this is required for the `podman farm build` feature. Backporting features is unusual, but Podman 4.9 is a very unusual release (based on 4.8 instead of main), which makes this necessary.
I can, at least, say that we do not intend on making a habit out of this.
=> Backport #2209 to release-5.29 branch

version/version.go
Release 5.29.1 happened on a branch; merge it into `main` to let Git, and go tools, now that `main` is “after” 5.29.1, notably so that updating to `main` does not trigger a downgrade of c/common to a version which does not require 5.29.1, or an upgrade of c/common does not trigger a downgrade from a `main` checkout to the branched 5.29.1 version of c/image.
=> Main is after latest release

.cirrus.yml
... to avoid breakage on incompatible dependency updates, like https://cirrus-ci.com/build/5613830407979008 .
=> Use a stable Skopeo branch for testing the stable c/image branch

docker/daemon/client.go, docker/daemon/client_test.go, go.sum
The version is currently hardcoded which is causing the issue documented here - https://github.com/containers/image/issues/2259
Decided adding a unit test wasn't feasible as as the version would change each time we pulled in a new docker client and as long as it negotiates a version that works I suspect we don't care what that exact version is.
=> Allow docker client to negotiate the API version with the server 

version/version.go
As we have a release-5.29 branch now that we will be updating, bump the main branch up to v5.30-dev to stop confusion.
=> Bump to v5.30.0-dev

docker/daemon/client.go, docker/daemon/client_test.go, version/version.go
In preparation for Podman v4.9.1, add the Docker Daemon version fix from #2260 and then bump the version to 5.29.2 before creating a release from this branch.
=> Backport Docker Daemon fix #2260, bump to 5.29.2, then 5.29.3-dev 

copy/compression.go, copy/manifest.go, copy/manifest_test.go, copy/single.go, directory/directory_dest.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, internal/imagedestination/impl/helpers.go, internal/imagedestination/impl/helpers_test.go, internal/private/private.go, oci/layout/oci_dest.go, ostree/ostree_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go
=> Make blob reuse choices manifest-format-sensitive, and allow conversions when writing to format-agnostic transports

signature/internal/rekor_set.go
… because we are not going to update to it, short-term.
Compare #2278 .
=> Add a comment about Rekor 1.3.5

copy/compression.go, copy/single.go, types/types.go
Fixes #2182.
<s>At this point completely untested.</s>
=> Edit the manifest when pushing uncompressed data from c/storage

oci/layout/oci_src_test.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_src.go
… on the principle that removing accidental complexity makes it easier to focus on the essential complexity.
(Yes, this conflicts with #2218 ; I’ll rebase that work.)
@giuseppe PTAL.
=> Random storage-related cleanups

storage/storage_dest.go, storage/storage_src.go
In addition to some small docs updates, this introduces `storageImageDestinationLockProtected` to visibly delineate the fields that need locking. Yes, this is a painful and disruptive change which requires rebasing any other changes, but the time has come. Documenting the relationships of the various layer-related fields, without distracting from the locking rule, seems too hard otherwise.
(I’ll also do the work of rebasing #2288 on top.)
@giuseppe PTAL.
=> Improve storage transport documentation, primarily about locking

copy/single.go, internal/imagedestination/stubs/put_blob_partial.go, internal/private/private.go, manifest/oci.go, oci/archive/oci_dest.go, openshift/openshift_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go, storage/storage_src.go
This is #2218 rebased on top of #2287, + my WIP work fixing issues as they come up.
Absolutely untested (do we have relevant CI in any project?).
See individual commits for details.
@giuseppe FWIW .
=> Fix c/storage destination with partial pulls

storage/storage_dest.go
Either return a compressed digest and compressed size, or an uncompressed digest and an uncompressed size (if we are allowed to change the manifest); if neither is possible, ignore the match and force a layer pull.
In almost all cases, a TOC match implies the layer has a TOC digest annotation, i.e. the input manifest is OCI, where the size field is mandatory; so this should not change which layers will be reused
- it just changes the returned size value.
Fixes https://github.com/containers/image/pull/2218#discussion_r1424652040 .
Cc: @giuseppe
=> Fix manifest updates when we match a layer by TOC digest

storage/storage_dest.go
… resolving the second part https://github.com/containers/image/pull/2218#discussion_r1470138422 .
Also adds an optimization: We now parse the config only once.
Cc: @giuseppe
=> Cleanly fail when trying to obtain a DiffID of a non-OCI image

storage/storage_src.go
Last outstanding parts of #1980.
Cc: @giuseppe (low priority)
=> Beautify TOC-related parts of storageImageSource

storage/storage_dest.go
This updates for the trivial half of https://github.com/containers/storage/pull/1830.
It does not update to benefit from the more important part (creating the reused layers with the right `CompressedDigest`/`CompressedSize`) — that also should happen, but it’s a tiny bit of _work_ and not an immediate priority.
=> Update a comment after a c/storage update

internal/manifest/oci_index.go
... so that zstd-preferring implementations like c/image can choose them.
Fixes #2077.
#2077 also talks about writing down what `InternalUnstableUndocumentedMIMEQuestionMark` means; this does not do that yet – the currently outstanding items in #2189 center around how `BlobInfoCache` deals with `zstd`/`zstd:chunked` as (not) interchangeable. Here we can trivially just check for two values without determining the exact semantics, `BlobInfoCache` will quite likely care a bit more, so decide the semantics at that point; for now, this PR just leaves a breadcrumb.
=> Also annotate image instances using zstd:chunked as using zstd

copy/multiple.go, internal/manifest/list.go, internal/manifest/oci_index.go, internal/manifest/oci_index_test.go, internal/manifest/testdata/oci1index.json
Add fields to manifest.ListUpdate for adding and updating the ArtifactType field in a list entry.  When copying a list or descriptor, preserve the value from the original descriptor for an entry.
=> Support editing ArtifactType, preserve it in lists

copy/digesting_reader.go
The reason is hidden if `expectedDigest.Validate()` errors. This patch will add the error message to the stack to provide more details.
PTAL @containers/image-maintainers
=> Add validation error to digesting reader

docker/docker_client.go
`gopls 0.15` identifies always-true/always-false conditions in the code; I broke that in fa54b28a4d7a7e97fe899f958326b2bd3f91a11a .
- Don’t ignore errors accessing layers by URLs. Note that this might break setups which were created in the past two years; they now don’t fall back to registry accesses.
- If we fail, also report all errors, not just the last one, as the original version of the code did.
=> Fix handling of errors when fetching layers by URLs

copy/compression.go, copy/single.go, internal/imagedestination/impl/helpers.go, internal/manifest/manifest.go, internal/manifest/oci_index.go, manifest/common.go, pkg/compression/compression.go, pkg/compression/internal/types.go
This is not expected to change observable behavior for now, just improve the internal logic. See individual commit messages for details.
@giuseppe PTAL.
=> Improve handling of zstd vs. zstd:chunked matching

version/version.go
Bumping in preparation of Podman v5.0.
Vendor c/storage v1.53.0 first, then c/image bump to v5.30.0.
[NO NEW TESTS NEEDED]
=> Bump c/storage to v1.53.0, c/image to v5.30.0, and then to v5.30.1-dev

go.mod, go.sum
It's the same commit, but using a tag will prevent the bots from automatically updating to future untagged commits.
=> Move to a tagged version of docker/docker

docker/docker_client.go, docker/docker_transport.go, docker/docker_transport_test.go, go.mod, internal/signature/sigstore.go, internal/signature/simple.go, manifest/oci.go, ostree/ostree_src.go, pkg/blobinfocache/internal/prioritize/prioritize.go, pkg/blobinfocache/internal/prioritize/prioritize_test.go, pkg/tlsclientconfig/tlsclientconfig.go, signature/fulcio_cert_test.go, signature/internal/sigstore_payload_test.go, signature/policy_config_test.go, storage/storage_dest.go
After https://github.com/containers/image/pull/2337 (notably https://github.com/go-openapi/swag/compare/v0.22.10...v0.23.0 ), we require Go 1.20 to build.
So, update to it formally, and take advantage of new standard library features.
=> Update to Go 1.20

manifest/docker_schema2.go
I'm trying to add support for Dockerfile HEALTHCHECK --start-interval param which has been added in Docker v25.0.0.
So I figured out I have to update this library as well.
The change is quite trivial but I couldn't say that I understand completely what I'm doing so feedback is appreciated.
=> Add support for Docker HealthConfig.StartInterval (v25.0.0+)

docker/docker_client.go, go.mod, internal/multierr/multierr.go, internal/multierr/multierr_test.go, openshift/openshift-copies.go, pkg/docker/config/config.go, pkg/shortnames/shortnames.go, pkg/sysregistriesv2/shortnames.go, signature/policy_eval_signedby.go, signature/policy_eval_sigstore.go
As of Go 1.20, the standard library supposedly contains infrastructure for reporting multiple errors.
Sadly, that infrastructure is mostly unhelpful: `errors.Join` gives no control over formatting, and `fmt.Errorf` does not support a `[]error` input. So, introduce our own `multierr.Format`, and use it where possible.
Then remove the `go-multierror` dependency. The net result is not particularly better _code_, but at least we try to work with the standard library design.
(This was originally motivated just by trying to remove the `go-multierror` dependency in #2364, now that the standard library supposedly supports the feature.)
This might, in some cases, change whether the returned error matches `errors.{As,Is}`, mostly because the previous code for aggregating multiple errors was written …
=> Add a helper for formatting multiple errors

go.mod, go.sum, oci/layout/oci_delete_test.go, signature/internal/rekor_set_test.go, signature/sigstore/rekor/rekor.go
… to try and decrease our exposure to risk, where it is trivially cheap to do so.
=> Drop some minimally-used dependencies

pkg/blobcache/dest.go
Prefer `defer`, and early returns, and straight-line code.
Effectively this is just one small bug fix (a `nil` reference on an error path)
The problem this is aiming to address is that nothing between initially creating `err3` and the code that removes the temporary file is allowed to `return`; i.e. adding new reasons for the function to fail is hard.
=> Refactor `blobCacheDestination.saveStream`

copy/single.go, storage/storage_dest.go
This primarily ensures that we log and use the same value.
Should not change behavior.
=> Avoid a redundant function call

README.md
I was really puzzled by the broken documentation at the current link. This version bump should fix it.
=> Fix GoDoc link at the top of the README file

copy/progress_bars.go, copy/single.go, directory/directory_dest.go, directory/directory_src.go, directory/directory_test.go, directory/directory_transport.go, directory/directory_transport_test.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/writer.go, docker/registries_d.go, docker/registries_d_test.go, openshift/openshift_src.go, ostree/ostree_dest.go, ostree/ostree_src.go, pkg/blobcache/blobcache.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
Digest values used throughout this library were not always validated. That allowed attackers to trigger, when pulling untrusted images, unexpected authenticated registry accesses on behalf of a victim user.
In less common uses of this library (using other transports or not using the containers/image.copy.Image API), an attacker could also trigger local path traversals or crashes.
=> [release-5.30] Fix CVE-2024-3727

version/version.go
This fixes CVE-2024-3727 .
Digest values used throughout this library were not always validated. That allowed attackers to trigger, when pulling untrusted images, unexpected authenticated registry accesses on behalf of a victim user.
In less common uses of this library (using other transports or not using the `containers/image/v5/copy.Image` API), an attacker could also trigger local path traversals or crashes.
=> [release-5.30] Release 5.30.1

version/version.go
The latest tagged release as of this moment, 5.30.1 is on the `release-5.30` branch, behind `main`.
That means that dependency automation tries to move users who use a recent commit from of `main` back onto `5.30.1`, possibly dropping some features.
This merge lets the tools know that `main` “is a superset of” 5.30.1; users on `main` can then update to `main` after this PR is merged.
=> Merge the `release-5.30` branch into `main`

docs/containers-transports.5.md
Consistently:
- Literal strings are in `backticks`
- Variables are _italic in underscores_
- Syntax meta-characters []{} are neither
This does not really work well in section headings, but at least the detailed descriptions should now be less misleading.
Fixes #2378.
=> Fix font choices in containers-transports.5

copy/manifest.go, docker/archive/reader.go, docker/daemon/daemon_dest.go, docker/internal/tarfile/reader.go, docker/internal/tarfile/src.go, docker/registries_d.go, internal/image/manifest.go, internal/manifest/docker_schema2_list.go, internal/manifest/list.go, internal/manifest/oci_index.go, manifest/common.go, manifest/docker_schema1.go, manifest/manifest.go, manifest/oci.go, oci/layout/oci_src.go, openshift/openshift-copies.go, openshift/openshift.go, signature/docker.go, signature/fulcio_cert.go, signature/fulcio_cert_test.go, signature/internal/json.go, signature/policy_config.go, signature/policy_config_sigstore.go, signature/policy_eval.go, signature/policy_eval_signedby.go, signature/policy_eval_sigstore.go, signature/policy_reference_match.go, transports/alltransports/alltransports.go
Typically, use `%q` instead of `%s` (or instead of `"%s"`), to expose various control characters and the like without interpreting them.
This is not really comprehensive; the codebase makes no _general_ guarantee that any returned string values are free of control characters or other malicious/misleading metadata. Not even in returned "error" values (which can legitimately contain newlines, if nothing else).
A side effect of the code audit required by CVE-2024-3727 .
=> Quote various strings coming from untrusted sources

copy/encryption.go, docs/atomic-signature-embedded-json.json, ostree/ostree_src.go, pkg/blobcache/src.go, signature/internal/sigstore_payload.go, signature/internal/sigstore_payload_test.go, signature/simple.go, signature/simple_test.go, storage/storage_dest.go
A set of cleanups around creating/validating `digest.Digest` values, in places where it should not be exploitable.
A side effect of the code audit required by CVE-2024-3727 .
=> Non-security digest.Digest use cleanups

copy/progress_bars.go, docker/docker_image_src.go, internal/imagesource/stubs/get_blob_at.go, internal/private/private.go, oci/archive/oci_src.go, pkg/blobcache/src.go
if the specified length for the range is set to -1, then request all the data possible by using the "Range: <unit>=<range-start>-" syntax for the HTTP range.
=> docker: support for requesting chunks without end offset

internal/pkg/platform/platform_matcher.go
This follows the logic we already use for Windows, and matches the containerd/platforms package.
Fixes #2376.
=> Silently assume arm=v7, arm64=v8 on macOS

storage/storage_src.go
… tangentially related to https://github.com/containers/podman/issues/22575 :
- Go is a treacherously innocuous-looking language. Get rid of unnecessary named return values 
- Fix removal of the layer temporary file.
=> Fixes to storage’s `GetBlob`

storage/storage_dest.go
notify c/storage that the staged layer is not used and must be cleaned up on error.
=> storage: cleanup staged layer if unused

copy/progress_bars.go, copy/single.go, directory/directory_dest.go, directory/directory_src.go, directory/directory_test.go, directory/directory_transport.go, directory/directory_transport_test.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/writer.go, docker/registries_d.go, docker/registries_d_test.go, openshift/openshift_src.go, ostree/ostree_dest.go, ostree/ostree_src.go, pkg/blobcache/blobcache.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
Digest values used throughout this library were not always validated. That allowed attackers to trigger, when pulling untrusted images, unexpected authenticated registry accesses on behalf of a victim user.
In less common uses of this library (using other transports or not using the `containers/image/v5/copy.Image` API), an attacker could also trigger local path traversals or crashes.
---
This is a backport of #2404 . Thanks to @dcermak for independently validating this work via #2415 .
=> [release-5.29] Fix CVE-2024-3727

docker/docker_client.go, docker/docker_client_test.go, docker/errors_test.go
... per data in https://github.com/containers/image/issues/2203 .
=> Recognize "manifest unknown" errors reported by Harbor

version/version.go
Bump the version in the release-5.29 branch to v5.29.3 in preparation for getting the fixes in this branch into the RHEL 8.10/9.4 branches in the Buildah v1.33, Podman v4.9 and Skopeo v1.14 branches.  Then bump the branch version to the next dev version, v5.29.4-dev
=> [release-5.29] Bump to v5.29.3

storage/storage_dest.go, storage/storage_src.go
This is on top of #2416, _partially_ addresses some of the concerns, and adds FIXMEs for other aspects.
Hopefully we can have better fixes over time.
=> Short-term kludges for recent AdditionalLayerStore changes

version/version.go
As the title says.   Bumping c/storage to v1.54.0 and then c/image to v5.31.0 and v5.31.1-dev.  This is in preparation for Podman v5.1
=> Bump to c/storage v1.54.0 then c/image to v5.31.0 and then to v5.31.1-dev

version/version.go
As I just created a release-5.31 branch where v5.31.1-dev will live, bump this to v5.32.0-dev
=> Bump to v5.32.0-dev

version/version.go
I managed to set main to v5.31.1-dev rather than the release-5.31 branch.  I've corrected main with #2430 and this will correct the release-5.31 branch
=> [release-5.31] Bump c/image to v5.31.1-dev

docker/docker_image.go
Per https://github.com/containers/skopeo/issues/2346, that happens in the wild.
=> Don't abort listing tags when we encounter a digest

docker/docker_image_src.go, docs/containers-registries.conf.5.md, pkg/sysregistriesv2/system_registries_v2.go, pkg/sysregistriesv2/system_registries_v2_test.go
Implements https://github.com/openshift/enhancements/pull/1600#issuecomment-2099607551
Currently, c/image doesn't share creds to Additional Layer Store so it requires additional configurations for registry authentication. And the current means of registry authentication for Additional Layer Store doesn't seem to meet requirements for the platform: https://github.com/openshift/enhancements/pull/1600#pullrequestreview-1990049051
This commit fixes that issue by allowing c/image directly sharing creds to Additional Layer Store. Additional Layer Store doesn't need to have its own logic to fetch registry creds but it can receive them from c/image.
Additional Layer Store needs to provide a helper binary that is executed from c/image. This helper binary is registered to c/image using …
=> [Additional Layer Store] Enable Additional Layer Store to perform registry authentication

docker/docker_image.go, version/version.go
Cherry Pick https://github.com/containers/image/pull/2440 then bump to v5.31.1 and finally to v5.31.2-dev
=> [release-5.31]  Don't abort listing tags when we encounter a digest

docker/docker_image.go, version/version.go
Cherry Pick https://github.com/containers/image/pull/2440 then bump to v5.29.4 and finally to v5.29.5-dev
=> [release-5.29] Don't abort listing tags when we encounter a digest

docker/docker_client.go, docker/docker_client_test.go
It _seems_ that they originate from the authentication endpoint. Add more context to the error there to tell whether it is so.
See individual commits for details.
=> Add more context to errors when obtaining a registry access token

docs/containers-transports.5.md
This adds the last missing pieces from the list referenced in https://github.com/containers/image/pull/1416#issuecomment-1828716547 (and applies them also to `docker-archive:`)
=> Warn that docker-archive and oci-archive overwrite the whole file

signature/mechanism_openpgp.go
We already know that IsSigned is set; and SignedBy is the result of a lookup of SignedByKeyId , so log that value.
Currently we log MessageDetails.Signature, which will always be nil if SignedBy == nil; that's not particularly useful.
Reported in https://github.com/containers/skopeo/issues/2238 .
=> Improve the error message when MessageDetails.SignedBy == nil

go.mod
Per previous consensus, we intentionally keep the toolchain at .0 so that the package does not interfere with toolchain update decisions.
Revert the tooolchain dependency from 1.21.11 to 1.21.0; then (go mod tidy) removed it entirely.
=> Drop the toolchain directive from go.mod

internal/manifest/docker_schema2_list_test.go, internal/manifest/oci_index.go, internal/manifest/oci_index_test.go, internal/manifest/testdata/oci1.index.everything.json, internal/manifest/testdata/v2list.everything.json, manifest/docker_schema1_test.go, manifest/docker_schema2_test.go, manifest/fixtures/ociv1.everything.json, manifest/fixtures/v2s1.everything.json, manifest/fixtures/v2s2.everything.json, manifest/oci_test.go
So that, e.g., `skopeo copy` does not drop the `artifactType` field.
Also adds unit tests.
Fixes #2460 .
=> Preserve more-recently-added fields when copying/updating OCI indices

go.mod, go.sum, storage/storage_dest.go
… per discussion in https://github.com/containers/storage/pull/2001 .
=> Allow matching of compressed blobs converted on the fly to zstd:chunked

docker/docker_client.go, docker/docker_client_test.go
This is a few refactors currently living in #1968, split for separate review and merging — without the substance of that feature.
The net effect of this PR is to decrease memory requirements a tiny bit, and to add make tests a tiny bit more relevant and decoupled.
=> Clean up obtaining bearer tokens for registries

copy/compression.go, docker/docker_image_dest.go, pkg/blobinfocache/memory/memory.go
… filed as a separate PR to simplify future “real” work.
Overall, should not change behavior. See individual commit messages for details.
=> Trivial zstd:chunked-related cleanups

copy/compression.go, copy/single.go, internal/blobinfocache/blobinfocache.go, internal/blobinfocache/types.go, pkg/blobinfocache/boltdb/boltdb.go, pkg/blobinfocache/internal/test/test.go, pkg/blobinfocache/memory/memory.go, pkg/blobinfocache/none/none.go, pkg/blobinfocache/sqlite/sqlite.go, storage/storage_dest.go, storage/storage_test.go
A single DiffID may map to multiple TOC digest values. Record that in `BlobInfoCache`, and use it for layer reuse.
Also prefer reusing even TOC-matched layers by DiffID, when available.
@giuseppe I’d appreciate a preliminary review of the new logic; see individual commits.
<s>Draft: The `BlobInfoCache` implementations don’t actually store/record any data yet — so this is obviously completely untested.</s>
=> Record (TOC digest → DiffID) mapping in BlobInfoCache

copy/compression.go, internal/blobinfocache/blobinfocache.go, internal/blobinfocache/types.go, pkg/blobinfocache/boltdb/boltdb.go, pkg/blobinfocache/internal/prioritize/prioritize.go, pkg/blobinfocache/internal/prioritize/prioritize_test.go, pkg/blobinfocache/internal/test/test.go, pkg/blobinfocache/memory/memory.go, pkg/blobinfocache/sqlite/sqlite.go, storage/storage_dest.go
This is a subset of #2487 , ready for review; it doesn’t make _that_ much sense separately, but I’m filing it early to allow earlier review / merging, and to decrease the size of the later review. See #2487 for more on how this is intended to be used.
This is:
- One mostly unrelated bug fix
- A set of refactoring of the BlobInfoCache implementations, so that compression matching decisions are centralized in a single place.
- A change to correctly use `BaseVariantName` instead of hard-coding a zstd:chunked exception.
@giuseppe PTAL.
=> zstd:chunked refactoring for early review

copy/compression.go, copy/single.go, copy/single_test.go, docker/docker_image_dest.go, internal/blobinfocache/types.go, internal/imagedestination/wrapper.go, internal/manifest/manifest.go, internal/manifest/manifest_test.go, internal/private/private.go, pkg/blobinfocache/boltdb/boltdb.go, pkg/blobinfocache/internal/prioritize/prioritize.go, pkg/blobinfocache/internal/prioritize/prioritize_test.go, pkg/blobinfocache/internal/test/test.go, pkg/blobinfocache/memory/memory.go, pkg/blobinfocache/sqlite/sqlite.go
<s>**WIP, premature to review.**</s>
This should allow re-using on-registry zstd:chunked data on push, instead of re-pushing every time, or making the output not chunked.
This includes #2321, I’m filing it early just to have an URL to link to in #2189.
=> Record zstd:chunked format, and annotations, in BlobInfoCache

version/version.go
We are on the 5.32 branch and the previous release was 5.32.1.
@TomSweeneyRedHat FYI: I’m afraid the just-created 5.32.1 calls itself 5.33.1.
=> [release-5.32] Fix the version number

pkg/blobcache/blobcache_test.go
Based on a patch from #2512.
----
1. Use os.ReadDir to remove a few lines of code.
2. Don't wrap errors from os, they already contain file name.
=> pkg/blobcache: simplify test case

signature/internal/rekor_set.go, signature/internal/sigstore_payload.go, signature/simple.go
Based on a patch from #2512.
Feel free to close if it doesn't make much sense (I'm on the verge).
=> Introduce/use JSONFormatToInvalidSignatureError

.golangci.yml, copy/copy.go, manifest/docker_schema1.go, openshift/openshift-copies.go, signature/policy_reference_match.go, storage/storage_reference.go, tarball/tarball_src.go, tarball/tarball_transport.go
Based on patches from #2512, but much more conservative this time.
See individual commit descriptions for details.
=> Use %w to wrap errors, enable errorlint

docs/containers-policy.json.5.md, signature/internal/sigstore_payload.go, signature/internal/sigstore_payload_test.go, signature/internal/testdata/cosign2.pub, signature/policy_config_sigstore.go, signature/policy_config_sigstore_test.go, signature/policy_eval_signedby.go, signature/policy_eval_sigstore.go, signature/policy_eval_sigstore_test.go, signature/policy_types.go, signature/sigstore/generate_test.go
This is #2456 + various cleanups on top.
*Huge thanks* to @dcermak and @danishprakash for doing almost all the work in #2456.
This is a few preparatory commits + landing the whole feature at once; see https://github.com/mtrmac/image/tree/sigstore-multi-individual-commits for a (tiny bit older) version with individual commits, and showing the relationship to original #2456.
<s>Currently not tested end-to-end in practice.</s>
=> Add  `keyPaths`, `keyDatas` to `prSigstoreSigned`

docs/containers-policy.json.5.md, signature/fulcio_cert.go, signature/fulcio_cert_test.go, signature/internal/rekor_set.go, signature/internal/rekor_set_test.go, signature/policy_config_sigstore.go, signature/policy_config_sigstore_test.go, signature/policy_eval_sigstore.go, signature/policy_eval_sigstore_test.go, signature/policy_types.go
Add `rekorPublicKeyPaths` and `rekorPublicKeyDatas` options to `policy.json`.
This is on top of unmerged #2524.
Note an outstanding design question on `…Datas`: https://github.com/containers/image/pull/2524#issuecomment-2294570712 .
<s>Currently not tested end-to-end in practice.</s>
=> Add support for accepting multiple Rekor public keys

docs/containers-policy.json.5.md, signature/fulcio_cert.go, signature/fulcio_cert_test.go, signature/internal/rekor_set.go, signature/internal/rekor_set_test.go, signature/internal/sigstore_payload.go, signature/internal/sigstore_payload_test.go, signature/internal/testdata/cosign2.pub, signature/policy_config_sigstore.go, signature/policy_config_sigstore_test.go, signature/policy_eval_signedby.go, signature/policy_eval_sigstore.go, signature/policy_eval_sigstore_test.go, signature/policy_types.go, signature/sigstore/generate_test.go, version/version.go
This backports #2524 and #2526 :
> This adds the ability to accept sigstore signatures signed by any key from a set of several (_huge thanks_ to @dcermak and @danishprakash for doing almost all the work), and Rekor log presence proofs signed by any key from a set of several keys.
Cc: @TomSweeneyRedHat
=> Release 5.32.2

docker/daemon/client.go
Proxy environment works fine with docker-cli:
```bash
> export http_proxy=http://my_proxy:8080
> export DOCKER_HOST=tcp://my_docker_host_through_proxy
> docker info
> docker image inspect foo:bar
```
But does not work with skopeo:
```bash
> export http_proxy=http://my_proxy:8080
> skopeo inspect --daemon-host http://my_docker_host_through_proxy docker-daemon:foo:bar
FATA[0000] Error parsing image name "docker-daemon:foo:bar": initializing docker engine client: unable to parse docker host `my_docker_host_through_proxy`
```
It's just an example, I need to copy image to the docker-daemon host in actual.
After this pull request was patched, skopeo also worked fine with the proxy environment.
> Note that: I used a plain HTTP connection with docker-daemon, so it should be `http://` in skepeo …
=> Support proxy environment for docker client

docker/docker_image.go
Motivated by https://github.com/containers/skopeo/issues/2409 .
<s>Untested so far. </s>
=> Add a workaround for null values in the tag list

copy/progress_bars.go, copy/single.go, directory/directory_dest.go, directory/directory_src.go, directory/directory_test.go, directory/directory_transport.go, directory/directory_transport_test.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/writer.go, docker/registries_d.go, docker/registries_d_test.go, internal/signer/signer_test.go, openshift/openshift_src.go, ostree/ostree_dest.go, ostree/ostree_src.go, pkg/blobcache/blobcache.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
… to avoid cross-branch regressions
=> [release-5.27] Backport

.cirrus.yml, Makefile, copy/copy.go, copy/progress_bars.go, directory/directory_dest.go, directory/directory_src.go, directory/directory_test.go, directory/directory_transport.go, directory/directory_transport_test.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/writer.go, docker/registries_d.go, docker/registries_d_test.go, internal/iolimits/iolimits_test.go, internal/signer/signer_test.go, openshift/openshift_src.go, ostree/ostree_dest.go, ostree/ostree_src.go, pkg/blobcache/blobcache.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
#2547 + #2546 exist on later branches to maintain continuity.
=> [release-5.24] Backport #2418 + #2453

copy/progress_bars.go, copy/single.go, directory/directory_dest.go, directory/directory_src.go, directory/directory_test.go, directory/directory_transport.go, directory/directory_transport_test.go, docker/docker_client.go, docker/docker_image.go, docker/docker_image_dest.go, docker/docker_image_src.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/writer.go, docker/registries_d.go, docker/registries_d_test.go, internal/manifest/oci_index_test.go, internal/signer/signer_test.go, openshift/openshift_src.go, ostree/ostree_dest.go, ostree/ostree_src.go, pkg/blobcache/blobcache.go, pkg/blobcache/dest.go, pkg/blobcache/src.go, storage/storage_dest.go, storage/storage_image.go, storage/storage_reference.go, storage/storage_src.go
… to avoid cross-branch regressions
=> [release-5.26] Backport

version/version.go
To resolve CVE-2024-3727, backport to release-5.27
=> [release-5.27] Bump c/image to v5.27.1 and then to v5.27.2-dev

copy/sign.go, copy/single.go, docker/docker_image_src.go, internal/manifest/docker_schema2_list.go, internal/manifest/oci_index.go, internal/pkg/platform/platform_matcher.go, internal/pkg/platform/platform_matcher_test.go, pkg/blobinfocache/internal/prioritize/prioritize.go, storage/storage_src.go
I’m happy to split this into separate PRs for separate review; let me know.
=> Assorted clean ups, optimizations, and a small bug fix

.cirrus.yml
The "main" branch of Skopeo now requires Go 1.22, and eventually will depend on new c/image APIs.
=> Test against a stable branch of Skopeo

copy/progress_bars.go, copy/progress_bars_test.go
copy: Add unit tests for progress output
Prep for more work.
Signed-off-by: Colin Walters <walters@verbum.org>
---
copy: Don't print "skipped: 0.0b = 0.00%"
I think this is just visually noisy. If we didn't do a partial
fetch then let's just not say anything about it.
Signed-off-by: Colin Walters <walters@verbum.org>
---
=>  copy: Don't print "skipped: 0.0b = 0.00%"

manifest/oci.go
Luckily this only affects error messages.
=> Fix an incorrect expected MIME type when validating manifests

Makefile
It isn't actually used anymore.
This might speed up tests a bit.
---
… and fix test failures, e.g. https://cirrus-ci.com/build/6069124558749696 .
=> Stop installing golint

docker/docker_client.go, docker/errors.go, types/types.go
The ping v1 happens when the ping v2 fails, however, it causes the ping v2 error to be skipped and not output to the user. As result, when a registry has v1 and v2 enabled, and there are, for example, intermittent connectivity issues making the ping v2 fail, the user is presented with a misleading error saying "can't talk to V1 registry."
Since the only use of v1 is for the search API as a workaround for docker.io, and new container registries setups are very unlikely to be v1-only, there is little utility in keeping this v1 detection in the attempt to help the user realize their setup is v1-only, hence not compatible. On the contratry, it just presents the user with a misleading error in certain circumstances.
=> registry: remove ping v1

pkg/compression/compression.go, pkg/compression/internal/types.go
The last outstanding item from very old https://github.com/containers/image/pull/1084 .
=> Document the semantics of the metadata created by pkg/compression

storage/storage_dest.go
Might be a fix for https://github.com/containers/image/issues/2602 .
=> Consistently use a string type for expectedLayerDiffIDFlag

docker/body_reader.go
The code was incorrectly setting it to "never", meaning the `bodyReaderMSSinceLastRetry` heuristic was never triggered, and, in effect, we would _always_ reconnect on `io.ErrUnexpectedEOF` or `syscall.ECONNRESET` .
This corrects the code - but it might also make more network failures user-visible instead of silently retried.
=> Actually record last retry time after reconnecting

copy/single.go, storage/storage_dest.go
... and, also, indirectly, confirm the hypothesis in https://github.com/containers/podman/issues/24308 .
=> Special-case an error message to make it clearer

copy/copy.go, directory/directory_dest.go, docker/archive/dest.go, docker/daemon/daemon_dest.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, docker/internal/tarfile/src_test.go, docker/tarfile/dest.go, internal/imagedestination/impl/compat.go, internal/imagedestination/wrapper.go, internal/private/private.go, oci/archive/oci_dest.go, oci/layout/oci_dest.go, openshift/openshift_dest.go, ostree/ostree_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go
This should allow returning precisely the correct image ID from pulls, improving on https://github.com/containers/common/pull/2202 .
To be used in c/common https://github.com/containers/common/pull/2209 .
<s>Absolutely untested at this point.</s>
=> Add Copy.Options.ReportResolvedReference

go.mod, go.sum, version/version.go
Bumping c/image to v5.33.0 after vendoring c/storage v1.56.0
This is in preparation for Podman v5.3
=> Bump c/storage to v1.56.0, c/image to v5.33.0

signature/fulcio_cert_stub.go, signature/internal/rekor_set_stub.go
#2526 has broken building v5.32.2 with the `containers_image_fulcio_stub` and `containers_image_rekor_stub` build tags, as the signatures for `verifyRekorFulcio()` and `VerifyRekorSET()` were updated without updating the corresponding stubs.
This PR updates the stubs to match
=> Update stubs to match signature of actual methods

docker/distribution_error.go, docker/distribution_error_test.go
in distribution v3, the registry/client package became internal. this change copies `responseChallenges` from upstream, removing the last reference to registry/client in this repo, making it ready for the distribution v3 bump, whenever that comes.
---
NOTE: I expected this change to cause `go mod tidy && go mod vendor` to remove the `challenge` package from the vendor dir, but that didn't happen - not sure why.
=> docker: drop use of external distribution challenge pkg

storage/storage_dest.go
We record (some) `CompressedDigest`/`CompressedSize` when pulling a layer from registry; but, previously, we would lose these values (and record uncompressed values) when creating a duplicate of a layer already present in storage. Eventually, the original layer might get deleted and then we would only find a match in `BlobInfoCache`, under more restrictive conditions.
Instead, try to propagate the value to the duplicated layer. This might not work if the layer has multiple compressed representations, but that's hopefully not all _that_ frequent.
This activates the other half of https://github.com/containers/storage/pull/1830 .
=> Propagate `CompressedDigest`/`CompressedSize` when reusing data from another layer

internal/manifest/docker_schema2_list.go, oci/internal/oci_util.go
… from browsing the output of `golangci-lint --enable-all`. =
(There are tons of other warnings, many outright unwanted, most stylistic and unimportant — I’m not claiming these are the 2 most important warnings, these are just the ones that stood out in the noise.)
=> Two small lint updates

docker/errors_test.go
Should not change (test) behavior, other than perhaps better test failure output.
=> Use testify's ErrorAs to simplify tests a bit

storage/storage_dest.go, storage/storage_test.go
<s>Absolutely untested, filing for early review.</s>
`createNewLayer` can add new entries to `s.filenames` for uncompressed versions of layers; these entries don't match `manifest.LayerInfos`, causing the existing logic to assume they are a config and to store them as `ImageBigData`.
That's both a potentially unlimited disk space waste (recording uncompressed versions of layers unnecessarily), and a memory pressure concern (`ImageBigData` is created by reading the whole blob into memory).
Instead, precisely track the digest of the config, and never include more than one file in `ImageBigData`.
Blobs added via `PutBlob`/`TryReusingBlob` but not referenced from the manifest are now ignored instead of being recorded inside the image.
This is intended to fix …
=> Fix excessive memory and disk usage when sharing layers

storage/storage_dest.go
... and use `defer` to avoid that bug in the future.
(Split from larger work as an independent piece. Reviewing is easier when ignoring whitespace changes.)
=> Fix a missing s.lock.Unlock() on an error path

copy/single.go, directory/directory_dest.go, docker/docker_image_dest.go, docker/internal/tarfile/dest.go, internal/imagedestination/stubs/original_oci_config.go, internal/imagedestination/wrapper.go, internal/private/private.go, oci/archive/oci_dest.go, oci/layout/oci_dest.go, openshift/openshift_dest.go, pkg/blobcache/dest.go, storage/storage_dest.go, storage/storage_src.go
This is primarily motivated by preparing for the zstd:chunked logic, but potentially useful separately:
- Have the generic code provide the image config, and thus DiffIDs, at the start of the copy. Therefore we can start committing staged chunked layers immediately, we don’t have to wait for all of them to be staged. That might be a fairly significant performance benefit.
- Support obtaining DiffIDs from v2s2 images as well. Right now that only happens in theoretical corner cases; we will want to enforce that for all images in the future.
- (Some mostly-unrelated cleanups of handling of zero-length manifests.)
<s>At this point absolutely untested.</s>
Cc: @giuseppe , filing early to allow a preliminary review in case I have missed anything important.
=> In pulls, compute DiffIDs earlier, and also for v2s2

docker/daemon/client.go
This corrects an issue where previously connections to the Docker daemon on Windows would attempt to add a TLS config, changing the scheme to https instead of http, and breaking the client.  This changes named pipes (returned as `npipe` by the docker client library) to mimic the behavior of unix sockets.
I tried to add tests for this case, but the base transport and scheme variables are not exposed from the docker client, so there wasn't a clear way to test this change.  I have tested this locally on a Windows machine, ensuring that accessing the daemon works after this change.
=> Fix docker daemon on Windows trying to use https instead of http for named pipes

docs/containers-transports.5.md, go.mod, internal/reflink/reflink_linux.go, internal/reflink/reflink_unsupported.go, oci/internal/oci_util.go, oci/internal/oci_util_test.go, oci/layout/fixtures/files/a.txt, oci/layout/fixtures/files/b.txt, oci/layout/oci_dest.go, oci/layout/oci_dest_test.go, oci/layout/oci_transport.go, oci/layout/oci_transport_test.go, oci/layout/reader.go, oci/layout/reader_test.go
Taken over from https://github.com/containers/image/pull/2567 but:
* Added tests for the three commits
* Use reflinks when adding a file
=> OCI layout extensions

oci/layout/oci_transport.go
... to reinforce the rule that `*_transport.go` needs to have comprehensive unit tests, to the fullest possible extent.
=> Add a comment justifying lack of unit test coverage

signature/internal/errors.go, signature/internal/rekor_set.go
otherwise:
```console
% go build -tags ' containers_image_fulcio_stub containers_image_rekor_stub' ./...
signature/internal/sigstore_payload.go:83:9: undefined: JSONFormatToInvalidSignatureError
```
=> Move JSONFormatToInvalidSignatureError to an unconditionally-included file

storage/storage_dest.go
After https://github.com/containers/storage/pull/2155 , we ~always compute `UncompressedDigest`, but the current code was expecting that to happen only when `convert_images` is set (and we consume the whole compressed blob).
That is breaking pulls of chunked images, e.g. https://api.cirrus-ci.com/v1/artifact/task/6559054106984448/html/sys-podman-debian-13-rootless-host-sqlite.log.html :
```
internal error: PrepareStagedLayer returned CompressedDigest "" not matching expected "sha256:…"
```
Update the code to not blindly assume that `CompressedDigest` is set, and to expect `UncompressedDigest` to be set much more frequently. Originally from https://github.com/containers/image/pull/2613 , and tested as a part of the full patch set.
Separate Podman tests to confirm this truly fixes the test …
=> Update for c/storage almost always computing UncompressedDigest

go.mod, go.sum, version/version.go
As the title says:
c/storage to v1.56.1
c/image to v5.33.1
in preparation for Podman v5.33.1
=> [release-5.33] Bump c/storage to v1.56.1, c/image to v5.33.1

docker/docker_client.go
This is not a security vulnerability because the registry can just as well send a manifest modified to match, but doing this correctly protects us in case this function were used for other purposes in the future.
Fixes #2687.
=> Validate digests of data downloaded while fetching sigstore attachments

go.sum, version/version.go
... so that Go understands the `main` branch is ahead.
=> Merge tag 'v5.33.1' into `main`

docker/registries_d.go, pkg/sysregistriesv2/system_registries_v2.go, pkg/tlsclientconfig/tlsclientconfig.go
There is a expected race condition between listing files and actually opening them. Between that time the file might have been removed already. This is not really a real error so we should just ignore it as otherwise flakes will happen in the wild.
See the first commit for a real flake, the other two ones I have not observed but I thought I might as well fix it for all .d readers. Are there other files I missed?
=> ignore ENOENT errors when parsing .d files

go.mod, go.sum, version/version.go
Bumping c/image to v5.34.0 after vendoring c/storage v1.57.0
This is in preparation for Podman v5.4
=> Bump c/storage to v1.57.1, c/image to v5.34.0, then to v5.35.0-dev

oci/layout/fixtures/name_lookups/index.json, oci/layout/oci_transport.go, oci/layout/oci_transport_test.go, oci/layout/reader_test.go
This pull request adds the docker media types when reading back OCI formats, along with the corresponding tests.  This is from running into cases where docker images were built with the docker media types.  To avoid having to convert all of the existing manifests so that the original types can be maintained, this code adds support for reading the docker specific formats since the OCI formats are backwards compatible with the docker formats (https://github.com/opencontainers/image-spec/blob/main/media-types.md).
=> Add docker media types in OCI formats

copy/single.go, manifest/oci.go, ostree/ostree_src.go, pkg/sysregistriesv2/system_registries_v2.go, signature/internal/sigstore_payload_test.go, storage/storage_transport.go
… discovered while looking at for opportunities to benefit from new features of Go 1.23 and Go 1.24, hence a fairly random collection.
=> Small cleanups + one bug fix

oci/layout/oci_dest.go, oci/layout/oci_src.go, oci/layout/oci_src_test.go
The podman artifact store needs a method to get the actual local path on disk to the blobs. This is needed so we can then bind mount the files into the container, of course the caller must ensure we treat the files as read only. The digest based nature of the store will break if the files are modified.
=> oci/layout: add GetLocalBlobPath()

go.mod, go.sum
This PR simply bumps `go-jose` to v4.0.5, fixing CVE-2025-27144
=> OCPBUGS-51217: CVE-2025-27144: Bump go-jose to v4.0.5

oci/archive/oci_dest.go, oci/layout/oci_delete.go, oci/layout/oci_dest.go, ostree/ostree_dest.go, pkg/blobinfocache/sqlite/sqlite.go, pkg/sysregistriesv2/shortnames.go, sif/load.go, storage/storage_dest.go
For objects (particularly files) that we write to, we should to check the return value of `f.Close()` and pass error back to the caller if this fails.
I recently read https://www.joeshaw.org/dont-defer-close-on-writable-files/ and while working on another PR in this repo I noticed that some some writable files had the `defer f.Close()` pattern, so I did a grep to find similar calls, and for cases involving writeable file, changed the defer function to capture the result of calling `Close()`, and if the `err` value of the parent is `nil`, then set it for the caller.
In this manner errors on close will be returned to the caller, but won't mask other errors if an error was already set.
This adjusts those to one of the patterns in that article, e.g.:
```golang
func doThing() (err error) { …
```
=> fix: handle error on Close() of writable objects

.cirrus.yml, .codespellrc, Makefile
See individual commits for details.
=> Misc small nits to CI and build

docker/docker_client.go
I'm trying to set proxy for single-side image proxy(only for src-image or dest-image, maybe you can combine these two proxy options) and find some err,  fix it by the way
=> fix: typo err and grammar err

go.mod, go.sum
... so that the referenced version is larger than 1.57.2 required by Skopeo, and we don't downgrade and lose a required API.
FYI @Luap99
=> Update c/storage after https://github.com/containers/storage/pull/2276

docker/docker_client.go, docker/docker_client_test.go, docker/docker_image_dest.go
Returning the size required by the `TryReuseBlob`/`PutBlob` API; otherwise we could put `-1` into manifests.
- When looking for inexact matches, this will cause the matches to be skipped.
- When checking for an exact match, this will cause an upload failure; we don't have any other way to handle pre-existing blobs on the destination.
---
<s>For now, completely untested.</s>
=> Don't silently ignore errors determining size in TryReuseBlob

docker/docker_client.go, types/types.go
dockerClient will use http client to fetch manifest、blob and do some network request. Golang build-in http library  will use `HTTP_PROXY`、`HTTPS_PROXY` environment variables to config proxy for network. But the  environment variables cannot make flexible control of proxy behaviours. So I want to declare proxy configuration explicitly.
=> Add proxy for dockerClient

go.mod
This is a very minimal change, just to handle the version bump.
I intend to let Renovate do the dependency updates. And a separate PR to actually benefit from new language features will follow.
=> Update to Go 1.23

storage/storage_dest.go
reused.Digest is not always blobDigest, it might be uncompressedDigest; but we must have a blobDiffIDs entry for reused.Digest.
=> [crio-1.31] Fix layer reuse in schema1 images

tarball/tarball_src.go
See https://github.com/containers/podman/issues/25593 .
This is an _absolutely untested_ demonstration of what probably needs fixing.
=> Correctly compute DiffID, and try to set the correct MIME type, for non-gzip input to `tarball:`

tarball/tarball_src.go
This is a backport of #2795.
Marked as draft, pending a decision on whether we can include this. Cc: @TomSweeneyRedHat
=> [5.34] Correctly compute DiffID, and try to set the correct MIME type, for non-gzip input to `tarball:`

version/version.go
As the title says.  This will start the SIC dance to eventually solve: https://issues.redhat.com/browse/RHEL-85218 and https://issues.redhat.com/browse/RHEL-85218 up in Podman for the RHEL 9.6/10.0 ZeroDay.
=> [release-5.34] Bump c/image to v5.34.3

go.mod, go.sum, version/version.go
Bump 
c/storage to v1.58.0
c/image to v5.35.0.
This is the second SIC vendor dance step for
Podman v5.5.0
=> Bump c/storage to v1.58.0, c/image to v5.35.0

go.mod, go.sum
Bots generally update direct dependencies, and dependencies with known vulnerabilities.
For indirect dependencies which are over a year old, and either have a newer tagged release or haven’t been using a tagged release anyway, update to the latest version.
(This does nothing about dependencies with no upstream activity, or officially deprecated or even archived.)
=> Update old indirect dependencies

.cirrus.yml, Makefile, contrib/cirrus/runner.sh
It was removed in https://github.com/containers/storage/pull/2308 .
=> Stop setting the btrfs_noversion build tag

docker/docker_image_dest.go
... not to registries with X-R-S-S (that would immediately fail, when uploading to such a registry, with no opt-out), and not to
lookaside (that would _work_ if users set up lookaside).
Before this PR, _if the image had any non-sigstore signatures_, we would upload both the non-sigstore and sigstore signatures to lookaside.
@mheon @TomSweeneyRedHat PTAL. The bug has been that way for 2.5 years. I think the combination of required circumstances (an image must have both kinds of signatures, and the user must have configured lookaside, not use of sigstore tags, while somehow requiring sigstore signatures) makes it unlikely that users would rely on it, but I can’t quite rule it out.
=> Only upload sigstore signatures to the sigstore tag schema

Makefile, contrib/cirrus/runner.sh
This is a quick and dirty fix but should get the job done and ensures the tests are actually run by CI. The idea is simple to not waste resources we just look for the test names using
ensureTestCanCreateImages() to skip as rootless.
=> CI: run tests that need root as root

.cirrus.yml
... to simplify, and to allow using recent packages.
We were using Debian because previously we were using Ubuntu, and that was because Ubuntu was the native distribution of Travis even before we were running CI in any kind of container; so there seems to have been no specific intent to use a non-Fedora OS, at least originally.
=> Run CI all on the Fedora images

Makefile, contrib/cirrus/runner.sh
The filter already assumes that subpackage, by grepping for a package-private function name, anyway.
Cc: @Luap99
=> Restrict the root-only tests to ./storage

signature/simplesequoia/options.go, signature/simplesequoia/signer_stub.go
This API is proven end-to-end in https://github.com/containers/image/pull/2876 and https://github.com/containers/skopeo/pull/2645 , but it is not yet convenient to use becahse the Rust dependency has to be compiled manually.
So, for now, add the API as a stub only; that allows building the CLIs and tests on top, and they will light up once the backend is added.
Cc: @Luap99 (@ueno ). I think the linked PRs show that the API is viable, and something we can commit to right now; adding a do-nothing stub might help with the CI inclusion / packaging ordering, as discussed, earlier.g. in https://github.com/containers/skopeo/pull/2645#discussion_r2197188801 .
=> Add a new Signer API for creating simple signing signatures with Sequoia-PGP

.cirrus.yml
This matches https://github.com/containers/skopeo/pull/2661 , without it, any Skopeo test is going to fail, as in https://github.com/containers/image/pull/2905/checks?check_run_id=46601934935
@lsm5 PTAL.
=> Update the CI image, to match Skopeo's updated test code

.cirrus.yml
This matches https://github.com/containers/skopeo/pull/2661 , without it, any Skopeo test is going to fail, as in https://github.com/containers/image/pull/2905/checks?check_run_id=46601934935
=> [release-5.36] Update the CI image, to match Skopeo's updated test code

docker/docker_client.go, oci/layout/oci_src.go
As of `go-connections` 0.6.0, there is no difference between "server" and "client" configuration; so, take this opportunity to switch from "server" defaults in client contexts, which were used for an unknown reason.
Also, don't use the whole `tlsconfig.ClientDefault()`, to _slightly_ move into the direction of using the Go built-in defaults, and to get a _bit_ closer to getting out of the business of managing TLS policy.
The TLS configuration in `docker/daemon` continues to use the full `tlsconfig.Client()`, because that's (to an extent) consistent with the defaults of `github.com/docker/docker/client`.
Should not change behavior (but the update from `go-connections` 0.5.0 to 0.6.0 did change the list of accepted TLS 1.2 cipher suites).
=> Losen the dependency on go-connections/tlsconfig

signature/sigstore/rekor/openapi_infra.go
The context must be valid for the entire lifetime of the request including reading the body, as such it is invalid to return the body after cancelling the context, depending of if all the response data arrived already or not this then might fail.
To fix this simply do not cancel the context here, we could move the cancel() up to the caller function that processes the body. However as that one already closes the body there should be no need to cancel the context to end the request.
Fixes: #2936
=> rekor: do not cancel http context
