- .travis.yml
> .travis.yml: configure Travis

- signature/docker.go
> signature: docker: fix govet in fmt.Sprintf

- README.md
> README.md: status buttons on a row

- .gitignore
> remove empty .gitignore

- doc.go
> doc.go: rename pkg to image

- directory/directory.go
- directory/directory_dest.go
- directory/directory_src.go
> directory: split files and fix comments

- directory/directory_test.go
> directory: add unit tests

- image/image.go
- image/image_test.go
- signature/policy_eval_signedby.go
- signature/policy_reference_match_test.go
- types/types.go
Extrapolated from https://github.com/projectatomic/skopeo/pull/102/files#r68405593 and https://github.com/projectatomic/skopeo/pull/102/files#r68404616
@mtrmac PTAL
> Prepare for OCI and cleanup

- README.md
Signed-off-by: Brandon Philips <brandon.philips@coreos.com>
> README: add contact details

- manifest/manifest.go
- oci/oci_dest.go
> oci: override all mime types

- README.md
> README.md: remove todo

- image/image.go
There are no users left after #17.
> Drop genericImage.getLayer

- oci/oci_dest.go
- oci/oci_dest_test.go
- oci/oci_transport.go
- oci/oci_transport_test.go
Fix https://github.com/containers/image/issues/66
@mtrmac PTAL
> oci: blobs storage is blobs/{algo}/{hash}

- copy/copy.go
This is necessary to allow copying signed images into destinations which don't support signatures.
> Add Options.RemoveSignatures

- manifest/manifest.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
https://github.com/opencontainers/image-spec/commit/5861fdb7f74b145b30a54c01ac343e26cf14519e u
/cc @runcom  @philips
> Update oci image spec mime type

- docker/docker_image_dest.go
> docker: drop Docker-Content-Digest == providedDigest check

- oci/layout/oci_dest.go
- oci/layout/oci_dest_test.go
Fix https://github.com/projectatomic/skopeo/issues/198
I'll revendor in skopeo once this is merged. @mtrmac PTAL
> oci: layout: print mime type received when cannot convert manifest

- openshift/openshift.go
- openshift/openshift_transport.go
- openshift/openshift_transport_test.go
@mtrmac gave a fast look at this one, I still have to write tests but I was hoping to get an early review if this is what you were expecting.
Take care of https://github.com/projectatomic/skopeo/issues/194 and https://github.com/projectatomic/skopeo/issues/189. I'll take care of fixing skopeo once this is merged.
This change isn't impacting the policy though - it's using the port from the registry_uri to discover the registry. I'm honestly confused. Are we also changing the docker reference in the policy to be REGISTRYHOST:REGISTRYPORT? or it will still be  HOSTFROMKUBECONFIG:REGISTRYPORT?
> openshift: change reference to include registry URI

- docker/docker_image_dest.go
It's futile to attempt to re-upload a blob if a result of statting it is
401 unauthorized. The same applies to most of the other status codes.
> Do not ignore response status for blob stat

- copy/copy.go
Like https://github.com/projectatomic/atomic/issues/649#issuecomment-249144922
I didn't document anything yet as this is super likely to change soon - I'll create a card to refactor this code but right now it's the simplest solution I can think of.
> copy: provide progress

- copy/copy.go
Fix https://github.com/containers/image/pull/102#pullrequestreview-1550771
@mtrmac PTAL
> copy: fix Image ReportWriter Option

- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- docker/daemon/daemon_transport.go
- docker/daemon/daemon_types.go
- manifest/manifest.go
- transports/transports.go
- transports/transports_test.go
Carry https://github.com/containers/image/pull/79 @rhatdan @imcleod PTAL
Signed-off-by: Miloslav Trmač <mitr@redhat.com>
> Add docker-daemon ImageTransport

- .travis.yml
Trying to debug the failure in https://github.com/containers/image/pull/136
> upgrade golang

- directory/directory_src.go
- directory/directory_transport_test.go
- image/docker_schema1.go
- image/manifest.go
- image/sourced.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1389442
@mtrmac PTAL (needed for sigs+docker story)
> image: do not guess mime types, use a default

- copy/copy.go
- docker/daemon/daemon_types.go
- image/docker_schema1.go
- image/manifest.go
- types/types.go
> Use digest.Digest for DiffID values

- copy/copy.go
> copy: provide src&dest contexts

- docker/docker_client.go
In reply to https://github.com/projectatomic/docker/issues/214#issuecomment-263937593
@mtrmac PTAL
> docker: useful ping error message

- signature/mechanism.go
> provide better error when key not found

- docker/docker_image_dest.go
- signature/policy_config.go
Trivial cleanup, individual reasoning is in the commit messages.
> Remove obsolete FIXMEs

- docker/docker_client.go
> docker: check if ctx is nil

- docker/docker_client.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1403908
> docker: set basic auth when requesting bearer token

- docker/daemon/daemon_dest.go
- docker/daemon/daemon_src.go
- image/manifest.go
Takes care of https://github.com/projectatomic/skopeo/issues/239
> docker: remove github.com/docker/engine-api

- image/docker_schema2.go
- image/fixtures/schema2-to-oci1.json
Fix https://github.com/containers/image/issues/229
@mtrmac PTAL
> image: fix docker v2s2 -> oci image config conversion

- signature/fixtures/.gitignore
This updates the .gitignore in signature/fixtures to deal with some new gpg files I was seeing.
> Gitignore update

- image/manifest.go
- pkg/strslice/README.md
- pkg/strslice/strslice.go
- pkg/strslice/strslice_test.go
This (and the other story listed below) would be part of an effort to remove dependency on docker/docker.
https://www.pivotaltracker.com/story/show/134910101
https://www.pivotaltracker.com/story/show/134909997
Signed-off-by: Tiago Scolari <tscolari@pivotal.io>
> Copy docker StrSlice implementation to reduce dependency

- storage/storage_image.go
> storage: correctly read tar header

- copy/copy.go
- docker/docker_image_dest.go
This fixes issues pointed out in #266.
> Fix typos and unclear wording in comments

- oci/layout/oci_dest.go
- oci/layout/oci_src.go
- oci/layout/oci_transport.go
- vendor.conf
> oci: update to image-spec v1.0.0-rc6

- .travis.Dockerfile
- .travis.yml
This is a followup for https://github.com/containers/image/pull/279
> Use a container for CI

- vendor.conf
> vendor.conf: bump c/storage

- vendor.conf
ref https://github.com/projectatomic/skopeo/pull/367
> bump ostree-go dep

- docker/docker_client.go
> Log the unrecognized challenges if we don’t recognize any of them

- vendor.conf
This includes #310 to pass tests on my machine; I will rebase after #310 is merged.
> Update to image-spec 1.0.0

- ostree/ostree_dest.go
> ostree: store the image digest in the OSTree metadata

- docker/docker_client.go
Part of the fixes from #351 got undone
> Remove duplicate code for setupCertificates

- image/docker_schema1.go
- image/docker_schema2.go
- image/oci.go
ref https://github.com/projectatomic/skopeo/issues/436
> image: guard against config being nil

- Makefile
* Add dedicated build target
* Make sure development works on macOS
* Add target to call go fmt
Fix for issue #324
> Issue #324 Adding build and fmt target

- storage/storage_image.go
- storage/storage_reference.go
- storage/storage_reference_test.go
- storage/storage_test.go
- storage/storage_transport.go
- storage/storage_transport_test.go
- transports/alltransports/alltransports.go
- transports/alltransports/storage.go
- transports/alltransports/storage_stub.go
Signed-off-by: Hardy Ferentschik <hardy@hibernate.org>
> Issue #361 Making storage transport pluggable

- docker/daemon/client.go
`dockerclient.NewClient` requires `http.Client` to be set peculiarly for `unix://` sockets (like the default one).  Instead of doing that, just pass `nil` if the host is a `PF_UNIX` socket because all our overrides are TLS-related, hence inapplicable in that case.
Fixes https://github.com/projectatomic/skopeo/issues/445 .
Cc: @hferentschik
> Use a nil *http.Client for unix:// sockets

- signature/policy_config.go
- signature/policy_config_test.go
- vendor.conf
@mtrmac PTAL, see individual commits messages
> CVE and error logging fixes

- docker/docker_image_dest.go
Fix #381 
@jonboulle @mtrmac PTAL
> docker: relax status code check on put manifest

- docker/docker_image_dest.go
> Use client.HandleErrorResponse in HasBlob when unauthorized

- pkg/docker/config/config.go
Whenever the auth directory was defaulting to /run/usr/UID
it was assuming that /run/usr/UID existed. The change creates the
directory if it doesn't exist.
We were also creating the XDG_RUNTIME_DIR deirectory if the variable
was set but the directory didn't exist. Not a good idea so we error out
now when that happens.
Fixes https://github.com/projectatomic/libpod/issues/427
> Fix failure to make auth directory

- storage/storage_image.go
> Vendor in latest from containers/storage

- docs/policy.json.md
> Reformat policy.json.md to be used as a man page

- pkg/docker/config/config.go
If the image is a public image, credentials are not needed to pull it,
try pulling the image even if XDG_RUNTIME_DIR is set to a non-existent path.
Addresses https://github.com/projectatomic/libpod/issues/659
> Don't fail if XDG_RUNTIME_DIR is set to a non-existent path

- docker/docker_image.go
This probably isn't actually the best way to do this; in the docker client api, this is basically
```
repo, err := NewRepository(ctx, ref, baseURL, transport)
return repo.Tags().All()
```
But that API can't really use the SystemContext configuration, at least, not as-is.
> tags is a paginated api, need to follow Link headers

- pkg/docker/config/config.go
... and that this is not an oversight, per the conversation in https://github.com/containers/image/pull/453 .
> Clarify that err != nil && !os.IsNotExist(err) does not need to be handled

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
Cache previously loaded registries with the path to the specific config
file as the key.  Such kind of caching avoids redundantly loading the
config file.  The cache is thread safe and thus qualifies to be used
concurrently.
> sysregistriesv2: cache registries

- .travis.yml
- Makefile
- vendor.conf
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> make and travis: cross platform compile check

- docs/registries.conf.5.md
A few touchups to the registries.conf man page plus added info on the block section.
> Update registries.conf man

- README.md
> Make it easier for CONTRIBUTORS to find information

- .gitignore
- oci/layout/oci_dest.go
- types/types.go
@mtrmac have a look, hope that what you suggested on the issue.
> Issue #475 Add flag for image compress layer for oci destination

- Makefile
- README.md
- oci/layout/oci_transport_test.go
> skopeo moved to containers/skopeo

- docs/containers-policy.json.md
- docs/containers-registries.conf.5.md
- docs/containers-registries.d.md
> docs/: prefix manpages with "containers-"

- README.md
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>
Closes #479
> Fix license reference in README.md

- registries.conf
> fix manpage references to containers-registries.conf

- copy/copy.go
- docker/docker_client.go
Assorted cleanups unrelated to the specific topic I am otherwise working on.
> Misc. small cleanups

- copy/copy.go
If an image contains several times the same layer, the generated image
archive is not correct.
```
$ skopeo copy docker://gcr.io/google_containers/pause@sha256:0d093c962a6c2dd8bb8727b661e2b5f13e9df884af9945b4cc7088d9350cd3ee docker-archive:///tmp/pause.tgz:latest
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
32 B / 32 B [==============================================================] 0s
Copying blob sha256:f112334343777b75be77ec1f835e3bbbe7d7bd46e27b6a2ae35c6b3cfea0987c
303.91 KB / 303.91 KB [====================================================] 0s
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
32 B / 32 B [==============================================================] 0s
Copying …
```
> docker tarfile: use the cached digest if existing

- copy/copy.go
When copying an image, return the manifest of the new copy of the image, which may be different from the manifest in the image referred to by the source reference if a format conversion was required.  One possible approach for #518.
> copy.Image(): return the image's manifest

- pkg/blobinfocache/default.go
> blobinfocache: fix Debugf format error

- signature/policy_reference_match_test.go
- storage/storage_image.go
- tarball/tarball_src.go
> fix lint errors: consistent receiver names

- copy/copy.go
Don't make changes to manifests or the blobs they reference when we're writing to a location that's specified using a digested reference, since changing the manifest will break the reference.
> Don't update manifests when writing to digested references

- pkg/blobinfocache/memory.go
Serialize method calls via a mutex to avoid concurrent accesses to the
map leading to panics.
Fixes: https://github.com/containers/libpod/issues/2420
> blobinfocache: sync via mutex

- pkg/blobinfocache/memory.go
One microoptimization, and two comment/documentation updates because I’m scared of concurrency.
> Tiny cleanups to `memoryCache` `BlobInfoCache`

- docs/containers-transports.5.md
Fixes: https://github.com/containers/image/issues/540
Fixes: github.com/containers/skopeo/issues/590
> docs: containers-transports(5) manpage

- docker/docker_client.go
- docker/docker_image_src.go
- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
This is the code subset of #617; #617 will be rebased on top of this, to include only the documentation, which needs more work.
Cc: @vrothberg @saschagrunert
> Mirror cleanups - code only

- storage/storage_image.go
Because a `storage.Layer` only records a single `CompressedDigest` and `CompressedSize`, we may need to depend on the `BlobInfoCache`.
In that case, `TryReusingBlob` currently returns correct data about the uncompressed blob, causing the manifest ultimately sent to `PutManifest` to be updated, and potentially breaking digest references, or disabling the reuse if manifest updates are forbidden.
The extra information necessary to avoid the manifest update is just the compressed layer size, and with non-schema1 manifests that size is a part of the manifest and provided by the caller; so, we can
just return the caller's `BlobInfo` unmodified.
To make this work, `Commit` also needs to be updated to call `LayersByUncompressedDigest` on a `diffID` recorded in `blobDiffIDs` because the kinds of …
> Try harder in storageImageDestination.TryReusingBlob

- docs/containers-registries.conf.5.md
> Fix typo in docs/containers-registries.conf.5.md

- pkg/docker/config/config.go
Updates the GetAuthentication method adding debug messages showing
from where the credentials come from.
Close #510
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>
> config.go: log where credentials come from

- Makefile
We want to create a containers-image package so that container-common can
include all of these man pages in the distribution.
Replaces: https://github.com/containers/skopeo/pull/645
> Add ability to install man pages

- pkg/docker/config/config.go
Fixes: #662
Store user credentials to kernel keyring if AuthFilePath is "", otherwise set the credentials to the authfile path.
Related to my libpod PR https://github.com/containers/libpod/pull/3674
> use keyring when authfile empty

- docs/containers-transports.5.md
Touch up the containers-transports storage specificiation in the man page.
Fixes: #666
> Touch up transport man page

- ostree/ostree_src.go
`GetBlob` itself returns the uncompressed version of the layer data (and `LayerInfosForCopy` has already set up the caller to expect uncompressed sizes).
Fixes https://github.com/containers/skopeo/issues/702 .
(Only took us a year and a half to notice…)
@giuseppe PTAL
> OSTree: Return the uncompressed size for originally-compressed layers in GetBlob

- pkg/docker/config/config.go
not set/get credentials to/from kernel keyring
> use enableKeyring(false) to disable keyring

- copy/copy.go
Unless specified otherwise, default to using the gzip compressor.  If
left nil, we'll run into a nil dereference breaking existing consumers
of containers/image.
> copy: compression: default to gzip

- storage/storage_test.go
- vendor.conf
> fix cross-compilation by vendoring latest c/storage

- copy/copy.go
> copy: don't lose annotations of BlobInfo

- go.mod
- go.sum
@mtrmac @mrunalp @rhatdan PTAL.
> make container tools work with go-openssl

- manifest/docker_schema2.go
- manifest/oci.go
The manifests in containers storage lie since the layers are stored
uncompressed while, in some cases, being displayed as compressed in
the manifest.
Consider this case when updating the manifest to avoid immediate
errors.
> manifest update: consider that storage lies

- docs/containers-registries.conf.5.md
- registries.conf
Add a warning about fully specifying registries
to the search list.
> Add registries warning to registries.conf

- docker/docker_client.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/tarfile/dest.go
- docker/tarfile/src.go
- image/docker_schema2.go
- image/oci.go
- internal/iolimits/iolimits.go
- internal/iolimits/iolimits_test.go
- openshift/openshift.go
This includes and continues on top of #803; see discussion there.
Fixes: CVE-2020-1702
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1792796
> Restrict sizes of inmem processed blobs

- version/version.go
@mtrmac @rhatdan @mrunalp PTAL
> Release v5.2.0

- copy/copy.go
- copy/manifest.go
If the only change we were making to a manifest list was to change its MIME type (i.e., other updates to the list didn't materially change its contents), we wouldn't re-serialize the list, so we wouldn't actually change its MIME type.
> copyMultipleImages: re-serialize the list if we only want to change its MIME type

- copy/copy.go
We rarely (<1% chance) hit the following panic when use this library. I have gone through the code and think this is the place to catch exactly why this panic happens. Due to very hard to reproduce, we need to know why Acquire() gets error
```
panic: semaphore: released more than held
goroutine 403 [running]:
golang.org/x/sync/semaphore.(*Weighted).Release(0xc000582230, 0x1)
/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/semaphore/semaphore.go:98 +0x1b1
github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0xe, 0xc00067e8c0, 0x47, 0x2fd, 0x0, 0x0, 0x0, 0x0, 0xc0005d2780, 0x31, ...)
```
> When semaphore cannot acquire lock in the copy image, it should print out the error at least info level, not debug

- docs/containers-registries.conf.5.md
- registries.conf
Patch originally from fatherlinux <smccarty@redhat.com>
> Updated warning about short names.

- go.mod
- go.sum
> Update containers/storage to v1.16.5

- docker/tarfile/src.go
- docker/tarfile/src_test.go
> Fix crash on missing RootFS in docker/tarfile configs

- go.mod
- pkg/blobinfocache/boltdb/boltdb.go
> Update import path for bbolt

- manifest/docker_schema2.go
- types/types.go
> Expose image variant

- docs/containers-registries.conf.5.md
Signed-off-by: Kang HuaiShuai <khs1994@khs1994.com>
ref: #813
> Fixed containers-registries.conf.5.md error

- internal/pkg/platform/platform_matcher.go
- internal/pkg/platform/platform_matcher_test.go
- manifest/docker_schema2_list.go
- manifest/list_test.go
- manifest/oci_index.go
This is a set of simplifications created while working on #898 , but independent from that.
Filing it as a separate PR that should not change behavior (apart from some error messages) while I continue to work on a full solution for #898 , to make the actual fix later smaller and easier to review.
> Platform matching cleanups

- version/version.go
Waiting for https://github.com/containers/image/pull/960 , needs to be rebased on top.
> Release 5.5.0

- Makefile
... which changed Make targets.
> Update for https://github.com/containers/skopeo/pull/932

- docker/docker_image_src.go
- oci/layout/oci_src.go
> Coverity found potential nil dereference

- docker/tarfile/src.go
I have a tarball with a "./" prefix (so: `./manifest.json`, `./config.json`, `./<layer-hash>/layer.tar` etc etc). This tarball works with docker load, but does not work with skopeo inspect, which is why I'm here now :smile: 
I added some normalization using `path.Clean` to all places where we might be looking at the path of something in the tarball; since I assume 'security' concerns (e.g. `../../`) are taken care of in other places, this should not introduce new vulnerabilities.
Let me know if I need to adapt something.
> Look for normalized paths in tarfile.

- go.sum
- pkg/docker/config/config.go
> use container/storage/pkg/homedir

- copy/copy.go
Addressing https://github.com/containers/image/issues/999
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Update copier/imagecopier to fix race

- version/version.go
Want to get an update to fix some issues in Podman.
> Bump to v5.7.0

- docs/signature-protocols.md
Update reference to [`containers-registries.d.md`](containers-registries.d.md) when the file was renamed by #493.
> docs: update reference to containers-registeries.d.md

- copy/copy.go
Fix misleading network error `Error writing blob: unexpected EOF`
close #1058 
> Fix misleading network error

- docker/daemon/daemon_transport_test.go
- docker/docker_transport_test.go
- docker/lookaside_test.go
- docker/policyconfiguration/naming.go
- docker/policyconfiguration/naming_test.go
- docs/containers-policy.json.5.md
- go.sum
- openshift/openshift_transport_test.go
- signature/fixtures/policy.json
- signature/policy_config_test.go
- signature/policy_eval_test.go
@mtrmac @vrothberg @ashcrow PTAL
> subdomain matching in policy.json

- docker/docker_image_src.go
> Add check sys != nil

- docs/containers-registries.conf.5.md
- pkg/sysregistriesv2/shortnames.go
- version/version.go
@rhatdan PTAL
I cut a new release-5.10 branch and will move the main branch to 5.11-dev.
> [5.10] backports and cut 5.10.3

- copy/copy.go
This PR optimizes image copies for the scenario where the destination image is expected to exist.
The scenario occurs for a common usage of `skopeo sync`: when periodically synchronizing two registries. Where the set of source images are (mostly) unchanged, and already exist at the destination. For this scenario, fetching the destination image's manifest, and checking if it matches the source manifest. And skipping the 'copy' (ie. layer content checks and manifest update) if equivalent provides a performance improvement.
This check should be an opt-in. As the default scenario for image copying is assumedly copying an image to a new destination. And the manifest fetch is pessimistic in this case. The copy is also never skipped if the copy requires signing or encryption (through more work …
> Compare destination image manifest copy optimization/feature

- version/version.go
> Bump v5.10.4

- docker/docker_image_src.go
close http response body when reponse code is not 200.
Closes #1177
> fix GetBlob socket leak

- storage/storage_image.go
Concurrency is full of pitfalls and prone to errors.  To make the life
of future readers easier, improve the internal documentation and code
comments of the storage destination.
@rhatdan @giuseppe @mtrmac PTAL
> storage destination: improve doc comments re: concurrency

- version/version.go
> Bump to v5.11.1

- CONTRIBUTING.md
- internal/pkg/platform/platform_matcher.go
Author: I-Cat <the_kat690@hotmail.com>
AuthorDate: 2021-04- 02:09:00 +0000
Commit: I-Cat <the_kat690@hotmail.com>
CommitDate: 2021-04- 02:12:00 +0000
Msg: Make One Commit
Signed-off-by: I-CAT <the_kat690@hotmail.com>
> https for links

- pkg/docker/config/config.go
Reference Issue: https://github.com/containers/podman/issues/6717
Sister PR to: https://github.com/containers/podman/pull/10068
> Add SetCredentials which returns human-readable path for configured auth

- .cirrus.yml
> Cirrus: Updates due to master->main rename

- version/version.go
The current tagged image seems to be screwed up, Just pusing a new tag to see if this fixes the issue.
> Bump to v5.13.1

- storage/storage_image.go
As it turned out in containers/podman/pull/10700,
containers/image@db5fb6e introduced a bug in the put-blob logic where
the empty-layer info was used for all blobs that the worker will commit
to storage.
Fix the bug by correctly storing the empty-layer information for each
blob separately and use that inside the worker.
> storage: PutBlobWithOptions: fix EmptyLayer logic

- .cirrus.yml
Ref: https://github.com/containers/skopeo/issues/1282
> Cirrus: Grab skopeo from main branch

- docker/docker_image_src.go
> docker: remove duplicate debug log

- .cirrus.yml
Ref: https://github.com/containers/skopeo/pull/1374
> Cirrus: Sync. skopeo test to skopeo repo.

- version/version.go
> [release-5.15] Bump to v5.15.1

- go.mod
- go.sum
Bump c/storage to v1.34.1 to ready for Podman 3.3
> [release-5.15] Bump c/storage to v1.34.1

- version/version.go
Bump to v5.15.2 in the release-5.15 branch
> [release-5.15] Bump to v5.15.2

- copy/copy.go
Add a weighted semaphore to the copy options which allows for setting a
limit of simultaneously pulled layers within the current process space.
This allows for long-running processes, such as CRI-O, to set custom
limits based on the execution environment.
@mrunalp @mtrmac PTAL ... as so often, I feel like naming the option is the hardest part.
> copy.Options: semaphore to limit parallel pulls globaly

- docs/containers-transports.5.md
Fixes confusion reported in https://github.com/containers/podman/issues/11553 .
> Fix documentation of oci: and oci-archive:

- pkg/sysregistriesv2/system_registries_v2.go
- pkg/sysregistriesv2/system_registries_v2_test.go
- storage/storage_transport.go
Per https://github.com/containers/podman/issues/11934 .
> Fix possible out-of-bounds accesses in string indexing

- docker/docker_image_dest.go
... to make it a bit easier to detect uploads to non-registries.
> Log if a manifest upload doesn't contain a Docker-Content-Digest header

- .cirrus.yml
Depends on https://github.com/containers/skopeo/pull/1499
> Bump Fedora to release 35 & Ubuntu to 21.10

- manifest/common.go
- sif/load.go
> Run codespell on code

- version/version.go
- build(deps): bump github.com/klauspost/compress from 1.14.1 to 1.14.2
- build(deps): bump github.com/containers/storage from 1.38.0 to 1.38.1
- build(deps): bump github.com/containers/storage from 1.38.1 to 1.38.2
@rhatdan PTAL
> Release 5.19.1

- go.mod
- go.sum
- version/version.go
Trying to fix test failures from https://github.com/containers/image/pull/1536 .
> Release 5.21.1

- docs/containers-registries.conf.5.md
- storage/storage_image.go
> Fix codespell errors

- go.mod
- go.sum
- version/version.go
Vendor c/storage to backport fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2072452.
Also bump the version.
@TomSweeneyRedHat @mtrmac PTAL
> [release-5.19] vendor c/storage and cut v5.19.4

- .cirrus.yml
Depends on https://github.com/containers/automation_images/pull/134
> Cirrus: use Ubuntu 22.04 LTS

- pkg/docker/config/config.go
In these cases we would not have _any_ log entry about the file, confusing log readers who expected to see something.
Also, both of these situations are non-obvious and worth calling attention to.
> Log invalid and empty credential helper entries

- go.mod
- go.sum
... to fix reads of compressed data by docker-archive:
```
go get github.com/klauspost/pgzip@master
go mod tidy
```
> Update for https://github.com/klauspost/pgzip/pull/50

- version/version.go
- Make the pseudo-config used in sigstore attachments a bit more valid
- Recognize invalid error responses of `registry.redhat.io`
> Tag 5.23.1

- docs/containers-policy.json.5.md
Signed-off-by: Sam Morris <sam@robots.org.uk>
> Fix unordered list formatting in containers-policy.json(5)

- README.md
> Add missing documentation of build tags

- pkg/docker/config/config.go
Fixes #1301.
Warning: Completely untested.
> Correctly report a credHelpers location in SetCredentials

- docker/internal/tarfile/reader.go
> Add support for non-seekable files in docker-archive: sources

- Makefile
- go.mod
- go.sum
- pkg/sysregistriesv2/shortnames.go
> Vendor in latest containers/storage

- storage/storage_src.go
All we need in this case is an anonymous temporary file, so unlink the file immediately after creating it.  This avoids leaking space if the caller forgets to call `Close()` (and the process exits).
This would have mitigated https://github.com/containers/skopeo/pull/1837 which was a missing `Close()` in the skopeo proxy code.
(It'd be better to use Linux `O_TMPFILE`, but this path is
portable and avoids a new dependency)
Signed-off-by: Colin Walters <walters@verbum.org>
> storage: Immediately unlink tmpfile

- pkg/docker/config/config.go
- pkg/docker/config/config_test.go
This is a cleanup for #1751, should not change behavior.
Cc: @cgwalters
> Don't duplicate the getPathToAuth rules for user-specified paths in getAuthPaths

- .cirrus.yml
Ref: https://github.com/containers/skopeo/pull/1821
> Cirrus: Use F37 CI VM Image

- version/version.go
Now supports both creating and verifying sigstore signatures that use
Fulcio and Rekor.
A New API for signing images during copy.
docker-archive: now can read non-seekable streams.
Improved error messages for registry errors.
- Introduce oci/{archive,layout}.ImageNotFoundError
- Don't use any default path fallbacks if the user specified a path
- Introduce signature/sigstore.NewSigner
- Introduce signature/simplesigning.NewSigner
- Add pkg/cli/sigstore
- Add functional-option NewPRSigstoreSigned
- Add signature/sigstore.GenerateKeyPair
- Avoid confusion about 404 on lookaside
- Heuristically warn about lookaside servers serving HTML
- Add a limit for the total number of signatures in lookaside
- Update the public.ecr.aws error with current data
- Add a test for isManifestUnknownError
- …
> Release v5.24.0

- docker/body_reader.go
- docker/body_reader_test.go
- docker/docker_client.go
- version/version.go
> [release-5.24] Reconnecting blob reader

- docker/body_reader.go
> Simplify bodyReader.errorIfNotReconnecting

- go.mod
- go.sum
- openshift/openshift-copies.go
> fix(deps): update module github.com/imdario/mergo to v1

- internal/manifest/list.go
- internal/manifest/oci_index.go
- internal/manifest/oci_index_test.go
Adding instance to list should automatically add special annotations if any.
> list,oci_index: automatically add inbuilt annotations on add

- docs/containers-registries.conf.5.md
... trying to cover things like GetDigest / GetRepositoryTags / SearchRegistry.
Fixes #2060 .
> Clarify where mirrors are used

- storage/storage_src.go
Unfortunately the eager removal of the temp file does not work on all versions of Windows and causes an error. To work around this we have to fallback to relying on the caller to invoke `Close()`
> fix removal of temp file in GetBlob on Windows

- version/version.go
@TomSweeneyRedHat / @mheon PTAL for a final confirmation.
> [release-5.29] Tag 5.29.1

- internal/manifest/oci_index.go
A part of #2302 I forgot to commit.
> Add a comment, to point at a possible update point

- copy/progress_bars.go
Per https://github.com/containers/podman/issues/20634#issuecomment-1960164114 .
> Provide data to correctly report throughput on partial pulls

- directory/directory_dest.go
- directory/explicitfilepath/path.go
- docker/docker_client.go
- docker/registries_d.go
- go.mod
- go.sum
- oci/layout/oci_dest.go
- ostree/ostree_dest.go
- pkg/blobinfocache/boltdb/boltdb.go
- pkg/docker/config/config.go
- pkg/sysregistriesv2/system_registries_v2.go
- signature/policy_config.go
use a faster alternative to os.Stat and os.Lstat to check whether a path is present
> use containers/storage/pkg/fileutils/(Exists,Lexists) 

- pkg/blobinfocache/default.go
Needed for: https://github.com/containers/podman/issues/22825
> blobinfocache: add function to delete the cache directory

- .cirrus.yml
… to try to resolve the failures in #2452
> [release-5.30] Test this release branch with a corresponding Skopeo release branch

- docker/docker_image.go
- version/version.go
Cherry Pick https://github.com/containers/image/pull/2440 then bump to v5.30.2 and finally to v5.30.3-dev
> [release-5.30] Don't abort listing tags when we encounter a digest

- version/version.go
Bump to v5.24.3 then to v5.24.4-dev to address CVE-2024-3727
> [release-5.24] Bump c/image to v5.24.3 then to v5.24.4-dev

- go.mod
- go.sum
- storage/storage_dest.go
ApplyDiffWithDiffer is deprecated and going to be removed in a future release
> storage: use PrepareStagedLayer instead of ApplyDiffWithDiffer

- signature/policy_config.go
- signature/policy_config_test.go
resolves:  https://github.com/containers/podman/issues/23852 
Modified only policy.json file to resolve above issue ---> if this implementation looks Good will modify unit-test cases also.
> Fix: Improving error log message for missing policy.json file

- signature/policy_types.go
Add `omitempty` annotations to PKI APIs
> Fix omitempty for PKI  struct

- docker/archive/transport.go
- docker/archive/transport_test.go
- docker/daemon/daemon_transport.go
- docker/daemon/daemon_transport_test.go
- docs/containers-transports.5.md
- oci/archive/oci_transport.go
- oci/layout/oci_transport.go
- oci/layout/oci_transport_test.go
> Improve handling and documentation of various transport reference corner cases

- image/unparsed.go
- internal/image/unparsed.go
- types/types.go
Cc: @Luap99 , I’ve noticed some problematic users recently. I’ll also audit our codebases.
> Add warnings about direct use of ImageSource

- Makefile
See individual commit messages for details, let’s see what it takes…
> [release-5.29] Fix CI

- Makefile
See individual commit messages for details, let’s see what it takes…
Expected to be a superset of #2856 .
> [release-5.26] Fix CI

- go.mod
- go.sum
- version/version.go
> [release-5.36] Bump to c/image v5.36.1
